import { useEffect, useMemo, useState } from 'react'
import { CheckCircle2, FileCheck2, RefreshCw, ShieldCheck } from 'lucide-react'
import { academicRecordsAPI } from '@/services/api'

type Grade={id:string;percentage:number;letterGrade:string;cycle:{academicYear:string;term:string;status:string};student:{user:{firstName:string;lastName:string};studentNumber:string};course:{name:string;code:string;teacher:{user:{firstName:string;lastName:string}}}}
type Card={id:string;term:string;average:number;attendanceSummary?:{total:number;present:number;absent:number;late:number;excused:number;sick:number;suspended:number;attendanceRate:number|null};publicationStatus:string;approvedAt?:string;student:{id:string;studentNumber:string;user:{firstName:string;lastName:string}}}
type Transcript={student:{name:string;studentNumber:string;grade:string};rows:Array<{id:string;percentage:number;letterGrade:string;credits:number;cycle:{academicYear:string;term:string};course:{name:string;code:string}}>;summary:{credits:number;cumulativeGpa:number|null;officialRecords:number};dataPolicy:string}

export default function AcademicRecordsControlCenter(){
 const [academicYear,setAcademicYear]=useState('2026-2027'),[term,setTerm]=useState('Semester 1 · Trimester 1'),[grades,setGrades]=useState<Grade[]>([]),[cards,setCards]=useState<Card[]>([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[transcript,setTranscript]=useState<Transcript|null>(null)
 const load=async()=>{setBusy(true);try{const [g,c]=await Promise.all([academicRecordsAPI.review({academicYear}),academicRecordsAPI.reportCards()]);setGrades(g.data.data||[]);setCards(c.data.data||[])}catch(error:any){setNotice(error?.response?.data?.message||'Unable to load official academic records.')}finally{setBusy(false)}}
 useEffect(()=>{void load()},[])
 const matching=useMemo(()=>grades.filter(item=>item.cycle.academicYear===academicYear&&item.cycle.term===term),[grades,academicYear,term])
 const students=new Set(matching.map(item=>item.student.studentNumber)).size,courses=new Set(matching.map(item=>item.course.code)).size
 const generate=async()=>{setBusy(true);try{const response=await academicRecordsAPI.generateReportCards({academicYear,term});setNotice(`${response.data.data.count} report card(s) generated for controlled review.`);await load()}catch(error:any){setNotice(error?.response?.data?.message||'Report-card generation failed.')}finally{setBusy(false)}}
 const approve=async(id:string)=>{setBusy(true);try{await academicRecordsAPI.approveReportCard(id);setNotice('Report card approved; official grades were frozen for the transcript.');await load()}catch(error:any){setNotice(error?.response?.data?.message||'Approval failed.')}finally{setBusy(false)}}
 const viewTranscript=async(studentId:string)=>{setBusy(true);try{const response=await academicRecordsAPI.transcript(studentId);setTranscript(response.data.data)}catch(error:any){setNotice(error?.response?.data?.message||'Transcript unavailable.')}finally{setBusy(false)}}
 const publish=async(id:string)=>{setBusy(true);try{await academicRecordsAPI.publishReportCard(id);setNotice('Approved report card published to the student and parent portal.');await load()}catch(error:any){setNotice(error?.response?.data?.message||'Publication failed.')}finally{setBusy(false)}}
 return <section className="space-y-4 rounded-3xl border border-emerald-200 bg-emerald-50/50 p-5 dark:border-emerald-900/50 dark:bg-emerald-950/20">
  <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="flex items-center gap-2 text-xs font-black uppercase tracking-[.18em] text-emerald-700 dark:text-emerald-300"><ShieldCheck size={17}/>Official Academic Records</p><h2 className="mt-1 font-display text-2xl font-bold text-kcs-blue-950 dark:text-white">Grade validation, report cards and transcripts</h2><p className="mt-1 text-sm text-gray-600 dark:text-gray-300">Only teacher-submitted and administrator-approved grades enter the official transcript. No projected or invented grade is accepted.</p></div><button disabled={busy} onClick={()=>void load()} className="rounded-xl border border-emerald-300 px-3 py-2 text-sm font-bold text-emerald-800 dark:text-emerald-200"><RefreshCw size={16} className="mr-1 inline"/>Refresh</button></div>
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><input value={academicYear} onChange={e=>setAcademicYear(e.target.value)} className="rounded-xl border bg-white p-3 dark:border-kcs-blue-700 dark:bg-kcs-blue-950 dark:text-white"/><select value={term} onChange={e=>setTerm(e.target.value)} className="rounded-xl border bg-white p-3 dark:border-kcs-blue-700 dark:bg-kcs-blue-950 dark:text-white"><option>Semester 1 · Trimester 1</option><option>Semester 1 · Trimester 2</option><option>Semester 2 · Trimester 3</option><option>Annual final</option></select><div className="rounded-xl border border-gray-200 bg-white p-3 text-sm font-medium text-kcs-blue-950 dark:border-kcs-blue-600 dark:bg-kcs-blue-800 dark:text-white"><b>{matching.length}</b> final grades · <b>{students}</b> students · <b>{courses}</b> courses</div><button disabled={busy||!matching.length} onClick={()=>void generate()} className="rounded-xl border border-kcs-blue-600 bg-kcs-blue-700 px-4 py-3 font-bold text-white shadow-sm hover:bg-kcs-blue-800 disabled:border-gray-400 disabled:bg-gray-300 disabled:text-gray-600 disabled:opacity-100 dark:disabled:border-kcs-blue-600 dark:disabled:bg-kcs-blue-800 dark:disabled:text-kcs-blue-200"><FileCheck2 size={17} className="mr-1 inline"/>Generate report cards</button></div>
  {notice&&<p className="rounded-xl bg-white p-3 text-sm font-semibold text-kcs-blue-900 dark:bg-kcs-blue-900 dark:text-white">{notice}</p>}
  <div className="grid gap-3 lg:grid-cols-2">{cards.slice(0,20).map(card=><article key={card.id} className="rounded-2xl bg-white p-4 shadow-sm dark:bg-kcs-blue-900 dark:text-white"><div className="flex items-start justify-between gap-3"><div><b>{card.student.user.lastName} {card.student.user.firstName}</b><p className="text-xs text-gray-500 dark:text-gray-300">{card.student.studentNumber} · {card.term}</p><p className="mt-2 text-sm">Average: <strong>{card.average.toFixed(2)}%</strong></p>{card.attendanceSummary&&<p className="mt-1 text-sm">Présences: <strong>{card.attendanceSummary.present}</strong> · Absences: <strong>{card.attendanceSummary.absent}</strong> · Retards: <strong>{card.attendanceSummary.late}</strong> · Taux: <strong>{card.attendanceSummary.attendanceRate??'—'}%</strong></p>}</div><span className="rounded-full bg-kcs-blue-50 px-2 py-1 text-xs font-bold text-kcs-blue-800">{card.publicationStatus}</span></div><div className="mt-3 flex flex-wrap gap-2">{card.publicationStatus==='READY_FOR_REVIEW'&&<button disabled={busy} onClick={()=>void approve(card.id)} className="rounded-xl bg-emerald-700 px-3 py-2 text-sm font-bold text-white"><CheckCircle2 size={16} className="mr-1 inline"/>Approve and freeze</button>}{card.publicationStatus==='APPROVED'&&<button disabled={busy} onClick={()=>void publish(card.id)} className="rounded-xl bg-kcs-gold-500 px-3 py-2 text-sm font-bold text-kcs-blue-950">Publish to portals</button>}<button disabled={busy} onClick={()=>void viewTranscript(card.student.id)} className="rounded-xl border border-kcs-blue-200 px-3 py-2 text-sm font-bold text-kcs-blue-700 dark:border-kcs-blue-700 dark:text-kcs-blue-200">View official transcript</button></div></article>)}</div>
  {transcript&&<div className="rounded-2xl bg-white p-5 shadow dark:bg-kcs-blue-900 dark:text-white"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase text-kcs-gold-600">Approved records only</p><h3 className="text-xl font-bold">{transcript.student.name}</h3><p className="text-sm text-gray-500 dark:text-gray-300">{transcript.student.studentNumber} · {transcript.student.grade}</p></div><div className="text-right"><b>GPA {transcript.summary.cumulativeGpa??'—'}</b><p className="text-sm">{transcript.summary.credits} credits · {transcript.summary.officialRecords} records</p></div></div>{transcript.rows.length?<div className="mt-4 overflow-x-auto"><table className="min-w-[680px] w-full text-sm"><thead><tr className="border-b text-left"><th className="p-2">Academic year</th><th>Term</th><th>Course</th><th>Credit</th><th>Average</th><th>Letter</th></tr></thead><tbody>{transcript.rows.map(row=><tr key={row.id} className="border-b border-gray-100 dark:border-kcs-blue-800"><td className="p-2">{row.cycle.academicYear}</td><td>{row.cycle.term}</td><td>{row.course.name}</td><td>{row.credits}</td><td>{row.percentage.toFixed(2)}%</td><td className="font-bold">{row.letterGrade}</td></tr>)}</tbody></table></div>:<p className="mt-4 rounded-xl bg-amber-50 p-4 text-sm text-amber-900">No approved academic record exists. Nexus will not fabricate or project grades.</p>}</div>}
 </section>
}
