import { useEffect, useMemo, useState } from 'react'
import { History, RefreshCw, Search, SlidersHorizontal, X } from 'lucide-react'
import { useTranslation } from 'react-i18next'
import { attendanceAPI } from '@/services/api'

type HistoryRow = {
  key:string; kind:'student'|'staff'; date:string; name:string; identifier:string; group:string
  status:string; note:string; recordedBy:string; period:string; arrival:string; departure:string
}
const field='w-full rounded-xl border border-gray-200 bg-white px-3 py-2.5 text-sm dark:border-kcs-blue-700 dark:bg-kcs-blue-950 dark:text-white'
const statuses=['PRESENT','ABSENT','LATE','EXCUSED','SICK','SUSPENDED']
const frLabels:Record<string,string>={PRESENT:'Présent',ABSENT:'Absent',LATE:'Retard',EXCUSED:'Excusé',SICK:'Malade',SUSPENDED:'Suspendu'}
const iso=(date:Date)=>date.toISOString().slice(0,10)
const normalized=(value:unknown)=>String(value??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim()

export default function AttendanceHistoryPanel(){
  const {i18n}=useTranslation()
  const isFr=(i18n.resolvedLanguage||i18n.language||'fr').startsWith('fr')
  const tr=(fr:string,en:string)=>isFr?fr:en
  const today=iso(new Date())
  const initialFrom=(()=>{const date=new Date();date.setUTCDate(date.getUTCDate()-89);return iso(date)})()
  const [from,setFrom]=useState(initialFrom),[to,setTo]=useState(today)
  const [registers,setRegisters]=useState<any[]>([]),[staffRecords,setStaffRecords]=useState<any[]>([])
  const [query,setQuery]=useState(''),[kind,setKind]=useState('all'),[status,setStatus]=useState(''),[recorder,setRecorder]=useState(''),[group,setGroup]=useState('')
  const [loading,setLoading]=useState(false),[notice,setNotice]=useState('')
  const load=async()=>{setLoading(true);setNotice('');try{const [studentResponse,staffResponse]=await Promise.all([attendanceAPI.history(from,to),attendanceAPI.staffHistory(from,to)]);setRegisters(studentResponse.data.data?.registers??[]);setStaffRecords(staffResponse.data.data?.records??[])}catch(error:any){setNotice(error?.response?.data?.message??tr("Impossible de charger l’historique officiel.","Official history could not be loaded."))}finally{setLoading(false)}}
  useEffect(()=>{void load()},[])
  const rows=useMemo<HistoryRow[]>(()=>[
    ...registers.flatMap((register:any)=>(register.students??[]).map((student:any)=>({key:'student-'+register.date+'-'+register.className+'-'+student.id,kind:'student' as const,date:register.date,name:student.name,identifier:student.studentNumber||'',group:register.className||'',status:student.status,note:student.note||'',recordedBy:register.recordedBy||tr('Système KCS','KCS System'),period:register.period||'',arrival:'',departure:''}))),
    ...staffRecords.map((record:any)=>({key:'staff-'+record.id,kind:'staff' as const,date:String(record.date).slice(0,10),name:record.staffName,identifier:record.employeeNumber||record.staffEmail||'',group:record.department||'',status:record.status,note:record.note||'',recordedBy:record.recordedBy||tr('Système KCS','KCS System'),period:'',arrival:record.arrivalTime||'',departure:record.departureTime||''}))
  ],[registers,staffRecords,isFr])
  const filtered=useMemo(()=>{const terms=normalized(query).split(/\s+/).filter(Boolean);return rows.filter(row=>(kind==='all'||row.kind===kind)&&(!status||row.status===status)&&(!recorder||normalized(row.recordedBy).includes(normalized(recorder)))&&(!group||normalized(row.group).includes(normalized(group)))&&terms.every(term=>normalized(Object.values(row).join(' ')).includes(term)))},[rows,query,kind,status,recorder,group])
  const clear=()=>{setQuery('');setKind('all');setStatus('');setRecorder('');setGroup('')}
  const filters=[query,kind!=='all'?kind:'',status,recorder,group].filter(Boolean).length
  return <section className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm dark:border-kcs-blue-800 dark:bg-kcs-blue-900/50">
    <div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex items-center gap-2"><History className="text-kcs-blue-600"/><h2 className="text-xl font-black text-kcs-blue-950 dark:text-white">{tr("Historique officiel des présences","Official attendance history")}</h2></div><p className="mt-1 text-sm text-gray-500">{tr("Consultez les présences passées du personnel et tous les rapports soumis par les enseignants.","Review past staff attendance and every report submitted by teachers.")}</p></div><div className="grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><input type="date" value={from} max={to} onChange={e=>setFrom(e.target.value)} className={field}/><input type="date" value={to} min={from} max={today} onChange={e=>setTo(e.target.value)} className={field}/><button type="button" disabled={loading} onClick={()=>void load()} className="inline-flex items-center justify-center gap-2 rounded-xl bg-kcs-blue-700 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50"><RefreshCw size={16} className={loading?'animate-spin':''}/>{tr("Charger","Load")}</button></div></div>
    {notice&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700 dark:bg-red-950/30 dark:text-red-200">{notice}</p>}
    <div className="mt-5 rounded-2xl border border-sky-200 bg-sky-50/70 p-4 dark:border-kcs-blue-700 dark:bg-kcs-blue-950/60"><div className="flex flex-wrap items-center justify-between gap-2"><p className="flex items-center gap-2 text-sm font-black text-kcs-blue-900 dark:text-white"><SlidersHorizontal size={17}/>{tr("Recherche minutieuse multicritère","Detailed multi-criteria search")} {filters>0&&<span className="rounded-full bg-sky-200 px-2 py-0.5 text-xs">{filters}</span>}</p>{filters>0&&<button type="button" onClick={clear} className="inline-flex items-center gap-1 text-xs font-bold text-red-600"><X size={14}/>{tr("Effacer les filtres","Clear filters")}</button>}</div><label className="relative mt-3 block"><Search className="pointer-events-none absolute left-3 top-3 text-gray-400" size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} className={field+' pl-10'} placeholder={tr("Nom, matricule, date, note, classe, département, enseignant…","Name, ID, date, note, class, department, teacher…")}/></label><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><select value={kind} onChange={e=>setKind(e.target.value)} className={field}><option value="all">{tr("Élèves et personnel","Students and staff")}</option><option value="student">{tr("Rapports élèves","Student reports")}</option><option value="staff">{tr("Présences personnel","Staff attendance")}</option></select><select value={status} onChange={e=>setStatus(e.target.value)} className={field}><option value="">{tr("Tous les statuts","All statuses")}</option>{statuses.map(item=><option key={item} value={item}>{isFr?frLabels[item]:item.charAt(0)+item.slice(1).toLowerCase()}</option>)}</select><input value={recorder} onChange={e=>setRecorder(e.target.value)} className={field} placeholder={tr("Enregistré par / enseignant","Recorded by / teacher")}/><input value={group} onChange={e=>setGroup(e.target.value)} className={field} placeholder={tr("Classe ou département","Class or department")}/></div></div>
    <p className="mt-3 text-xs font-semibold text-gray-500">{filtered.length} {tr("résultat(s) sur","result(s) out of")} {rows.length} · {from} → {to}</p>
    <div className="mt-3 overflow-x-auto rounded-xl border dark:border-kcs-blue-800"><table className="w-full min-w-[1050px] text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-gray-500 dark:bg-kcs-blue-950"><tr><th className="p-3">{tr("Date","Date")}</th><th>{tr("Type","Type")}</th><th>{tr("Personne","Person")}</th><th>{tr("Matricule","ID")}</th><th>{tr("Classe / département","Class / department")}</th><th>{tr("Statut","Status")}</th><th>{tr("Enregistré par","Recorded by")}</th><th>{tr("Heures / note","Times / note")}</th></tr></thead><tbody>{filtered.map(row=><tr key={row.key} className="border-t align-top dark:border-kcs-blue-800"><td className="p-3 font-semibold">{row.date}</td><td>{row.kind==='student'?tr('Élève','Student'):tr('Personnel','Staff')}</td><td className="font-bold dark:text-white">{row.name}</td><td>{row.identifier||'—'}</td><td>{row.group||'—'}</td><td><span className="rounded-full bg-sky-50 px-2 py-1 font-bold text-kcs-blue-800 dark:bg-kcs-blue-800 dark:text-white">{isFr?frLabels[row.status]??row.status:row.status}</span></td><td>{row.recordedBy}</td><td>{[row.arrival&&tr('Arrivée ','Arrival ')+row.arrival,row.departure&&tr('Départ ','Departure ')+row.departure,row.note].filter(Boolean).join(' · ')||'—'}</td></tr>)}</tbody></table>{!loading&&!filtered.length&&<p className="p-6 text-center text-sm text-gray-500">{tr("Aucun ancien rapport ne correspond à ces critères.","No past report matches these criteria.")}</p>}</div>
  </section>
}
