import { useEffect, useMemo, useState } from 'react'
import { CheckCircle2, ClipboardCheck, RefreshCw, Save } from 'lucide-react'
import { attendanceAPI, registryAPI } from '@/services/api'

type Status='PRESENT'|'ABSENT'|'LATE'|'EXCUSED'|'SICK'|'SUSPENDED'
const statuses:Status[]=['PRESENT','ABSENT','LATE','EXCUSED','SICK','SUSPENDED']
const labels:Record<Status,string>={PRESENT:'Présent',ABSENT:'Absent',LATE:'Retard',EXCUSED:'Excusé',SICK:'Malade',SUSPENDED:'Suspendu'}
const panel='rounded-2xl border border-gray-100 bg-white p-5 shadow-sm dark:border-kcs-blue-800 dark:bg-kcs-blue-900/50'
const field='w-full rounded-xl border border-gray-200 bg-white px-3 py-2.5 text-sm dark:border-kcs-blue-700 dark:bg-kcs-blue-950 dark:text-white'
const button='inline-flex items-center justify-center gap-2 rounded-xl bg-kcs-blue-700 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50'

export default function AttendanceManagementPanel(){
 const [tab,setTab]=useState<'students'|'staff'>('students'),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[classes,setClasses]=useState<any[]>([]),[classKey,setClassKey]=useState(''),[staff,setStaff]=useState<any[]>([])
 const [states,setStates]=useState<Record<string,Status>>({}),[notes,setNotes]=useState<Record<string,string>>({}),[times,setTimes]=useState<Record<string,string>>({}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[notice,setNotice]=useState('')
 const selectedClass=classes.find(item=>`${item.grade}::${item.section}`===classKey)??classes[0]
 const load=async()=>{setLoading(true);setNotice('');try{const [studentsResponse,staffResponse,directoryResponse]=await Promise.all([attendanceAPI.students(date),attendanceAPI.staff(date),registryAPI.getDirectory()]);const nextClasses=studentsResponse.data.data?.classes??[];const records=staffResponse.data.data?.records??[];const people=directoryResponse.data.data?.teachers??[];setClasses(nextClasses);setClassKey(current=>nextClasses.some((item:any)=>`${item.grade}::${item.section}`===current)?current:(nextClasses[0]?`${nextClasses[0].grade}::${nextClasses[0].section}`:''));setStaff(people);setStates(Object.fromEntries([...nextClasses.flatMap((item:any)=>item.students.map((student:any)=>[student.id,student.status??'PRESENT'])),...people.map((person:any)=>[person.id,records.find((record:any)=>record.staffOrbitId===person.id)?.status??'PRESENT'])]));setNotes(Object.fromEntries([...nextClasses.flatMap((item:any)=>item.students.map((student:any)=>[student.id,student.note??''])),...people.map((person:any)=>[person.id,records.find((record:any)=>record.staffOrbitId===person.id)?.note??''])]));setTimes(Object.fromEntries(people.map((person:any)=>[person.id,records.find((record:any)=>record.staffOrbitId===person.id)?.arrivalTime??''])))}catch(error:any){setNotice(error?.response?.data?.message??'Le registre officiel ne peut pas être chargé.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[date])
 const save=async()=>{setSaving(true);setNotice('');try{if(tab==='students'){if(!selectedClass?.students?.length)return;await attendanceAPI.saveStudents({grade:selectedClass.grade,section:selectedClass.section,date,period:'Daily',entries:selectedClass.students.map((student:any)=>({studentId:student.id,status:states[student.id]??'PRESENT',note:notes[student.id]||undefined}))});setNotice(`Présence enregistrée pour ${selectedClass.students.length} élève(s).`)}else{if(!staff.length)return;await attendanceAPI.saveStaff({date,entries:staff.map((person:any)=>({staffOrbitId:person.id,employeeNumber:person.employeeId||undefined,staffName:person.fullName||[person.lastName,person.middleName,person.firstName].filter(Boolean).join(' '),staffEmail:person.email||undefined,department:person.department||undefined,status:states[person.id]??'PRESENT',arrivalTime:times[person.id]||undefined,note:notes[person.id]||undefined}))});setNotice(`Présence enregistrée pour ${staff.length} membre(s) du personnel.`)}await load()}catch(error:any){setNotice(error?.response?.data?.message??'Impossible d’enregistrer la présence.')}finally{setSaving(false)}}
 const rows=tab==='students'?(selectedClass?.students??[]):staff
 const summary=useMemo(()=>statuses.map(status=>({status,count:rows.filter((row:any)=>(states[row.id]??'PRESENT')===status).length})),[rows,states])
 return <div className="space-y-5">
  <section className={panel}><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-2"><ClipboardCheck className="text-kcs-blue-600"/><h2 className="text-xl font-bold text-kcs-blue-900 dark:text-white">Registre officiel des présences</h2></div><p className="mt-2 text-sm text-gray-500">Élèves et personnel, enregistrés dans l’écosystème et répercutés dans leurs dossiers.</p></div><div className="flex flex-wrap gap-2"><button className={button} onClick={()=>void load()}><RefreshCw size={16}/>Actualiser</button><button className={button} disabled={saving||rows.length===0} onClick={()=>void save()}><Save size={16}/>{saving?'Enregistrement…':'Enregistrer'}</button></div></div></section>
  {notice&&<p className="rounded-xl bg-kcs-blue-50 p-4 text-sm font-semibold text-kcs-blue-800 dark:bg-kcs-blue-900 dark:text-white">{notice}</p>}
  <section className={panel}><div className="grid gap-3 md:grid-cols-[220px_1fr_auto]"><input type="date" className={field} value={date} onChange={event=>setDate(event.target.value)}/><div className="flex rounded-xl bg-gray-100 p-1 dark:bg-kcs-blue-950">{(['students','staff'] as const).map(value=><button key={value} onClick={()=>setTab(value)} className={`flex-1 rounded-lg px-4 py-2 text-sm font-bold ${tab===value?'bg-white text-kcs-blue-800 shadow dark:bg-kcs-blue-800 dark:text-white':'text-gray-500'}`}>{value==='students'?'Élèves':'Personnel'}</button>)}</div>{tab==='students'&&<select className={field} value={selectedClass?`${selectedClass.grade}::${selectedClass.section}`:''} onChange={event=>setClassKey(event.target.value)}>{classes.map((item:any)=><option key={`${item.grade}::${item.section}`} value={`${item.grade}::${item.section}`}>{item.grade} {item.section} · {item.students.length} élèves</option>)}</select>}</div>
   <div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-3 xl:grid-cols-6">{summary.map(item=><div key={item.status} className="rounded-xl bg-sky-50 p-3 text-center dark:bg-kcs-blue-800/30"><b className="block text-xl dark:text-white">{item.count}</b><span className="text-xs text-gray-500">{labels[item.status]}</span></div>)}</div>
   <button className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-green-700" onClick={()=>setStates(current=>({...current,...Object.fromEntries(rows.map((row:any)=>[row.id,'PRESENT']))}))}><CheckCircle2 size={17}/>Tout marquer présent</button>
  </section>
  <section className={panel}>{loading?<p className="text-sm text-gray-500">Chargement du registre…</p>:rows.length===0?<p className="text-sm text-gray-500">Aucune personne dans ce registre.</p>:<div className="overflow-x-auto"><table className="min-w-[850px] w-full text-sm"><thead><tr className="border-b text-left text-xs uppercase text-gray-400"><th className="pb-3">Personne</th><th>Identifiant / fonction</th><th>Statut</th>{tab==='staff'&&<th>Arrivée</th>}<th>Note</th></tr></thead><tbody>{rows.map((row:any)=><tr key={row.id} className="border-b dark:border-kcs-blue-800"><td className="py-3 font-semibold dark:text-white">{row.name||row.fullName}</td><td>{row.studentNumber||row.employeeId||row.jobTitle||'—'}</td><td><select className={field} value={states[row.id]??'PRESENT'} onChange={event=>setStates(current=>({...current,[row.id]:event.target.value as Status}))}>{statuses.map(status=><option key={status} value={status}>{labels[status]}</option>)}</select></td>{tab==='staff'&&<td><input type="time" className={field} value={times[row.id]??''} onChange={event=>setTimes(current=>({...current,[row.id]:event.target.value}))}/></td>}<td><input className={field} value={notes[row.id]??''} onChange={event=>setNotes(current=>({...current,[row.id]:event.target.value}))} placeholder="Note vérifiée"/></td></tr>)}</tbody></table></div>}</section>
 </div>
}
