# Generated by Django 4.2.13 on 2026-05-06 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('T1', 'Term 1'), ('T2', 'Term 2'), ('T3', 'Term 3')], max_length=5, verbose_name='Term')),
                ('grade_type', models.CharField(choices=[('exam', 'Exam'), ('quiz', 'Quiz'), ('assignment', 'Assignment'), ('project', 'Project'), ('participation', 'Participation')], max_length=20, verbose_name='Type')),
                ('score', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Score')),
                ('max_score', models.DecimalField(decimal_places=2, default=20.0, max_digits=6, verbose_name='Max Score')),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='Weight')),
                ('date', models.DateField(verbose_name='Date')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='classes.academicyear', verbose_name='Academic Year')),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='classes.classsubject', verbose_name='Class / Subject')),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_grades', to=settings.AUTH_USER_MODEL, verbose_name='Entered By')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'db_table': 'grades',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('T1', 'Term 1'), ('T2', 'Term 2'), ('T3', 'Term 3')], max_length=5, verbose_name='Term')),
                ('overall_average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Overall Average')),
                ('rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='Rank')),
                ('teacher_comment', models.TextField(blank=True, verbose_name='Teacher Comment')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(default=dict, verbose_name='Report Data')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='classes.academicyear', verbose_name='Academic Year')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='students.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Report Card',
                'verbose_name_plural': 'Report Cards',
                'db_table': 'report_cards',
                'unique_together': {('student', 'academic_year', 'term')},
            },
        ),
    ]
