import DateSelect from '../../components/common/DateSelect';
import React, { useMemo, useState } from 'react';
import { ArrowLeft, Edit3, Save, UserRound, X } from 'lucide-react';
import { Link, useLocation, useNavigate, useParams } from 'react-router-dom';
import DashboardLayout from '../../components/layout/DashboardLayout';
import { parentsService, studentsService } from '../../services/api';

const fieldSets = {
  student: [['ID élève','student_id'],['Nom complet','full_name'],['Email','email'],['Classe','class_name'],['Date de naissance','date_of_birth'],['Genre','gender'],['Parent responsable','parent_name'],['Téléphone parent','parent_phone'],['Email parent','parent_email'],['Carte KCS','kcs_card_id'],['Statut','is_active']],
  parent: [['ID parent','parent_external_id'],['Famille / parent','family_name'],['Email','email'],['Téléphone','phone'],['Adresse physique','address'],['Élèves liés','students_label'],['Classes','classes_label'],['Effectif','student_count'],['Carte KCS','kcs_card_id']],
};
const levels=['K3','K4','K5',...Array.from({length:12},(_,i)=>`Grade ${i+1}`)];
const suffixes=['',...Array.from({length:26},(_,i)=>String.fromCharCode(65+i))];
const valueOf=(value)=>value===true?'Actif':value===false?'Inactif':value||'Non renseigné';
const splitName=(value='')=>{const p=value.trim().split(/\s+/).filter(Boolean);return {lastName:p[0]||'',middleName:p.slice(1,-1).join(' '),firstName:p.length>1?p[p.length-1]:''};};
const splitClass=(value='')=>{const match=value.match(/^(K[3-5]|Grade\s+\d+)(?:\s+([A-Z]))?$/i);return {classLevel:match?.[1]||'',classSuffix:match?.[2]||''};};

const EntityWorkspacePage=({type,mode})=>{
  const {id}=useParams(); const location=useLocation(); const navigate=useNavigate();
  const storageKey=`savanex:${type}:${id}`;
  const entity=useMemo(()=>{if(location.state?.entity){sessionStorage.setItem(storageKey,JSON.stringify(location.state.entity));return location.state.entity;}try{return JSON.parse(sessionStorage.getItem(storageKey)||'null');}catch{return null;}},[location.state,storageKey]);
  const isEdit=mode==='edit'; const listPath=type==='student'?'/students':'/parents';
  const initial=useMemo(()=>type==='student'?{...splitName(entity?.full_name),email:entity?.email||'',...splitClass(entity?.class_name),dateOfBirth:entity?.date_of_birth||'',gender:entity?.gender||'F',notes:entity?.notes||''}:{last_name:entity?.last_name||'',middle_name:entity?.middle_name||'',first_name:entity?.first_name||'',email:entity?.email||'',phone:entity?.phone||'',address:entity?.address||''},[entity,type]);
  const [form,setForm]=useState(initial); const [saving,setSaving]=useState(false); const [error,setError]=useState('');
  const set=(key)=>(event)=>setForm(current=>({...current,[key]:event.target.value}));
  const save=async(event)=>{event.preventDefault();setSaving(true);setError('');try{if(type==='student'){await studentsService.update(entity.id,{first_name:form.firstName,middle_name:form.middleName,last_name:form.lastName,user_email:form.email,class_level:form.classLevel,class_suffix:form.classSuffix,date_of_birth:form.dateOfBirth||undefined,gender:form.gender,notes:form.notes});}else{if(!entity.management_id)throw new Error('Ce parent ne peut pas être modifié depuis Savanex.');await parentsService.update(entity.management_id,form,{source:entity.management_source,identifierType:entity.identifier_type});}sessionStorage.removeItem(storageKey);navigate(listPath,{replace:true});}catch(err){setError(err?.response?.data?.detail||err?.message||'Enregistrement impossible.');}finally{setSaving(false);}};
  if(!entity)return <DashboardLayout><div className="mx-auto max-w-4xl card p-10 text-center"><h2 className="text-2xl font-bold text-slate-100">Fiche indisponible</h2><p className="mt-3 text-slate-400">Retournez à la liste et sélectionnez de nouveau cette entité.</p><Link to={listPath} className="mt-6 inline-flex rounded-xl bg-kcs-blue px-5 py-3 font-bold text-slate-950">Retour à la liste</Link></div></DashboardLayout>;
  return <DashboardLayout><div className="savanex-dedicated-page mx-auto w-full max-w-[1500px] space-y-6">
    <header className="card flex flex-col gap-5 p-6 sm:flex-row sm:items-center sm:justify-between lg:p-8"><div className="flex items-start gap-4"><span className="rounded-2xl border border-cyan-300/25 bg-cyan-300/10 p-3 text-cyan-200">{isEdit?<Edit3/>:<UserRound/>}</span><div><p className="text-xs font-bold uppercase tracking-[.22em] text-cyan-300">{isEdit?'Modification':'Consultation'} · {type==='student'?'Élève':'Parent'}</p><h2 className="mt-2 font-display text-3xl font-bold text-slate-50">{entity.full_name||entity.family_name||entity.student_id}</h2><p className="mt-2 text-sm text-slate-400">{isEdit?'Modifiez les informations autorisées puis enregistrez.':'Fiche administrative complète dans un espace dédié.'}</p></div></div><div className="flex flex-wrap gap-3"><Link to={listPath} className="inline-flex items-center gap-2 rounded-xl border border-github-border px-4 py-3 text-sm font-bold text-slate-200 hover:bg-slate-800"><ArrowLeft size={17}/>Retour</Link>{!isEdit&&<Link to={`${location.pathname}/edit`} state={{entity}} className="inline-flex items-center gap-2 rounded-xl bg-amber-300 px-5 py-3 text-sm font-bold text-slate-950"><Edit3 size={17}/>Modifier</Link>}</div></header>
    {!isEdit?<section className="card p-6 lg:p-8"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{fieldSets[type].map(([label,key])=><article key={key} className="min-h-28 rounded-2xl border border-cyan-200/15 bg-slate-950/45 p-5"><p className="text-xs font-bold uppercase tracking-[.16em] text-slate-500">{label}</p><p className="mt-3 break-words text-base font-semibold text-slate-100">{valueOf(entity[key])}</p></article>)}</div></section>:
    <form onSubmit={save} className="card space-y-6 p-6 lg:p-8">{error&&<p className="rounded-xl border border-rose-400/30 bg-rose-400/10 p-4 text-rose-200">{error}</p>}
      <section className="rounded-2xl border border-cyan-200/15 bg-slate-950/35 p-5"><h3 className="font-display text-xl font-bold text-slate-100">Identité et coordonnées</h3><div className="mt-5 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{type==='student'?<><Field label="Nom" value={form.lastName} onChange={set('lastName')}/><Field label="Postnom" value={form.middleName} onChange={set('middleName')}/><Field label="Prénom" value={form.firstName} onChange={set('firstName')}/><Field label="Email" type="email" value={form.email} onChange={set('email')}/><label className="block text-sm font-bold text-slate-300">Date de naissance<DateSelect value={form.dateOfBirth} onChange={set('dateOfBirth')} className="mt-2 min-h-12 w-full rounded-xl border border-github-border bg-slate-950/70 px-4 py-3 text-slate-100" /></label></>:<><Field label="Nom" value={form.last_name} onChange={set('last_name')}/><Field label="Postnom" value={form.middle_name} onChange={set('middle_name')}/><Field label="Prénom" value={form.first_name} onChange={set('first_name')}/><Field label="Email" type="email" value={form.email} onChange={set('email')}/><Field label="Téléphone" value={form.phone} onChange={set('phone')}/><Field label="Adresse physique" value={form.address} onChange={set('address')}/></>}</div></section>
      {type==='student'&&<section className="rounded-2xl border border-emerald-200/15 bg-slate-950/35 p-5"><h3 className="font-display text-xl font-bold text-slate-100">Classe et profil</h3><div className="mt-5 grid gap-5 md:grid-cols-3"><Select label="Niveau" value={form.classLevel} onChange={set('classLevel')} options={levels}/><Select label="Suffixe" value={form.classSuffix} onChange={set('classSuffix')} options={suffixes}/><Select label="Genre" value={form.gender} onChange={set('gender')} options={['F','M','O']}/></div><label className="mt-5 block text-sm font-bold text-slate-300">Notes administratives<textarea value={form.notes} onChange={set('notes')} className="mt-2 min-h-32 w-full rounded-xl border border-github-border bg-slate-950/70 p-4 text-slate-100 outline-none focus:border-cyan-300"/></label></section>}
      <footer className="flex flex-wrap justify-end gap-3 border-t border-github-border pt-6"><Link to={listPath} className="inline-flex items-center gap-2 rounded-xl border-2 border-amber-300 bg-amber-100 px-5 py-3 font-black text-amber-950"><X size={17}/>Annuler</Link><button disabled={saving} className="inline-flex items-center gap-2 rounded-xl border-2 border-emerald-200 bg-emerald-300 px-6 py-3 font-black text-slate-950 shadow-xl shadow-emerald-400/30 hover:bg-emerald-200 disabled:opacity-50"><Save size={17}/>{saving?'Enregistrement...':'Enregistrer les modifications'}</button></footer>
    </form>}
  </div></DashboardLayout>;
};
const Field=({label,...props})=><label className="block text-sm font-bold text-slate-300">{label}<input {...props} className="mt-2 min-h-12 w-full rounded-xl border border-github-border bg-slate-950/70 px-4 py-3 text-slate-100 outline-none focus:border-cyan-300 focus:ring-2 focus:ring-cyan-300/15"/></label>;
const Select=({label,options,...props})=><label className="block text-sm font-bold text-slate-300">{label}<select {...props} className="mt-2 min-h-12 w-full rounded-xl border border-github-border bg-slate-950/70 px-4 py-3 text-slate-100 outline-none focus:border-cyan-300">{options.map(option=><option key={option||'none'} value={option}>{option||'Sans suffixe'}</option>)}</select></label>;
export default EntityWorkspacePage;
