const fr: Record<string, string> = {
  "Dashboard":"Tableau de bord","Curriculum":"Programme scolaire","Search":"Rechercher","Install App":"Installer l'application","New Lesson Plan":"Nouveau plan de leçon",
  "Toggle language":"Changer de langue","Toggle theme":"Changer de thème","Switch to French":"Passer en français","Switch to light theme":"Passer au thème clair","Switch to dark theme":"Passer au thème sombre",
  "Account security":"Sécurité du compte","Account Security":"Sécurité du compte","Logout":"Se déconnecter","KCS Lesson Planner":"Planificateur de leçons KCS","A4 print-ready":"Prêt pour l'impression A4",
  "Profile Photo":"Photo de profil","Choose photo":"Choisir une photo","Remove photo":"Supprimer la photo","Change Password":"Modifier le mot de passe","Change Email":"Modifier l'adresse e-mail",
  "Current password":"Mot de passe actuel","New password":"Nouveau mot de passe","Confirm password":"Confirmer le mot de passe","New email":"Nouvelle adresse e-mail","Show password":"Afficher le mot de passe","Hide password":"Masquer le mot de passe",
  "Save":"Enregistrer","Cancel":"Annuler","Close":"Fermer","Password updated":"Mot de passe mis à jour","Password updated successfully.":"Mot de passe mis à jour avec succès.",
  "The new password confirmation does not match.":"La confirmation du nouveau mot de passe ne correspond pas.","Unable to update password.":"Impossible de mettre à jour le mot de passe.",
  "Email change requested. Please sign in again.":"Modification de l'adresse e-mail demandée. Veuillez vous reconnecter.","Unable to update email.":"Impossible de mettre à jour l'adresse e-mail.",
  "After changing email, you may need to confirm the new address depending on Supabase email settings. You will be signed out for security.":"Après la modification, vous devrez peut-être confirmer la nouvelle adresse selon les paramètres e-mail de Supabase. Vous serez déconnecté par sécurité.",
  "Access Portal":"Portail d'accès","Sign in":"Se connecter","Create account":"Créer un compte","Password":"Mot de passe","Email":"Adresse e-mail","Full name":"Nom complet","Loading secure session...":"Chargement de la session sécurisée...",
  "Select department":"Sélectionner un département","Recover":"Récupérer","Password Recovery Center":"Centre de récupération du mot de passe","Temporary password":"Mot de passe temporaire","Optional temporary password":"Mot de passe temporaire facultatif","Set temporary password":"Définir un mot de passe temporaire",
  "Account activated":"Compte activé","Account disabled":"Compte désactivé","Active":"Actif","Inactive":"Inactif","Active users":"Utilisateurs actifs","Inactive users":"Utilisateurs inactifs",
  "User Administration":"Administration des utilisateurs","Users & Roles":"Utilisateurs et rôles","Search users":"Rechercher des utilisateurs","Any role":"Tous les rôles","Any user status":"Tous les statuts utilisateur","Any department":"Tous les départements","Any course":"Tous les cours","Any class":"Toutes les classes","Any lesson activity":"Toute activité de leçon",
  "Has lesson plans":"Possède des plans de leçon","No lesson plans":"Aucun plan de leçon","Has drafts":"Possède des brouillons","Has submitted plans":"Possède des plans soumis","Under review":"En cours de révision","Approved/final/published":"Approuvé/final/publié","Rejected/revision requested":"Rejeté/révision demandée",
  "Clear filters":"Effacer les filtres","Department":"Département","Subjects":"Matières","Grade classes":"Classes et niveaux","Save profile":"Enregistrer le profil","Edit":"Modifier","Delete":"Supprimer","No users match this search.":"Aucun utilisateur ne correspond à cette recherche.",
  "Recent Activity":"Activité récente","Upcoming Teaching Schedule":"Programme d'enseignement à venir","Completion Progress":"Progression de l'achèvement","Quick Actions":"Actions rapides","Curriculum Progress":"Progression du programme","Review Activity":"Activité de révision","Teachers Pending Submission":"Enseignants en attente de soumission","Department Shortcuts":"Raccourcis du département","Department Performance":"Performance des départements","Approval Statistics":"Statistiques d'approbation","Teacher Activity":"Activité des enseignants","Inspection Readiness":"Préparation à l'inspection","Data Overview":"Aperçu des données","Administrator Authority":"Pouvoirs de l'administrateur","System Activity":"Activité du système","Configuration Shortcuts":"Raccourcis de configuration",
  "No activity yet.":"Aucune activité pour le moment.","No upcoming lessons scheduled.":"Aucune leçon à venir n'est planifiée.","No department data yet.":"Aucune donnée de département pour le moment.",
  "Lesson Plans":"Plans de leçon","Search, filter, review, archive, restore, duplicate, and back up your local library.":"Recherchez, filtrez, révisez, archivez, restaurez, dupliquez et sauvegardez votre bibliothèque locale.",
  "Keywords":"Mots-clés","Teacher":"Enseignant","Subject":"Matière","Grade":"Niveau","Exact Date":"Date exacte","From Date":"Date de début","To Date":"Date de fin","Term":"Trimestre","Any week":"Toute semaine","Any month":"Tout mois","Any year":"Toute année","Topic":"Sujet","Tags":"Étiquettes","All":"Tous","Deleted":"Supprimé","Duplicate":"Dupliquer","Submit":"Soumettre","Review":"Réviser","HOD Approve":"Approbation du chef de département","Request Revision":"Demander une révision","Reject":"Rejeter","Final Approve":"Approbation finale","Publish":"Publier","Archive":"Archiver","Unarchive":"Désarchiver","Restore":"Restaurer",
  "No plans match the current filters.":"Aucun plan ne correspond aux filtres actuels.","Optional teacher":"Enseignant facultatif","Optional subject":"Matière facultative","Optional grade":"Niveau facultatif","Lesson plan duplicated":"Plan de leçon dupliqué","Lesson plan restored":"Plan de leçon restauré","A reviewer comment is required":"Un commentaire du réviseur est requis",
  "Curriculum Manager":"Gestionnaire du programme scolaire","Academic Year":"Année scolaire","Any term":"Tout trimestre","Any grade":"Tout niveau","Any subject":"Toute matière","Unit":"Unité","Subtopic":"Sous-thème","Competencies":"Compétences","Learning Objectives":"Objectifs d'apprentissage","Learning Outcomes":"Résultats d'apprentissage","References":"Références","Skills":"Compétences pratiques","Curriculum Standards":"Normes du programme","Export JSON":"Exporter en JSON","New Item":"Nouvel élément","Open":"Ouvrir","Save Curriculum Item":"Enregistrer l'élément du programme","No curriculum items match the filters.":"Aucun élément du programme ne correspond aux filtres.","Curriculum item saved":"Élément du programme enregistré","Curriculum item deleted":"Élément du programme supprimé","Curriculum JSON imported":"Programme JSON importé",
  "Everyone":"Tout le monde","Role":"Rôle","User":"Utilisateur","Choose target":"Choisir le destinataire","Message":"Message","Send":"Envoyer","Search messages":"Rechercher des messages","Any sender":"Tout expéditeur","Any audience":"Tout public","Read and unread":"Lus et non lus","Unread only":"Non lus uniquement","Read only":"Lus uniquement","From":"Du","To":"Au","New":"Nouveau","Edit message":"Modifier le message","Delete message":"Supprimer le message","Select message":"Sélectionner le message","No messages match this search.":"Aucun message ne correspond à cette recherche.","Message sent":"Message envoyé","Message updated":"Message mis à jour","Message deleted":"Message supprimé","Unable to load messages.":"Impossible de charger les messages.","Unable to send message.":"Impossible d'envoyer le message.","Unable to update message.":"Impossible de mettre à jour le message.","Unable to delete message.":"Impossible de supprimer le message.",
  "Access restricted":"Accès restreint","You do not have permission to view this lesson plan.":"Vous n'avez pas l'autorisation de consulter ce plan de leçon.","Switch to an authorized role or return to the visible lesson plan library.":"Passez à un rôle autorisé ou revenez à la bibliothèque de plans visible.","Back to plans":"Retour aux plans","Split daily":"Diviser en plans quotidiens","Build weekly":"Créer le plan hebdomadaire","Preview":"Aperçu","Daily Lesson Plan":"Plan de leçon quotidien","Weekly Lesson Plan":"Plan de leçon hebdomadaire","Chapter / Unit":"Chapitre / Unité","Date":"Date","Select week":"Sélectionner la semaine","Week Start Date":"Date de début de semaine","Week End Date":"Date de fin de semaine","Classroom":"Salle de classe","Number of Students":"Nombre d'élèves",
  "Curriculum suggestions":"Suggestions du programme","Apply first match":"Appliquer la première correspondance","Apply":"Appliquer","Objectives row":"Ligne des objectifs","Presentation row":"Ligne de présentation","Assessment row":"Ligne d'évaluation","Assessment":"Évaluation","Regenerate day":"Régénérer la journée","Lifecycle and history":"Cycle de vie et historique","Status, revision notes, and activity log.":"Statut, notes de révision et journal d'activité.","Revision note":"Note de révision","Explain what changed or what needs review...":"Expliquez ce qui a changé ou doit être révisé...","No activity logged yet.":"Aucune activité enregistrée pour le moment.","Print preview":"Aperçu avant impression","Scaled to fit the screen.":"Adapté à la taille de l'écran.","Print":"Imprimer","School":"École","Restore suggestion":"Restaurer la suggestion","Only the changing details are editable. KCS is already known.":"Seuls les détails variables sont modifiables. KCS est déjà renseigné.","Download failed":"Échec du téléchargement","Curriculum suggestions applied":"Suggestions du programme appliquées","Revision note added":"Note de révision ajoutée"
};

Object.assign(fr, {
  "% inspection ready":"% prêt pour l'inspection","- Continuation":"- Suite","- Standards:":"- Normes :","1. Essential setup":"1. Configuration essentielle","Academic Year - Term - Grade - Subject - Unit - Topic - Subtopic - Competencies - Objectives - Outcomes.":"Année scolaire - Trimestre - Niveau - Matière - Unité - Thème - Sous-thème - Compétences - Objectifs - Résultats.",
  "Confirm new password":"Confirmer le nouveau mot de passe","Lesson":"Leçon","Lesson Data":"Données de la leçon","Lesson Planner":"Planificateur de leçons","Competencies:":"Compétences :","Objectives:":"Objectifs :","Plans:":"Plans :","Exit Ticket (":"Billet de sortie (","Guided Practice (":"Pratique guidée (","Presentation (":"Présentation (","Solution:":"Solution :","Solution: adjust the activity minutes so the total matches the lesson duration.":"Solution : ajustez les minutes des activités afin que le total corresponde à la durée de la leçon.","Subtopic suggestion":"Suggestion de sous-thème","Topic suggestion":"Suggestion de thème","Suggestions for":"Suggestions pour","Temporary password generated for":"Mot de passe temporaire généré pour","Version 1.3":"Version 1.3",
  "account":"compte","approved":"approuvé","attention":"attention","awaiting review":"en attente de révision","daily":"quotidien","draft":"brouillon","lesson plan":"plan de leçon","message":"message","plan quality checks":"contrôles de qualité du plan","review":"révision","selected":"sélectionné","shown":"affiché","submitted":"soumis","user profile":"profil utilisateur","| Modified":"| Modifié","| Updated":"| Mis à jour","· Department:":"· Département :","and":"et","for":"pour","of":"sur","to improve":"à améliorer","total":"total","min in activities":"min d'activités","unit, topic, standard...":"unité, thème, norme...","topic, objective...":"thème, objectif...","subject, content, sender...":"objet, contenu, expéditeur...","comma tags":"étiquettes séparées par des virgules",
  "Account":"Compte","Account email":"E-mail du compte","Administration":"Administration","Administrator":"Administrateur","Vice Principal":"Directeur adjoint","Head of Department":"Chef de département","Principal":"Directeur","System Administrator":"Administrateur système",
  "Administrator Dashboard":"Tableau de bord administrateur","Principal Dashboard":"Tableau de bord du directeur","Vice Principal Dashboard":"Tableau de bord du directeur adjoint","Teacher Dashboard":"Tableau de bord enseignant","HOD Dashboard":"Tableau de bord du chef de département",
  "Role-based operational command center for lesson planning, review workflows, curriculum progress, and school readiness at":"Centre opérationnel par rôle pour la planification des leçons, les circuits de révision, la progression du programme et la préparation de l'école à",
  "Version 1.5 Enterprise Dashboard":"Version 1.5 - Tableau de bord d'entreprise","All Lesson Plans":"Tous les plans de leçon","Total Lesson Plans":"Total des plans de leçon","All Plans":"Tous les plans","Submitted Plans":"Plans soumis","Approved Plans":"Plans approuvés","Drafts":"Brouillons","Approval Queue":"File d'approbation","Approval Rate":"Taux d'approbation","Review Queue":"File de révision","Review All Plans":"Réviser tous les plans","Archive Review":"Révision des archives","Storage Overview":"Aperçu du stockage","Manage Plans":"Gérer les plans","Curriculum Data":"Données du programme","Curriculum Audit":"Audit du programme","Department Lesson Plans":"Plans de leçon du département","Term Progress":"Progression du trimestre","Performance":"Performance","Overview":"Aperçu","Security":"Sécurité","Users":"Utilisateurs","Roles":"Rôles",
  "View Drafts":"Voir les brouillons","View identities, correct profiles, activate access, send password recovery, or remove application profiles.":"Consultez les identités, corrigez les profils, activez les accès, envoyez les récupérations de mot de passe ou supprimez les profils de l'application.","Inspection readiness blends approval rate, curriculum coverage, and live submission progress.":"La préparation à l'inspection combine le taux d'approbation, la couverture du programme et la progression réelle des soumissions.",
  "Activate":"Activer","Disable":"Désactiver","Delete selected":"Supprimer la sélection","Delete Selected":"Supprimer la sélection","Restore Selected":"Restaurer la sélection","Clear selection":"Effacer la sélection","Show deleted":"Afficher les éléments supprimés","Select all visible deletable plans":"Sélectionner tous les plans visibles pouvant être supprimés","No records to show.":"Aucun enregistrement à afficher.","No authority profiles found.":"Aucun profil d'autorité trouvé.","No pending teacher submissions.":"Aucune soumission d'enseignant en attente.","No classes":"Aucune classe","No classes assigned":"Aucune classe attribuée","No subjects":"Aucune matière","No department":"Aucun département","Unassigned":"Non attribué","Unknown user":"Utilisateur inconnu",
  "Send recovery":"Envoyer la récupération","Sending recovery...":"Envoi de la récupération...","Copy password":"Copier le mot de passe","Copied":"Copié","Update Email":"Mettre à jour l'adresse e-mail","Update Password":"Mettre à jour le mot de passe","Updating...":"Mise à jour...","Updating password...":"Mise à jour du mot de passe...","Preparing...":"Préparation...","Requesting...":"Envoi de la demande...","Signing in...":"Connexion...","Creating account...":"Création du compte...","Set new password":"Définir le nouveau mot de passe","Recover password":"Récupérer le mot de passe",
  "Account created. A school authority must activate it before first login.":"Compte créé. Une autorité scolaire doit l'activer avant la première connexion.","Account creation started, but Supabase did not return a user id. Please check whether email confirmation is required, then try signing in after confirmation.":"La création du compte a commencé, mais Supabase n'a renvoyé aucun identifiant utilisateur. Vérifiez si la confirmation par e-mail est requise, puis reconnectez-vous après confirmation.","New accounts start inactive. An administrator, principal, or vice principal activates the profile before access. If online signup is temporarily limited, ask a school authority to create or activate the account.":"Les nouveaux comptes sont d'abord inactifs. Un administrateur, le directeur ou son adjoint active le profil. Si l'inscription en ligne est temporairement limitée, demandez à une autorité scolaire de créer ou d'activer le compte.",
  "Cloud mode active. Enter your account email and password to load your profile and lesson plans from Supabase.":"Mode cloud actif. Saisissez l'adresse e-mail et le mot de passe de votre compte pour charger votre profil et vos plans depuis Supabase.","This account is waiting for activation by the school authority.":"Ce compte attend son activation par l'autorité scolaire.","If this is urgent, ask an administrator, principal, or vice principal to create or activate the account from the authority portal.":"En cas d'urgence, demandez à un administrateur, au directeur ou à son adjoint de créer ou d'activer le compte depuis le portail d'autorité.","If this account exists, a branded KCS recovery email has been sent. Check the inbox and spam folder.":"Si ce compte existe, un e-mail KCS de récupération a été envoyé. Vérifiez la boîte de réception et les courriers indésirables.","If this account exists, a recovery email has been sent.":"Si ce compte existe, un e-mail de récupération a été envoyé.",
  "Temporary local access: demo password":"Accès local temporaire : mot de passe de démonstration","Temporary password activated. Sign in with the temporary password sent by the school authority, then change it from your profile.":"Mot de passe temporaire activé. Connectez-vous avec le mot de passe envoyé par l'autorité scolaire, puis modifiez-le depuis votre profil.","Password updated. You can sign in with your new password.":"Mot de passe mis à jour. Vous pouvez vous connecter avec votre nouveau mot de passe.","Pending activation:":"En attente d'activation :",
  "Incorrect email or password.":"Adresse e-mail ou mot de passe incorrect.","Invalid email or password":"Adresse e-mail ou mot de passe invalide","An account already exists for this email.":"Un compte existe déjà pour cette adresse e-mail.","No account found for this email.":"Aucun compte trouvé pour cette adresse e-mail.","Recovery link is missing or expired.":"Le lien de récupération est absent ou expiré.","Current password is incorrect.":"Le mot de passe actuel est incorrect.","Current user profile was not found.":"Le profil utilisateur actuel est introuvable.","Please sign in again before changing your email.":"Veuillez vous reconnecter avant de modifier votre adresse e-mail.","Please sign in again before changing your password.":"Veuillez vous reconnecter avant de modifier votre mot de passe.","Too many account requests were sent in a short time. Please wait a few minutes before trying again, or ask a school authority to create or activate the account.":"Trop de demandes de compte ont été envoyées en peu de temps. Attendez quelques minutes avant de réessayer ou demandez à une autorité scolaire de créer ou d'activer le compte.",
  "Unable to create this account.":"Impossible de créer ce compte.","Unable to process request":"Impossible de traiter la demande","Unable to start password recovery.":"Impossible de démarrer la récupération du mot de passe.","Unable to prepare password recovery.":"Impossible de préparer la récupération du mot de passe.","Unable to send the recovery email.":"Impossible d'envoyer l'e-mail de récupération.","Unable to update the password.":"Impossible de mettre à jour le mot de passe.","Unable to set the temporary password.":"Impossible de définir le mot de passe temporaire.","Unable to activate the temporary password.":"Impossible d'activer le mot de passe temporaire.","The recovery mail service is not configured.":"Le service d'e-mail de récupération n'est pas configuré.","Supabase could not send the recovery email. Ask an administrator to generate a temporary password from Dashboard > Security.":"Supabase n'a pas pu envoyer l'e-mail de récupération. Demandez à un administrateur de générer un mot de passe temporaire depuis Tableau de bord > Sécurité.",
  "Choose a user and generate a temporary password directly. This avoids blocked recovery emails.":"Choisissez un utilisateur et générez directement un mot de passe temporaire. Cela évite les e-mails de récupération bloqués.","Choose a user and set a temporary password for local fallback mode.":"Choisissez un utilisateur et définissez un mot de passe temporaire pour le mode local de secours.","The account is now inactive and cannot sign in until it is activated again.":"Le compte est maintenant inactif et ne pourra se connecter qu'après une nouvelle activation.","The user's existing account password was kept.":"Le mot de passe existant du compte a été conservé.","User profile activated. The user's existing account password was kept.":"Profil utilisateur activé. Le mot de passe existant du compte a été conservé.","User profile disabled.":"Profil utilisateur désactivé.","User profile deleted.":"Profil utilisateur supprimé.","User profile updated.":"Profil utilisateur mis à jour.","User profile not found.":"Profil utilisateur introuvable.","Keep at least one active administrator, principal, or vice-principal profile.":"Conservez au moins un profil actif d'administrateur, de directeur ou de directeur adjoint.","You cannot delete your own active administrator profile.":"Vous ne pouvez pas supprimer votre propre profil administrateur actif.",
  "Draft":"Brouillon","Submitted":"Soumis","In Review":"En révision","Under Review":"En cours de révision","Approved":"Approuvé","Final Approved":"Approbation finale","Published":"Publié","Archived":"Archivé","Rejected":"Rejeté","Revision Requested":"Révision demandée","Rejected / Revision":"Rejeté / Révision","Submitted for Review":"Soumis pour révision","Approved by HOD":"Approuvé par le chef de département","Rejected by reviewer":"Rejeté par le réviseur","Returned for correction":"Retourné pour correction","Final approval granted":"Approbation finale accordée","Review started":"Révision commencée","Submitted by":"Soumis par","Owner:":"Propriétaire :","ID / Status":"Identifiant / Statut","Status":"Statut","Created":"Créé","Last update:":"Dernière mise à jour :","Modified":"Modifié","Updated":"Mis à jour",
  "Lesson Plan":"Plan de leçon","Lesson Plan Title":"Titre du plan de leçon","Plan Type":"Type de plan","Daily":"Quotidien","Weekly":"Hebdomadaire","Daily Lesson":"Leçon quotidienne","Weekly grid":"Grille hebdomadaire","Week":"Semaine","Month":"Mois","Year":"Année","Quarter":"Trimestre","Semester":"Semestre","School Year":"Année scolaire","Class":"Classe","Section":"Section","Duration":"Durée","Objectives":"Objectifs","Presentation":"Présentation","Introduction":"Introduction","Closure":"Conclusion","Homework":"Devoir","Reflection":"Réflexion","Collaborative Activity":"Activité collaborative","Independent Practice":"Pratique autonome","Guided Practice":"Pratique guidée","Exit Ticket":"Billet de sortie","Exit Ticket / Assessment":"Billet de sortie / Évaluation","Presentation / Guided Practice":"Présentation / Pratique guidée","School identity":"Identité de l'école","KCS identity":"Identité KCS","KCS logo":"Logo KCS","KCS stays fixed; the title, lesson details, and teaching content come from your fields.":"KCS reste fixe ; le titre, les détails de la leçon et le contenu pédagogique proviennent de vos champs.",
  "Generate week":"Générer la semaine","Generate day":"Générer la journée","Add note":"Ajouter une note","Lock":"Verrouiller","Unlock":"Déverrouiller","Show":"Afficher","Hide":"Masquer","Import JSON":"Importer le JSON","Delete this curriculum item?":"Supprimer cet élément du programme ?","Delete this message for everyone?":"Supprimer ce message pour tout le monde ?","Move this lesson plan to deleted items?":"Déplacer ce plan de leçon vers les éléments supprimés ?","Edit Curriculum Item":"Modifier l'élément du programme","New Curriculum Item":"Nouvel élément du programme","Manage the curriculum hierarchy used by lesson plans.":"Gérez la hiérarchie du programme utilisée par les plans de leçon.","Read-only curriculum view for lesson planning.":"Vue du programme en lecture seule pour la planification des leçons.",
  "Chapter is required":"Le chapitre est requis","Grade/Class is required":"Le niveau ou la classe est requis","Subject is required":"La matière est requise","Teacher is required":"L'enseignant est requis","Teacher is missing.":"L'enseignant est manquant.","Subject is missing.":"La matière est manquante.","Grade/Class is missing.":"Le niveau ou la classe est manquant.","Unit or chapter is missing.":"L'unité ou le chapitre est manquant.","Daily lesson date is missing.":"La date de la leçon quotidienne est manquante.","Weekly schedule is incomplete.":"Le programme hebdomadaire est incomplet.","This plan is read-only for your current role.":"Ce plan est en lecture seule pour votre rôle actuel.","Add the teacher name before submitting or printing the lesson plan.":"Ajoutez le nom de l'enseignant avant de soumettre ou d'imprimer le plan.","Choose the subject so the objectives, activities, and assessment match the curriculum.":"Choisissez la matière afin que les objectifs, activités et évaluations correspondent au programme.","Choose the grade or class to keep the level of work appropriate.":"Choisissez le niveau ou la classe afin d'adapter le travail.","Add the unit/chapter so the lesson has a clear curriculum anchor.":"Ajoutez l'unité ou le chapitre afin d'ancrer clairement la leçon dans le programme.","Select the lesson date so the daily plan is properly scheduled.":"Sélectionnez la date afin de planifier correctement la leçon quotidienne.","Add the week number, start date, and end date for a complete weekly plan.":"Ajoutez le numéro, la date de début et la date de fin pour compléter le plan hebdomadaire.",
  "Use Generate week first, then edit only the parts that need teacher judgement.":"Utilisez d'abord Générer la semaine, puis modifiez uniquement les parties nécessitant le jugement de l'enseignant.","Regenerate the row or edit repeated cells so each day shows real progression.":"Régénérez la ligne ou modifiez les cellules répétées afin que chaque journée montre une progression réelle.","Unlock this cell before regenerating it":"Déverrouillez cette cellule avant de la régénérer","Write the approval comment for the teacher:":"Rédigez le commentaire d'approbation destiné à l'enseignant :","Write the final approval comment for the teacher:":"Rédigez le commentaire d'approbation finale destiné à l'enseignant :","Explain corrections required for the teacher:":"Expliquez les corrections demandées à l'enseignant :","Explain why this lesson plan is rejected:":"Expliquez pourquoi ce plan de leçon est rejeté :","Optional review start comment:":"Commentaire facultatif de début de révision :","Optional submission note for the reviewer:":"Note facultative de soumission au réviseur :","No reviewer comment was written.":"Aucun commentaire du réviseur n'a été rédigé.",
  "Lesson plan created":"Plan de leçon créé","Lesson plan updated":"Plan de leçon mis à jour","Lesson plan saved":"Plan de leçon enregistré","Lesson plan approved":"Plan de leçon approuvé","Lesson plan published":"Plan de leçon publié","Lesson plan rejected":"Plan de leçon rejeté","Lesson plan archived":"Plan de leçon archivé","Lesson plan unarchived":"Plan de leçon désarchivé","Lesson plan moved to deleted items":"Plan de leçon déplacé vers les éléments supprimés","Lesson plan restored from deleted items":"Plan de leçon restauré depuis les éléments supprimés","Duplicated lesson plan":"Plan de leçon dupliqué","Daily lesson generated automatically":"Leçon quotidienne générée automatiquement","Week generated automatically":"Semaine générée automatiquement","JSON backup imported":"Sauvegarde JSON importée","Manual save with revision snapshot":"Enregistrement manuel avec instantané de révision","Autosaved lesson changes":"Modifications de la leçon enregistrées automatiquement",
  "PDF download in progress...":"Téléchargement du PDF en cours...","DOCX download in progress...":"Téléchargement du DOCX en cours...","PDF downloaded":"PDF téléchargé","DOCX downloaded":"DOCX téléchargé","Generated on":"Généré le","Teacher Signature / Date":"Signature de l'enseignant / Date","Principal Signature / Date":"Signature du directeur / Date","Scan to open the digital Lesson Plan":"Scannez pour ouvrir le plan de leçon numérique","Lesson plan QR code":"Code QR du plan de leçon","Page 1/":"Page 1/","Page 2/2 | Generated on":"Page 2/2 | Généré le",
  "Monday":"Lundi","Tuesday":"Mardi","Wednesday":"Mercredi","Thursday":"Jeudi","Friday":"Vendredi","Good morning":"Bonjour","Good afternoon":"Bon après-midi","Good evening":"Bonsoir","Good night":"Bonne nuit",
  "Use the browser installation icon or menu if the prompt is not available yet.":"Utilisez l'icône ou le menu d'installation du navigateur si la demande n'est pas encore disponible.","Use the installation icon in your browser address bar if the prompt is not available yet.":"Utilisez l'icône d'installation dans la barre d'adresse du navigateur si la demande n'est pas disponible.","KCS EduPlanner installed":"KCS EduPlanner installé","KCS EduPlanner is now installed.":"KCS EduPlanner est maintenant installé.","Profile photo updated":"Photo de profil mise à jour","Choose an image file.":"Choisissez un fichier image.","Unable to load image.":"Impossible de charger l'image.","Unable to prepare image.":"Impossible de préparer l'image.","Unable to read image.":"Impossible de lire l'image.","Unable to read this image.":"Impossible de lire cette image.","Unable to update profile photo.":"Impossible de mettre à jour la photo de profil.",
  "Delete message":"Supprimer le message","Selected messages deleted":"Messages sélectionnés supprimés","Select sent":"Sélection envoyée","Unable to mark message as read.":"Impossible de marquer le message comme lu.","Unable to delete selected messages.":"Impossible de supprimer les messages sélectionnés.","This message could not be deleted. It may have been deleted already or you may not be the sender.":"Ce message n'a pas pu être supprimé. Il a peut-être déjà été supprimé ou vous n'en êtes pas l'expéditeur.","This message could not be updated. It may have been deleted or you may not be the sender.":"Ce message n'a pas pu être mis à jour. Il a peut-être été supprimé ou vous n'en êtes pas l'expéditeur.","Audience":"Public","Audience:":"Public :","Sender":"Expéditeur","Target":"Destinataire","No activity yet":"Aucune activité pour le moment","No date":"Aucune date","None":"Aucun","Untitled Lesson":"Leçon sans titre"
});
const patterns: Array<[RegExp, (...values: string[]) => string]> = [
  [/^Week (\d+)$/, value => `Semaine ${value}`],
  [/^(\d+) lesson plans?$/, count => `${count} plan${count === "1" ? "" : "s"} de leçon`],
  [/^Status updated to (.+)$/, status => `Statut mis à jour : ${translateToFrench(status)}`],
  [/^Workflow updated: (.+)$/, status => `Flux de travail mis à jour : ${translateToFrench(status)}`],
  [/^Saved checkpoint (\d+)$/, value => `Point de contrôle ${value} enregistré`],
  [/^(\d+) daily lesson plans created$/, count => `${count} plans de leçon quotidiens créés`],
  [/^Select (.+)$/, value => `Sélectionner ${translateToFrench(value)}`],
  [/^(.+) Dashboard$/, role => `Tableau de bord ${translateToFrench(role).toLowerCase()}`],
  [/^(\d+) profiles?$/, count => `${count} profil${count === "1" ? "" : "s"}`],
  [/^Plans: (\d+) total$/, count => `Plans : ${count} au total`],
  [/^Temporary password generated for (.+)$/, name => `Mot de passe temporaire généré pour ${name}`],
  [/^Suggestions for (.+)$/, value => `Suggestions pour ${value}`],
  [/^(\d+)% inspection ready$/, value => `${value} % prêt pour l'inspection`],
  [/^(\d+) min in activities$/, value => `${value} min d'activités`],
  [/^Page 2\/2 \| Generated on (.+)$/, date => `Page 2/2 | Généré le ${date}`]
];

export const translateToFrench = (value: string): string => {
  if (fr[value]) return fr[value];
  for (const [pattern, replacement] of patterns) {
    const match = value.match(pattern);
    if (match) return replacement(...match.slice(1));
  }
  return value;
};
