import { schoolBranding } from "../config/branding";

type ReportRow = { student: string; className: string; parent: string; expected: number; paid: number; balance: number; status: string };
type ReportResponse = { answer?: string; facts?: string[]; actions?: string[]; confidence?: string; tableRows?: ReportRow[] };

const esc = (value: unknown) => String(value ?? "").replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" })[char] ?? char);
const money = (value: number, lang: "fr" | "en") => new Intl.NumberFormat(lang === "fr" ? "fr-FR" : "en-US", { style: "currency", currency: "USD" }).format(Number(value || 0));

export function printAssistantReport({ question, response, lang }: { question: string; response: ReportResponse; lang: "fr" | "en" }) {
  const L = (fr: string, en: string) => lang === "fr" ? fr : en;
  const generatedAt = new Date();
  const logo = esc(new URL(schoolBranding.logoSrc, window.location.href).toString());
  const facts = (response.facts ?? []).map((item) => `<li>${esc(item)}</li>`).join("");
  const actions = (response.actions ?? []).map((item, index) => `<li><b>${index + 1}.</b> ${esc(item)}</li>`).join("");
  const rows = (response.tableRows ?? []).map((row) => `<tr><td><b>${esc(row.student)}</b></td><td>${esc(row.className)}</td><td>${esc(row.parent)}</td><td class="num">${esc(money(row.expected, lang))}</td><td class="num">${esc(money(row.paid, lang))}</td><td class="num balance">${esc(money(row.balance, lang))}</td><td>${esc(row.status)}</td></tr>`).join("");
  const reportId = `AI-${generatedAt.toISOString().replace(/\D/g, "").slice(0, 14)}`;
  // Keep the WindowProxy so the report can be written before printing.
  // Passing "noopener" to window.open makes some browsers return null even when
  // the tab was opened successfully, which left users with an empty document.
  const popup = window.open("", "_blank");
  if (!popup) throw new Error(L("La fenêtre d’impression a été bloquée.", "The print window was blocked."));
  try {
    popup.opener = null;
  } catch {
    // Some browsers expose opener as read-only; the report can still be rendered.
  }
  popup.document.write(`<!doctype html><html lang="${lang}"><head><meta charset="utf-8"><title>${esc(L("Rapport de l’Assistant IA", "AI Assistant Report"))}</title><style>
  @page{size:A4;margin:14mm 13mm 16mm}*{box-sizing:border-box}body{margin:0;color:#102a43;font-family:Inter,Arial,sans-serif;font-size:11px;line-height:1.55}.watermark{position:fixed;inset:0;display:grid;place-items:center;pointer-events:none;z-index:-1}.watermark img{width:330px;height:330px;object-fit:contain;opacity:.055;filter:grayscale(100%)}header{display:flex;align-items:center;justify-content:space-between;border-bottom:3px solid ${schoolBranding.colors.primary};padding-bottom:12px;margin-bottom:16px}.brand{display:flex;align-items:center;gap:12px}.logo{width:64px;height:64px;object-fit:contain;border:1px solid #cbd5e1;border-radius:14px;padding:6px;background:#fff}.kicker{font-size:9px;font-weight:800;letter-spacing:.16em;text-transform:uppercase;color:#52708f}h1{font-size:22px;margin:2px 0;color:#0b2e59}.school{font-weight:700}.meta{text-align:right;color:#526779;font-size:9.5px}.badge{display:inline-block;margin-top:5px;border:1px solid #8fb7e8;border-radius:999px;padding:2px 8px;color:#0b2e59;font-weight:700}.question{padding:12px 14px;border-left:4px solid #1f4f8f;background:#f1f6fc;border-radius:4px;margin:0 0 16px}.label{font-size:9px;font-weight:800;letter-spacing:.14em;text-transform:uppercase;color:#52708f;margin-bottom:4px}h2{font-size:14px;color:#0b2e59;margin:16px 0 7px;border-bottom:1px solid #d8e3ef;padding-bottom:4px}.answer{font-size:12px;background:#fff;border:1px solid #d8e3ef;border-radius:8px;padding:12px}ul,ol{margin:6px 0 0;padding-left:20px}li{margin:4px 0;break-inside:avoid}table{width:100%;border-collapse:collapse;font-size:8.5px;margin-top:8px;table-layout:fixed}th{background:#0b2e59;color:#fff;text-align:left;padding:6px 5px}td{border:1px solid #cbd5e1;padding:5px;vertical-align:top;word-break:break-word}.num{text-align:right;white-space:nowrap}.balance{font-weight:800;color:#9a5b00}.confidence{margin-top:15px;padding:9px 11px;border:1px solid #f0d48a;background:#fffbeb;border-radius:7px;color:#72520d}.notice{margin-top:16px;font-size:9px;color:#64748b}footer{position:fixed;bottom:-11mm;left:0;right:0;border-top:1px solid #cbd5e1;padding-top:5px;display:flex;justify-content:space-between;color:#64748b;font-size:8px}.avoid{break-inside:avoid}@media print{body{-webkit-print-color-adjust:exact;print-color-adjust:exact}}
  </style></head><body><div class="watermark"><img src="${logo}" alt=""></div><header><div class="brand"><img class="logo" src="${logo}" alt="${esc(schoolBranding.schoolName)}"><div><div class="kicker">${esc(schoolBranding.appName)} · ${esc(L("Analyse financière intelligente", "Intelligent financial analysis"))}</div><h1>${esc(L("Rapport de l’Assistant IA", "AI Assistant Report"))}</h1><div class="school">${esc(schoolBranding.schoolName)}</div></div></div><div class="meta">${esc(L("Document administratif", "Administrative document"))}<br>${esc(generatedAt.toLocaleString(lang === "fr" ? "fr-FR" : "en-US"))}<br><span class="badge">${reportId}</span></div></header><section class="question"><div class="label">${esc(L("Question analysée", "Analyzed question"))}</div><div>${esc(question)}</div></section><section><h2>${esc(L("Diagnostic de l’Assistant IA", "AI Assistant Assessment"))}</h2><div class="answer">${esc(response.answer)}</div></section>${facts ? `<section><h2>${esc(L("Chiffres clés et constats", "Key figures and findings"))}</h2><ul>${facts}</ul></section>` : ""}${rows ? `<section><h2>${esc(L("Tableau financier détaillé", "Detailed financial table"))}</h2><table><thead><tr><th>${esc(L("Élève", "Student"))}</th><th>${esc(L("Classe", "Class"))}</th><th>${esc(L("Parent", "Parent"))}</th><th>${esc(L("Attendu", "Expected"))}</th><th>${esc(L("Payé", "Paid"))}</th><th>${esc(L("Solde", "Balance"))}</th><th>${esc(L("Statut", "Status"))}</th></tr></thead><tbody>${rows}</tbody></table></section>` : ""}${actions ? `<section class="avoid"><h2>${esc(L("Actions recommandées", "Recommended actions"))}</h2><ol>${actions}</ol></section>` : ""}${response.confidence ? `<div class="confidence">${esc(response.confidence)}</div>` : ""}<p class="notice">${esc(L("Ce rapport est généré à partir des données EduPay disponibles au moment de l’analyse. Toute décision financière doit être validée par le service Finance.", "This report is generated from EduPay data available at the time of analysis. Any financial decision must be validated by the Finance department."))}</p><footer><span>${esc(schoolBranding.schoolName)} · ${esc(schoolBranding.appName)}</span><span>${reportId} · ${esc(L("Document confidentiel", "Confidential document"))}</span></footer><script>window.addEventListener("load",()=>setTimeout(()=>window.print(),350));<\/script></body></html>`);
  popup.document.close();
}
