"""
Users app — Custom user model with role-based access control.
"""
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _
from uuid import uuid4


def generate_kcs_card_id():
    return f"KCS-{uuid4().hex[:12].upper()}"


def generate_access_code():
    return f"ACC-{uuid4().hex[:10].upper()}"


class User(AbstractUser):
    """
    Extended user model supporting Admin, Employee, Teacher, Student, and Parent roles.
    """
    ROLE_ADMIN = 'admin'
    ROLE_EMPLOYEE = 'employee'
    ROLE_TEACHER = 'teacher'
    ROLE_STUDENT = 'student'
    ROLE_PARENT = 'parent'

    ROLE_CHOICES = [
        (ROLE_ADMIN, _('Admin')),
        (ROLE_EMPLOYEE, _('Employee')),
        (ROLE_TEACHER, _('Teacher')),
        (ROLE_STUDENT, _('Student')),
        (ROLE_PARENT, _('Parent')),
    ]

    LANGUAGE_CHOICES = [
        ('en', 'English'),
        ('fr', 'Français'),
    ]

    role = models.CharField(
        max_length=20,
        choices=ROLE_CHOICES,
        default=ROLE_STUDENT,
        verbose_name=_('Role'),
    )
    phone = models.CharField(max_length=20, blank=True, verbose_name=_('Phone'))
    avatar = models.ImageField(
        upload_to='avatars/',
        blank=True,
        null=True,
        verbose_name=_('Avatar'),
    )
    photo_data = models.TextField(blank=True, verbose_name=_('Photo Data'))
    photo_source = models.CharField(
        max_length=20,
        blank=True,
        choices=[('upload', _('Upload')), ('camera', _('Camera'))],
        verbose_name=_('Photo Source'),
    )
    left_fingerprint_data = models.TextField(blank=True, verbose_name=_('Left Fingerprint Data'))
    right_fingerprint_data = models.TextField(blank=True, verbose_name=_('Right Fingerprint Data'))
    kcs_card_id = models.CharField(
        max_length=24,
        unique=True,
        default=generate_kcs_card_id,
        verbose_name=_('KCS Card ID'),
    )
    access_code = models.CharField(
        max_length=24,
        unique=True,
        default=generate_access_code,
        verbose_name=_('Access Code'),
    )
    language = models.CharField(
        max_length=5,
        choices=LANGUAGE_CHOICES,
        default='en',
        verbose_name=_('Preferred Language'),
    )
    dark_mode = models.BooleanField(default=True, verbose_name=_('Dark Mode'))
    must_change_password = models.BooleanField(default=False, verbose_name=_('Must Change Password'))
    password_generated_by_system = models.BooleanField(default=False, verbose_name=_('Password Generated by System'))
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'users'
        verbose_name = _('User')
        verbose_name_plural = _('Users')

    def __str__(self):
        return f"{self.get_full_name() or self.username} ({self.get_role_display()})"

    @property
    def is_admin(self):
        return self.role == self.ROLE_ADMIN

    @property
    def is_teacher(self):
        return self.role == self.ROLE_TEACHER

    @property
    def is_employee(self):
        return self.role in (self.ROLE_EMPLOYEE, self.ROLE_TEACHER)

    @property
    def is_student(self):
        return self.role == self.ROLE_STUDENT

    @property
    def is_parent(self):
        return self.role == self.ROLE_PARENT
