import { LessonPlan, LessonStage, LessonStageName, RepeatableItem, WeeklyDayName, WeeklyPlanDay } from "../types/lesson";
import { uid } from "../utils/id";
import { createVariedWeeklyPlan } from "../services/lessonContentVariationService";

export const schoolName = "KINSHASA CHRISTIAN SCHOOL";
export const schoolShortName = "KCS";
export const schoolDisplayName = `${schoolShortName} - ${schoolName}`;
export const schoolImage = `${import.meta.env.BASE_URL.replace(/\/$/, "")}/kcs.jpg`;

export const stageNames: LessonStageName[] = [
  "Starter",
  "Introduction",
  "Presentation",
  "Guided Practice",
  "Independent Practice",
  "Collaborative Activity",
  "Assessment",
  "Closure",
  "Homework",
  "Reflection"
];

export const weeklyDayNames: WeeklyDayName[] = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"];

export const emptyItem = (value = ""): RepeatableItem => ({ id: uid("item"), value });

export const createStage = (name: LessonStageName): LessonStage => ({
  id: uid("stage"),
  name,
  duration: name === "Starter" ? "5 min" : "10 min",
  teacherActivities: "",
  studentActivities: "",
  resources: "",
  notes: "",
  attachments: [],
  images: []
});

export const createFlexibleWeeklyPlan = (subject = "", gradeClass = "", chapter = ""): WeeklyPlanDay[] => {
  return createVariedWeeklyPlan({ subject, gradeClass, chapter });
};

export const isAutoGeneratedWeeklyPlan = (weeklyPlan?: Partial<WeeklyPlanDay>[], subject = "", gradeClass = "", chapter = "") => {
  if (!weeklyPlan?.length) return true;

  const text = weeklyPlan
    .map((day) => Object.entries(day || {})
      .filter(([key]) => key !== "day")
      .map(([, value]) => (typeof value === "string" ? value : ""))
      .join(" "))
    .join(" ")
    .trim();

  if (!text) return true;

  const hasGenericPlaceholder = ["the selected unit", "the subject", "the class"].some((marker) => text.includes(marker));
  if (hasGenericPlaceholder) return true;

  const expected = createFlexibleWeeklyPlan(subject, gradeClass, chapter);
  const editableKeys: (keyof Omit<WeeklyPlanDay, "day">)[] = [
    "lesson",
    "objectives",
    "presentation",
    "guidedPractice",
    "exitTicket",
    "assessment",
    "homework"
  ];

  return expected.every((expectedDay, index) => {
    const currentDay = weeklyPlan[index] || {};
    return editableKeys.every((key) => !currentDay[key] || currentDay[key] === expectedDay[key]);
  });
};

export const createAutomaticLessonSupport = (subject = "", gradeClass = "", chapter = "") => {
  const subjectLabel = subject || "the subject";
  const gradeLabel = gradeClass || "the class";
  const chapterLabel = chapter || "the selected unit";

  return {
    learningObjectives: [
      `Identify the main ideas and skills connected to ${chapterLabel}.`,
      `Apply ${subjectLabel} concepts through guided and independent practice.`,
      `Demonstrate understanding through oral responses, written work, and an exit task.`
    ],
    learningOutcomes: [
      `Learners in ${gradeLabel} can explain the focus of ${chapterLabel}.`,
      `Learners can complete practice tasks with increasing accuracy.`
    ],
    successCriteria: [
      "Learners participate actively during modelling and practice.",
      "Learners complete classwork with correct reasoning or explanation.",
      "Learners show understanding in the exit ticket or homework task."
    ],
    vocabulary: `${chapterLabel}; key terms; examples; practice language`,
    materialsResources: "Board, markers, notebooks, textbook or reference material, teacher examples, practice exercises",
    differentiation: "Provide guided examples, peer support, extra scaffolding for struggling learners, and extension tasks for fast finishers.",
    assessment: "Teacher checks participation, oral responses, written practice, exit tickets, homework, and common errors.",
    reflection: "Review learner responses after the lesson and adjust the next lesson according to common needs."
  };
};

export const createPdfExampleWeeklyPlan = (): WeeklyPlanDay[] => [
  {
    day: "Monday",
    lesson: "Types of Sentences / Subjects and Predicates",
    objectives: "Write, identify, and punctuate declarative, imperative, interrogative, and exclamatory sentences.",
    introduction: "Review complete sentences and ask learners to identify sentence purpose from short examples.",
    presentation: "Explain the four types of sentences, then introduce subject and predicate using examples.",
    guidedPractice: "Learners identify sentence types, subjects, and predicates in model sentences.",
    exitTicket: "Learners write one example for each sentence type.",
    assessment: "Observe participation and mark written exercises.",
    homework: "Write eight sentences: 2 declarative, 2 interrogative, 2 imperative and 2 exclamatory. Underline the subject and circle the predicate."
  },
  {
    day: "Tuesday",
    lesson: "Compound Subjects and Predicates / Compound Sentences",
    objectives: "Identify compound subjects and predicates. Distinguish simple and compound sentences. Write compound sentences using coordinating conjunctions.",
    introduction: "Review simple subjects and predicates, then introduce how ideas can be joined.",
    presentation: "Teach compound subjects, compound predicates, and compound sentences with examples.",
    guidedPractice: "Learners identify and create compound sentences.",
    exitTicket: "Learners combine two simple sentences with a coordinating conjunction.",
    assessment: "Check correct use of coordinating conjunctions and sentence punctuation.",
    homework: "Write 10 compound sentences using different coordinating conjunctions."
  },
  {
    day: "Wednesday",
    lesson: "Subordinating Conjunctions / Complex Sentences",
    objectives: "Identify subordinating conjunctions such as because, although, if, and when. Use subordinating conjunctions in sentences.",
    introduction: "Ask learners how one idea can depend on another idea in a sentence.",
    presentation: "Explain that subordinating conjunctions introduce a subordinate clause and connect it to a main clause.",
    guidedPractice: "Learners join clauses using subordinating conjunctions.",
    exitTicket: "What is a subordinating conjunction? What is a complex sentence? Give one example of each.",
    assessment: "Evaluate ability to form complex sentences and participate in class activities.",
    homework: "Write 10 complex sentences using different subordinating conjunctions."
  },
  {
    day: "Thursday",
    lesson: "Simple, Compound, and Complex Sentences / Prepositions",
    objectives: "Identify, differentiate, and construct simple, compound, and complex sentences.",
    introduction: "Review the three sentence types using learner-generated examples.",
    presentation: "Explain the three sentence types and introduce common prepositions such as in, on, under, behind, between, and at.",
    guidedPractice: "Learners write 3 simple, 3 compound, and 3 complex sentences.",
    exitTicket: "What are the three types of sentences? Give examples.",
    assessment: "Teacher checks written exercises.",
    homework: "Write 10 mixed sentences and identify their types."
  },
  {
    day: "Friday",
    lesson: "Prepositional Phrases / Chapter 1 Review",
    objectives: "Identify and use prepositions and prepositional phrases.",
    introduction: "Use classroom objects to review location words before defining prepositional phrases.",
    presentation: "Explain that a prepositional phrase is made of a preposition and its object.",
    guidedPractice: "Learners identify prepositional phrases in sentences and write original examples.",
    exitTicket: "What is a preposition? Give examples.",
    assessment: "First test / chapter review.",
    homework: "Write 10 sentences using different prepositions and prepositional phrases."
  }
];

export const createBlankLesson = (lessonNumber: string): LessonPlan => {
  const now = new Date().toISOString();
  const currentYear = new Date().getFullYear();
  const today = new Date();
  const weekStartDate = toIsoDate(addDays(today, -((today.getDay() + 6) % 7)));
  const weekEndDate = toIsoDate(addDays(new Date(`${weekStartDate}T00:00:00`), 4));

  return {
    id: uid("lesson"),
    ownerId: "",
    ownerName: "",
    department: "",
    lessonNumber,
    planType: "weekly",
    status: "draft",
    tags: [],
    schoolName: schoolDisplayName,
    schoolYear: `${currentYear}-${currentYear + 1}`,
    semester: "1st",
    quarter: "1st",
    chapter: "",
    teachers: "",
    subject: "",
    gradeClass: "",
    date: new Date().toISOString().slice(0, 10),
    week: "",
    weekStartDate,
    weekEndDate,
    term: "1st Quarter",
    duration: "45 min",
    classroom: "",
    numberOfStudents: "",
    topic: "",
    subtopic: "",
    referenceBook: "",
    learningArea: "",
    biblicalIntegration: "",
    crossCurricularConnections: "",
    learningObjectives: [emptyItem()],
    learningOutcomes: [emptyItem()],
    successCriteria: [emptyItem()],
    materialsResources: [emptyItem()],
    vocabulary: [emptyItem()],
    safetyConsiderations: [emptyItem()],
    stages: stageNames.map(createStage),
    blooms: {
      remember: [""],
      understand: [""],
      apply: [""],
      analyze: [""],
      evaluate: [""],
      create: [""]
    },
    differentiation: {
      strugglingLearners: "",
      eslSupport: "",
      giftedLearners: "",
      specialNeeds: "",
      inclusiveStrategies: ""
    },
    assessment: {
      diagnostic: "",
      formative: "",
      summative: "",
      observationChecklist: "",
      rubric: "",
      exitTicket: "",
      teacherComments: ""
    },
    reflection: {
      whatWentWell: "",
      challenges: "",
      improvements: "",
      followUpActivities: "",
      teacherNotes: ""
    },
    weeklyPlan: createFlexibleWeeklyPlan(),
    createdAt: now,
    updatedAt: now,
    activityLogs: [],
    revisionNotes: [],
    reviewerComments: [],
    revisionRequests: [],
    approvalHistory: [],
    workflowHistory: [],
    versions: []
  };
};

const addDays = (date: Date, days: number) => {
  const next = new Date(date);
  next.setDate(date.getDate() + days);
  return next;
};

const toIsoDate = (date: Date) => {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
};
