import { useEffect, useState, type FormEvent } from 'react'
import { Download, FileCheck2, FileText, PlusCircle, Printer, Send, ShieldCheck } from 'lucide-react'
import PortalSidebar from '@/components/layout/PortalSidebar'
import { incidentReportsAPI } from '@/services/api'
import { useAuthStore } from '@/store/authStore'
import { printOfficialPdf } from '@/utils/officialPdf'

type Report={id:string;reference:string;title:string;category:string;occurredAt:string;location:string;description:string;peopleInvolved?:string;immediateActions?:string;confidentiality:'STANDARD'|'CONFIDENTIAL';status:'SUBMITTED'|'UNDER_REVIEW'|'CLOSED';adminNotes?:string;authorName:string;authorRole:string;attachmentName?:string;attachmentSize?:number;verificationHash:string;createdAt:string}
const empty={title:'',category:'Operational',occurredAt:'',location:'',description:'',peopleInvolved:'',immediateActions:'',confidentiality:'STANDARD'}
const labels={SUBMITTED:'Reçu',UNDER_REVIEW:'En analyse',CLOSED:'Clôturé'}

export default function IncidentReportsPage(){
 const {user}=useAuthStore();const superAdmin=user?.id==='configured-superadmin'
 const fieldClass='w-full rounded-2xl border border-kcs-blue-200 bg-kcs-blue-50/70 px-4 py-3 text-sm text-kcs-blue-950 outline-none transition focus:border-kcs-gold-500 focus:ring-4 focus:ring-kcs-gold-100/60 dark:border-kcs-blue-700 dark:bg-kcs-blue-950/70 dark:text-white dark:focus:ring-kcs-gold-900/30';
 const blankFilters={q:'',status:'',category:'',authorRole:'',confidentiality:'',dateFrom:'',dateTo:'',hasAttachment:''}
 const [reports,setReports]=useState<Report[]>([]),[form,setForm]=useState(empty),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[filters,setFilters]=useState(blankFilters)
 const load=async()=>{try{const response=await incidentReportsAPI.list();setReports(response.data.data||[])}catch{setMessage('Impossible de charger les rapports.')}}
 useEffect(()=>{void load()},[])
 const categories=[...new Set(reports.map(r=>r.category))].sort(),roles=[...new Set(reports.map(r=>r.authorRole))].sort()
 const visibleReports=reports.filter(r=>{const q=filters.q.toLocaleLowerCase();const hay=[r.reference,r.title,r.category,r.location,r.description,r.peopleInvolved,r.immediateActions,r.authorName,r.adminNotes].join(' ').toLocaleLowerCase();const day=r.occurredAt.slice(0,10);return(!q||hay.includes(q))&&(!filters.status||r.status===filters.status)&&(!filters.category||r.category===filters.category)&&(!filters.authorRole||r.authorRole===filters.authorRole)&&(!filters.confidentiality||r.confidentiality===filters.confidentiality)&&(!filters.dateFrom||day>=filters.dateFrom)&&(!filters.dateTo||day<=filters.dateTo)&&(!filters.hasAttachment||(filters.hasAttachment==='yes'?Boolean(r.attachmentName):!r.attachmentName))})
 const submit=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setMessage('');try{const data=new FormData();Object.entries(form).forEach(([k,v])=>data.append(k,k==='occurredAt'?new Date(v).toISOString():v));if(file)data.append('attachment',file);await incidentReportsAPI.create(data);setForm(empty);setFile(null);setMessage('Rapport transmis et authentifié avec succès.');await load()}catch(error:any){setMessage(error?.response?.data?.message||'Envoi impossible. Vérifiez les informations et le document.')}finally{setBusy(false)}}
 const download=async(report:Report)=>{try{const response=await incidentReportsAPI.attachment(report.id);const url=URL.createObjectURL(response.data);const link=document.createElement('a');link.href=url;link.download=report.attachmentName||'preuve';document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url)}catch(error:any){setMessage(error?.response?.data?.message||'Téléchargement impossible.')}}
 const print=(r:Report)=>printOfficialPdf({title:'INCIDENT REPORT',subtitle:'Rapport officiel hors discipline',metadata:[['Référence',r.reference],['Statut',labels[r.status]],['Auteur',r.authorName],['Rôle',r.authorRole],['Date du fait',new Date(r.occurredAt).toLocaleString('fr-CD')],['Lieu',r.location],['Catégorie',r.category],['Confidentialité',r.confidentiality],['Empreinte SHA-256',r.verificationHash],['Vérification',`${location.origin}/api/incident-reports/verify/${r.reference}`]],narrative:`${r.description}\n\nPersonnes concernées : ${r.peopleInvolved||'Non renseigné'}\nMesures immédiates : ${r.immediateActions||'Aucune'}\n\nPièce justificative : ${r.attachmentName||'Aucune'}`})
 const update=async(r:Report,status:Report['status'])=>{setBusy(true);setMessage('');try{await incidentReportsAPI.updateStatus(r.id,{status,adminNotes:r.adminNotes||''});setMessage('Rapport mis à jour avec succès.');await load()}catch(error:any){setMessage(error?.response?.data?.message||'Mise à jour impossible.')}finally{setBusy(false)}}
 return <div className="portal-shell flex"><PortalSidebar/><main className="min-h-screen min-w-0 flex-1 overflow-x-hidden bg-gray-50 p-4 pt-20 dark:bg-kcs-blue-950 lg:p-8 lg:pt-8">
  <div className="mx-auto max-w-7xl space-y-6">
   <header className="rounded-3xl bg-gradient-to-r from-kcs-blue-900 to-kcs-blue-700 p-6 text-white shadow-xl"><div className="flex items-center gap-3"><ShieldCheck className="text-kcs-gold-400"/><div><p className="text-xs font-bold uppercase tracking-[.22em] text-kcs-gold-300">KCS Nexus</p><h1 className="font-display text-3xl font-bold">Incident Report</h1></div></div><p className="mt-3 max-w-3xl text-sm text-blue-100">{superAdmin?'Consultez les rapports reçus et créez également vos propres rapports officiels.':'Signalez ici tout événement important qui ne relève pas d’un incident disciplinaire.'}</p></header>
   <form onSubmit={submit} className="grid gap-4 rounded-3xl bg-white p-6 shadow-lg dark:bg-kcs-blue-900 md:grid-cols-2">
    <h2 className="md:col-span-2 flex items-center gap-3 font-display text-xl font-bold dark:text-white"><PlusCircle className="text-kcs-gold-500"/>Créer un nouveau rapport</h2>
    <input required minLength={5} placeholder="Titre du rapport" className={fieldClass} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/>
    <select className={fieldClass} value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option>Operational</option><option>Santé et sécurité</option><option>Infrastructure</option><option>Transport</option><option>Événement</option><option>Administration</option><option>Autre</option></select>
    <input required type="datetime-local" className={fieldClass} value={form.occurredAt} onChange={e=>setForm({...form,occurredAt:e.target.value})}/>
    <input required placeholder="Lieu exact" className={fieldClass} value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/>
    <textarea required minLength={20} placeholder="Description factuelle et chronologique" className={`${fieldClass} min-h-36 md:col-span-2`} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/>
    <textarea placeholder="Personnes concernées ou témoins" className={`${fieldClass} min-h-24`} value={form.peopleInvolved} onChange={e=>setForm({...form,peopleInvolved:e.target.value})}/>
    <textarea placeholder="Mesures prises immédiatement" className={`${fieldClass} min-h-24`} value={form.immediateActions} onChange={e=>setForm({...form,immediateActions:e.target.value})}/>
    <label className="rounded-2xl border-2 border-dashed border-kcs-blue-200 p-4 text-sm dark:text-white"><FileText className="mb-2"/><b>Preuve PDF ou Word</b><span className="block text-xs text-gray-500">PDF, DOC, DOCX — 10 Mo maximum</span><input className="mt-3 block w-full" type="file" accept=".pdf,.doc,.docx,application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document" onChange={e=>setFile(e.target.files?.[0]||null)}/></label>
    <label className="flex items-center gap-3 rounded-2xl border p-4 dark:text-white"><input type="checkbox" checked={form.confidentiality==='CONFIDENTIAL'} onChange={e=>setForm({...form,confidentiality:e.target.checked?'CONFIDENTIAL':'STANDARD'})}/> Rapport confidentiel</label>
    <button disabled={busy} className="md:col-span-2 flex items-center justify-center gap-2 rounded-xl bg-kcs-blue-700 px-5 py-3 font-bold text-white disabled:opacity-60"><Send size={18}/>{busy?'Transmission…':superAdmin?'Enregistrer et soumettre':'Transmettre au SuperAdmin'}</button>
   </form>
   {message&&<p className="rounded-xl border border-kcs-gold-200 bg-kcs-gold-50 p-3 text-sm text-kcs-blue-900">{message}</p>}
   <section className="space-y-4"><div><h2 className="font-display text-2xl font-bold dark:text-white">{superAdmin?'Centre de suivi de tous les rapports':'Mes rapports'}</h2><p className="text-sm text-gray-500 dark:text-gray-300">{visibleReports.length} rapport(s) trouvé(s) sur {reports.length}</p></div>
    <div className="grid gap-3 rounded-3xl bg-white p-4 shadow dark:bg-kcs-blue-900 sm:grid-cols-2 lg:grid-cols-4">
     <input className={`${fieldClass} sm:col-span-2 lg:col-span-4`} placeholder="Référence, titre, auteur, lieu, personne, description ou note…" value={filters.q} onChange={e=>setFilters({...filters,q:e.target.value})}/>
     <select className={fieldClass} value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">Tous les statuts</option><option value="SUBMITTED">À traiter</option><option value="UNDER_REVIEW">En analyse</option><option value="CLOSED">Clôturés</option></select>
     <select className={fieldClass} value={filters.category} onChange={e=>setFilters({...filters,category:e.target.value})}><option value="">Toutes les catégories</option>{categories.map(x=><option key={x}>{x}</option>)}</select>
     {superAdmin&&<select className={fieldClass} value={filters.authorRole} onChange={e=>setFilters({...filters,authorRole:e.target.value})}><option value="">Tous les profils auteurs</option>{roles.map(x=><option key={x}>{x}</option>)}</select>}
     <select className={fieldClass} value={filters.confidentiality} onChange={e=>setFilters({...filters,confidentiality:e.target.value})}><option value="">Toute confidentialité</option><option value="STANDARD">Standard</option><option value="CONFIDENTIAL">Confidentiel</option></select>
     <input aria-label="Depuis" type="date" className={`${fieldClass} dark:[color-scheme:dark] dark:[&::-webkit-calendar-picker-indicator]:invert dark:[&::-webkit-calendar-picker-indicator]:opacity-100`} value={filters.dateFrom} onChange={e=>setFilters({...filters,dateFrom:e.target.value})}/>
     <input aria-label="Jusqu'au" type="date" className={`${fieldClass} dark:[color-scheme:dark] dark:[&::-webkit-calendar-picker-indicator]:invert dark:[&::-webkit-calendar-picker-indicator]:opacity-100`} value={filters.dateTo} onChange={e=>setFilters({...filters,dateTo:e.target.value})}/>
     <select className={fieldClass} value={filters.hasAttachment} onChange={e=>setFilters({...filters,hasAttachment:e.target.value})}><option value="">Avec ou sans pièce</option><option value="yes">Avec pièce jointe</option><option value="no">Sans pièce jointe</option></select>
     <button type="button" onClick={()=>setFilters(blankFilters)} className="rounded-xl border border-kcs-blue-200 px-4 py-2 font-bold dark:border-kcs-blue-700 dark:text-white">Réinitialiser les filtres</button>
    </div>
    {visibleReports.length===0&&<div className="rounded-2xl bg-white p-8 text-center text-gray-500 dark:bg-kcs-blue-900">Aucun rapport disponible.</div>}
    {visibleReports.map(r=><article key={r.id} className="rounded-3xl bg-white p-5 shadow dark:bg-kcs-blue-900 dark:text-white"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold text-kcs-gold-700">{r.reference}</p><h3 className="text-lg font-bold">{r.title}</h3><p className="text-sm text-gray-500">{r.authorName} · {new Date(r.occurredAt).toLocaleString('fr-CD')} · {r.location}</p></div><span className="rounded-full bg-kcs-blue-50 px-3 py-1 text-xs font-bold text-kcs-blue-800">{labels[r.status]}</span></div><p className="mt-4 whitespace-pre-wrap text-sm">{r.description}</p><div className="mt-4 flex flex-wrap gap-2">{r.attachmentName&&<button onClick={()=>void download(r)} className="flex items-center gap-2 rounded-xl border px-3 py-2 text-sm"><Download size={16}/>{r.attachmentName}</button>}<button onClick={()=>print(r)} className="flex items-center gap-2 rounded-xl bg-kcs-blue-700 px-3 py-2 text-sm text-white"><Printer size={16}/>PDF officiel</button>{superAdmin&&<><textarea aria-label="Notes administratives" placeholder="Notes du SuperAdmin" className="min-h-20 w-full rounded-xl border border-gray-200 p-3 text-sm text-kcs-blue-950 dark:border-kcs-blue-700 dark:bg-kcs-blue-950 dark:text-white" value={r.adminNotes||''} onChange={event=>setReports(current=>current.map(item=>item.id===r.id?{...item,adminNotes:event.target.value}:item))}/><button disabled={busy} onClick={()=>void update(r,'UNDER_REVIEW')} className="rounded-xl border px-3 py-2 text-sm">Mettre en analyse</button><button disabled={busy} onClick={()=>void update(r,'CLOSED')} className="flex items-center gap-2 rounded-xl bg-green-700 px-3 py-2 text-sm text-white"><FileCheck2 size={16}/>Clôturer</button></>}</div><p className="mt-3 break-all text-[10px] text-gray-400">SHA-256 : {r.verificationHash}</p></article>)}
   </section>
  </div>
 </main></div>
}
