CREATE TYPE "AssignmentCadence" AS ENUM ('ONE_TIME', 'DAILY', 'WEEKLY', 'MONTHLY', 'TERM', 'ANNUAL');

ALTER TYPE "AssignmentType" ADD VALUE IF NOT EXISTS 'CLASSWORK';
ALTER TYPE "AssignmentType" ADD VALUE IF NOT EXISTS 'TEST';
ALTER TYPE "AssignmentType" ADD VALUE IF NOT EXISTS 'PRESENTATION';
ALTER TYPE "AssignmentType" ADD VALUE IF NOT EXISTS 'RESEARCH';
ALTER TYPE "AssignmentType" ADD VALUE IF NOT EXISTS 'PRACTICAL';

ALTER TABLE "Assignment"
  ADD COLUMN "cadence" "AssignmentCadence" NOT NULL DEFAULT 'ONE_TIME',
  ADD COLUMN "estimatedMinutes" INTEGER,
  ADD COLUMN "resourceUrl" TEXT,
  ADD COLUMN "resourceName" TEXT,
  ADD COLUMN "publishedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;