import { zodResolver } from "@hookform/resolvers/zod";
import { ChevronDown, ChevronUp, Copy, Download, FileDown, Layers3, Loader2, Printer, Save, Sparkles, Trash2 } from "lucide-react";
import { CSSProperties, useEffect, useMemo, useRef, useState } from "react";
import { useForm } from "react-hook-form";
import { useReactToPrint } from "react-to-print";
import { useNavigate, useParams } from "react-router-dom";
import { z } from "zod";
import { useToast } from "../components/Toast";
import { Button } from "../components/ui/button";
import { Card } from "../components/ui/card";
import { Dialog } from "../components/ui/dialog";
import { Input, Select, Textarea } from "../components/ui/input";
import { Label } from "../components/ui/label";
import { useAuth } from "../contexts/AuthContext";
import {
  createAutomaticLessonSupport,
  createBlankLesson,
  createFlexibleWeeklyPlan,
  isAutoGeneratedWeeklyPlan,
  schoolDisplayName,
  schoolImage
} from "../data/defaults";
import { useDebouncedEffect } from "../hooks/useDebouncedEffect";
import { useKeyboardShortcuts } from "../hooks/useKeyboardShortcuts";
import { LessonPrint } from "../print/LessonPrint";
import { curriculumRepository, findCurriculumSuggestions } from "../services/curriculumRepository";
import { lessonRepository } from "../services/lessonRepository";
import { canDeleteLesson, canEditLesson, canReviewLesson, canViewLesson, prepareNewLessonForUser } from "../services/permissions";
import { analyzeWeeklyPlanQuality } from "../services/contentQualityService";
import { analyzeDurationAllocation, distributeActivityDurations, getActivityDurations, parseMinutes } from "../services/durationValidationService";
import { createSuggestedWeeklyDay, createVariedWeeklyPlan } from "../services/lessonContentVariationService";
import { LessonPlan, WeeklyPlanDay } from "../types/lesson";
import { exportElementToDocx, exportElementToPdf } from "../utils/export";

const schema = z.object({
  teachers: z.string().min(1, "Teacher is required"),
  subject: z.string().min(1, "Subject is required"),
  gradeClass: z.string().min(1, "Grade/Class is required"),
  chapter: z.string().min(1, "Chapter is required")
}).passthrough();

const weekOptions = Array.from({ length: 40 }, (_, index) => String(index + 1));
const durationOptions = ["30 min", "45 min", "50 min", "60 min", "1h", "1h15", "1h30", "2h"];
const semesterOptions = ["1st", "2nd"];
const quarterOptions = ["1st", "2nd", "3rd", "4th"];
const currentSchoolYear = new Date().getFullYear() - 1;
const schoolYearOptions = Array.from({ length: 8 }, (_, index) => {
  const start = currentSchoolYear + index;
  return `${start}-${start + 1}`;
});
type SetupField =
  | "planType"
  | "teachers"
  | "subject"
  | "gradeClass"
  | "chapter"
  | "date"
  | "week"
  | "weekStartDate"
  | "weekEndDate"
  | "duration"
  | "schoolYear"
  | "semester"
  | "quarter"
  | "term"
  | "classroom"
  | "numberOfStudents";
type WeeklyEditableKey = keyof Omit<WeeklyPlanDay, "day" | "activityDurations" | "lockedFields" | "editedFields">;

export const Editor = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const { notify } = useToast();
  const { currentUser, can } = useAuth();
  const [preview, setPreview] = useState(false);
  const [exporting, setExporting] = useState<"pdf" | "docx" | null>(null);
  const [revisionNote, setRevisionNote] = useState("");
  const [qualityChecksCollapsed, setQualityChecksCollapsed] = useState(false);
  const printRef = useRef<HTMLDivElement>(null);
  const [lesson, setLesson] = useState<LessonPlan | undefined>(() => (id ? lessonRepository.get(id) : undefined));
  const fallback = useMemo(() => createBlankLesson(`LP-${new Date().getFullYear()}-0001`), []);
  const canViewCurrent = lesson ? canViewLesson(currentUser, lesson) : true;
  const canEditCurrent = lesson ? canEditLesson(currentUser, lesson) : can("lesson:create");
  const canDeleteCurrent = lesson ? canDeleteLesson(currentUser, lesson) : false;
  const canReviewCurrent = lesson ? canReviewLesson(currentUser, lesson) : false;

  const form = useForm<LessonPlan>({
    defaultValues: lesson || fallback,
    resolver: zodResolver(schema),
    mode: "onChange"
  });

  useEffect(() => {
    const localLesson = id ? lessonRepository.get(id) : undefined;
    setLesson(localLesson);
    if (localLesson) form.reset(localLesson);
    if (!id || !currentUser) return;
    let cancelled = false;
    lessonRepository.syncFromCloud()
      .then(() => {
        const syncedLesson = lessonRepository.get(id);
        if (!cancelled && syncedLesson) {
          setLesson(syncedLesson);
          form.reset(syncedLesson);
        }
      })
      .catch(() => undefined);
    return () => {
      cancelled = true;
    };
  }, [id, currentUser?.id]);
  const previousSetupRef = useRef({
    subject: (lesson || fallback).subject,
    gradeClass: (lesson || fallback).gradeClass,
    chapter: sanitizeChapter((lesson || fallback).chapter)
  });
  const previousAutoObjectivesRef = useRef<string[]>([]);
  const previousLessonSupportRef = useRef<Record<number, Partial<Record<WeeklyEditableKey, string>>>>({});
  const values = form.watch();
  const currentChapter = sanitizeChapter(values.chapter);
  const planType = values.planType || "weekly";
  const weeklyPlan = normalizeEditableWeeklyPlan(values.weeklyPlan, values.subject, values.gradeClass, currentChapter);
  const displayedPlan = planType === "daily" ? weeklyPlan.slice(0, 1) : weeklyPlan;
  const lessonSignature = weeklyPlan.map((day) => day.lesson).join("|");
  const printableLesson = toPrintableLesson(values);
  const teacherFeedback = useMemo(() => getTeacherFeedback(values), [values]);
  const curriculumItems = useMemo(() => curriculumRepository.list(), []);
  const curriculumSuggestions = useMemo(() => findCurriculumSuggestions(curriculumItems, values.gradeClass, values.subject), [curriculumItems, values.gradeClass, values.subject]);
  const unitOptions = useMemo(() => unique([...curriculumSuggestions.map((item) => item.unit), currentChapter].filter(Boolean)), [curriculumSuggestions, currentChapter]);
  const topicOptions = useMemo(() => unique(curriculumSuggestions.map((item) => item.topic).filter(Boolean)), [curriculumSuggestions]);
  const subtopicOptions = useMemo(() => unique(curriculumSuggestions.map((item) => item.subtopic).filter(Boolean)), [curriculumSuggestions]);
  const qualityWarnings = useMemo(() => analyzeWeeklyPlanQuality(printableLesson), [printableLesson]);
  const durationWarnings = useMemo(() => analyzeDurationAllocation(printableLesson), [printableLesson]);

  useEffect(() => {
    if (!canEditCurrent) return;
    const current = form.getValues();
    const totalMinutes = parseMinutes(current.duration);
    if (!totalMinutes) return;

    const currentPlan = normalizeEditableWeeklyPlan(current.weeklyPlan, current.subject, current.gradeClass, sanitizeChapter(current.chapter));
    const needsInitialDurations = currentPlan.some((day) => !hasActivityDurations(day));
    if (!needsInitialDurations) return;

    form.setValue("weeklyPlan", currentPlan.map((day, index) => hasActivityDurations(day)
      ? day
      : {
        ...day,
        activityDurations: distributeActivityDurations(totalMinutes, { ...day, activityDurations: undefined }, index)
      }), {
      shouldDirty: true,
      shouldValidate: false
    });
  }, [canEditCurrent, form, values.duration, values.planType, values.subject, values.gradeClass, values.chapter]);

  useEffect(() => {
    const current = form.getValues();
    const chapter = sanitizeChapter(current.chapter);
    const hasSetup = Boolean(current.subject || current.gradeClass || chapter);
    const support = createAutomaticLessonSupport(current.subject, current.gradeClass, chapter);
    const previousSetup = previousSetupRef.current;
    const hasManualWeeklyEdits = current.weeklyPlan?.some((day) => day.editedFields && Object.values(day.editedFields).some(Boolean));
    const planCanSync =
      !hasManualWeeklyEdits &&
      (isAutoGeneratedWeeklyPlan(current.weeklyPlan, current.subject, current.gradeClass, chapter) ||
      isAutoGeneratedWeeklyPlan(current.weeklyPlan, previousSetup.subject, previousSetup.gradeClass, previousSetup.chapter));

    previousSetupRef.current = {
      subject: current.subject,
      gradeClass: current.gradeClass,
      chapter
    };

    if (!hasSetup) return;

    if (planCanSync) {
      form.setValue("weeklyPlan", createVariedWeeklyPlan(current), {
        shouldDirty: true,
        shouldValidate: false
      });

    } else {
      const previousGenerated = createVariedWeeklyPlan({
        ...current,
        subject: previousSetup.subject,
        gradeClass: previousSetup.gradeClass,
        chapter: previousSetup.chapter
      });
      const nextGenerated = createVariedWeeklyPlan({ ...current, chapter });
      const currentPlan = normalizeEditableWeeklyPlan(current.weeklyPlan, current.subject, current.gradeClass, chapter);
      let changed = false;
      const nextPlan = currentPlan.map((day, index) => {
        const generatedDay = nextGenerated[index];
        const previousDay = previousGenerated[index];
        const nextDay = { ...day };
        (["lesson", "objectives", "introduction", "presentation", "guidedPractice", "exitTicket", "assessment", "homework"] as WeeklyEditableKey[]).forEach((key) => {
          const locked = Boolean(day.lockedFields?.[key]);
          const manuallyEdited = Boolean(day.editedFields?.[key]);
          const currentValue = String(day[key] || "").trim();
          const previousValue = String(previousDay?.[key] || "").trim();
          const shouldSync = !locked && (!manuallyEdited || !currentValue || currentValue === previousValue || hasOldSetupText(currentValue, previousSetup));
          if (shouldSync && generatedDay?.[key] && currentValue !== generatedDay[key]) {
            nextDay[key] = generatedDay[key];
            changed = true;
          }
        });
        return nextDay;
      });
      if (changed) {
        form.setValue("weeklyPlan", planType === "daily" ? [nextPlan[getBusinessDayIndex(current.date)] || nextPlan[0], ...nextPlan.slice(1)] : nextPlan, {
          shouldDirty: true,
          shouldValidate: false
        });
      }
    }

    const nextTitle = buildAutomaticTitle(current);
    const titleCanSync = true;

    if (titleCanSync && nextTitle !== current.topic) {
      form.setValue("topic", nextTitle, {
        shouldDirty: true,
        shouldValidate: false
      });
    }

    if (!hasFilledItems(current.learningObjectives)) {
      form.setValue("learningObjectives", support.learningObjectives.map((value, index) => ({ id: `auto-objective-${index + 1}`, value })), {
        shouldDirty: true,
        shouldValidate: false
      });
    }

    if (!hasFilledItems(current.learningOutcomes)) {
      form.setValue("learningOutcomes", support.learningOutcomes.map((value, index) => ({ id: `auto-outcome-${index + 1}`, value })), {
        shouldDirty: true,
        shouldValidate: false
      });
    }

    if (!hasFilledItems(current.successCriteria)) {
      form.setValue("successCriteria", support.successCriteria.map((value, index) => ({ id: `auto-criteria-${index + 1}`, value })), {
        shouldDirty: true,
        shouldValidate: false
      });
    }

    if (!hasFilledItems(current.vocabulary)) {
      form.setValue("vocabulary", [{ id: "vocabulary", value: support.vocabulary }], {
        shouldDirty: true,
        shouldValidate: false
      });
    }

    if (!hasFilledItems(current.materialsResources)) {
      form.setValue("materialsResources", [{ id: "materials", value: support.materialsResources }], {
        shouldDirty: true,
        shouldValidate: false
      });
    }

    if (!current.differentiation?.inclusiveStrategies?.trim()) {
      form.setValue("differentiation.inclusiveStrategies", support.differentiation, {
        shouldDirty: true,
        shouldValidate: false
      });
    }

    if (!current.assessment?.teacherComments?.trim()) {
      form.setValue("assessment.teacherComments", support.assessment, {
        shouldDirty: true,
        shouldValidate: false
      });
    }

    if (!current.reflection?.teacherNotes?.trim()) {
      form.setValue("reflection.teacherNotes", support.reflection, {
        shouldDirty: true,
        shouldValidate: false
      });
    }
  }, [form, values.subject, values.gradeClass, values.chapter, values.week, values.weekStartDate, values.weekEndDate, values.date, values.planType]);

  useEffect(() => {
    const current = form.getValues();
    const currentPlan = normalizeEditableWeeklyPlan(current.weeklyPlan, current.subject, current.gradeClass, sanitizeChapter(current.chapter));
    let changed = false;

    const nextPlan = currentPlan.map((day, index) => {
      const generatedFromLesson = createLessonBasedSuggestion(current, day, index);
      const autoObjective = generatedFromLesson.objectives || createDailyObjective(day.lesson, current.subject, current.gradeClass, index);
      const previousAutoObjective = previousAutoObjectivesRef.current[index];
      const previousLessonObjective = previousLessonSupportRef.current[index]?.objectives || "";
      const currentObjective = day.objectives || "";
      const objectiveLocked = Boolean(day.lockedFields?.objectives);
      const objectiveManuallyEdited = Boolean(day.editedFields?.objectives);
      const objectiveCanSync =
        (!objectiveLocked && !currentObjective.trim()) ||
        (!objectiveLocked && !objectiveManuallyEdited && currentObjective === previousAutoObjective) ||
        (!objectiveLocked && !objectiveManuallyEdited && currentObjective === previousLessonObjective) ||
        (!objectiveLocked && isGenericObjective(currentObjective, current.gradeClass, sanitizeChapter(current.chapter)));
      const nextDay = { ...day };

      previousAutoObjectivesRef.current[index] = autoObjective;

      if (!day.day) {
        nextDay.day = weeklyPlan[index]?.day || day.day;
        changed = changed || nextDay.day !== day.day;
      }

      if (objectiveCanSync && currentObjective !== autoObjective) {
        nextDay.objectives = autoObjective;
        changed = true;
      }

      (["introduction", "presentation", "guidedPractice", "exitTicket", "assessment", "homework"] as WeeklyEditableKey[]).forEach((key) => {
        const locked = Boolean(day.lockedFields?.[key]);
        const manuallyEdited = Boolean(day.editedFields?.[key]);
        const currentValue = String(day[key] || "");
        const previousGenerated = previousLessonSupportRef.current[index]?.[key] || "";
        const nextGenerated = String(generatedFromLesson[key] || "");
        const canSync = !locked && !manuallyEdited && (!currentValue.trim() || currentValue === previousGenerated);

        if (canSync && nextGenerated && currentValue !== nextGenerated) {
          nextDay[key] = nextGenerated;
          changed = true;
        }
      });

      previousLessonSupportRef.current[index] = {
        ...(previousLessonSupportRef.current[index] || {}),
        objectives: generatedFromLesson.objectives,
        introduction: generatedFromLesson.introduction,
        presentation: generatedFromLesson.presentation,
        guidedPractice: generatedFromLesson.guidedPractice,
        exitTicket: generatedFromLesson.exitTicket,
        assessment: generatedFromLesson.assessment,
        homework: generatedFromLesson.homework
      };

      return nextDay;
    });

    if (changed) {
      form.setValue("weeklyPlan", nextPlan, {
        shouldDirty: true,
        shouldValidate: false
      });
    }
  }, [form, lessonSignature, values.subject, values.gradeClass, values.chapter, values.topic]);

  const completion = useMemo(() => {
    const required = [
      values.teachers,
      values.subject,
      values.gradeClass,
      values.chapter,
      ...displayedPlan.flatMap((day) => [day.lesson, day.objectives, day.presentation, day.assessment])
    ];
    return Math.round((required.filter(Boolean).length / required.length) * 100);
  }, [displayedPlan, values]);

  const save = (withVersion = false) => {
    if (!canEditCurrent) return;
    const current = form.getValues();
    const now = new Date().toISOString();
    const currentWeeklyPlan = normalizeEditableWeeklyPlan(current.weeklyPlan, current.subject, current.gradeClass, sanitizeChapter(current.chapter));
    const persistedWeeklyPlan = currentWeeklyPlan.map((day) => ({ ...day }));
    const next: LessonPlan = {
      ...toPrintableLesson(current),
      weeklyPlan: persistedWeeklyPlan,
      updatedAt: now,
      versions: withVersion
        ? [{ id: crypto.randomUUID(), savedAt: now, summary: `Manual save: ${current.chapter || current.topic}`, snapshot: { ...current, weeklyPlan: persistedWeeklyPlan, versions: [] } }, ...(current.versions || [])].slice(0, 20)
        : current.versions || []
    };
    lessonRepository.save(next, currentUser, withVersion ? "Manual save with revision snapshot" : "Autosaved lesson changes");
    if (withVersion) {
      form.reset(next, { keepValues: true });
      notify(`Saved checkpoint ${next.versions.length}`);
    }
  };

  useDebouncedEffect(() => {
    if (canEditCurrent && form.formState.isDirty) save(false);
  }, [values, canEditCurrent], 900);

  const printTitle = printableLesson.topic || printableLesson.chapter || "lesson-plan";
  const print = useReactToPrint({ contentRef: printRef, documentTitle: printTitle });

  useKeyboardShortcuts({
    save: () => save(true),
    print
  });

  const exportDocument = async (type: "pdf" | "docx") => {
    if (!printRef.current || exporting) return;
    setExporting(type);
    notify(type === "pdf" ? "PDF download in progress..." : "DOCX download in progress...");
    try {
      if (type === "pdf") {
        await exportElementToPdf(printRef.current, `${printTitle}.pdf`);
      } else {
        await exportElementToDocx(printRef.current, `${printTitle}.docx`);
      }
      notify(type === "pdf" ? "PDF downloaded" : "DOCX downloaded");
    } catch {
      notify("Download failed");
    } finally {
      setExporting(null);
    }
  };

  const duplicate = () => {
    if (!currentUser) return;
    const now = new Date().toISOString();
    const copy = prepareNewLessonForUser({
      ...form.getValues(),
      id: crypto.randomUUID(),
      ownerId: "",
      ownerName: "",
      department: "",
      lessonNumber: `LP-${new Date().getFullYear()}-${Date.now().toString().slice(-4)}`,
      createdAt: now,
      updatedAt: now,
      versions: []
    }, currentUser);
    lessonRepository.save(copy, currentUser, "Lesson plan duplicated from editor");
    notify("Duplicated lesson plan");
    navigate(`/editor/${copy.id}`);
  };

  const splitWeeklyIntoDailyPlans = () => {
    if (!currentUser || !canEditCurrent || planType !== "weekly") return;
    const current = toPrintableLesson(form.getValues());
    const sourcePlan = normalizeEditableWeeklyPlan(current.weeklyPlan, current.subject, current.gradeClass, sanitizeChapter(current.chapter));
    const now = new Date().toISOString();
    const created = sourcePlan.map((day, index) => {
      const daily = prepareNewLessonForUser({
        ...current,
        id: crypto.randomUUID(),
        lessonNumber: `${current.lessonNumber || `LP-${new Date().getFullYear()}`}-D${index + 1}`,
        planType: "daily",
        status: "draft",
        date: addDaysToIso(current.weekStartDate || getWeekStartFromDate(current.date), index),
        topic: buildAutomaticTitle({ ...current, planType: "daily", date: addDaysToIso(current.weekStartDate || getWeekStartFromDate(current.date), index) }),
        weeklyPlan: [day, ...createFlexibleWeeklyPlan(current.subject, current.gradeClass, sanitizeChapter(current.chapter)).slice(1)],
        createdAt: now,
        updatedAt: now,
        activityLogs: [],
        revisionNotes: [],
        reviewerComments: [],
        revisionRequests: [],
        approvalHistory: [],
        workflowHistory: [],
        versions: []
      }, currentUser);
      lessonRepository.save(daily, currentUser, `Daily lesson created from ${current.lessonNumber || current.id}`);
      return daily;
    });
    notify(`${created.length} daily lesson plans created`);
    navigate(`/editor/${created[0].id}`);
  };

  const buildWeeklyFromDailyPlans = () => {
    if (!currentUser || !canEditCurrent || planType !== "daily") return;
    const current = toPrintableLesson(form.getValues());
    const weekStart = current.weekStartDate || getWeekStartFromDate(current.date);
    const weekEnd = current.weekEndDate || addBusinessWeekEnd(weekStart);
    const matchingDailyPlans = lessonRepository
      .list()
      .filter((item) =>
        item.planType === "daily" &&
        item.ownerId === current.ownerId &&
        item.subject === current.subject &&
        item.gradeClass === current.gradeClass &&
        sanitizeChapter(item.chapter) === sanitizeChapter(current.chapter) &&
        item.date >= weekStart &&
        item.date <= weekEnd
      )
      .sort((a, b) => a.date.localeCompare(b.date));

    const basePlan = normalizeEditableWeeklyPlan(current.weeklyPlan, current.subject, current.gradeClass, sanitizeChapter(current.chapter));
    const combinedPlan = basePlan.map((baseDay, index) => {
      const date = addDaysToIso(weekStart, index);
      const daily = matchingDailyPlans.find((item) => item.date === date) || (index === 0 ? current : undefined);
      const dailyDay = daily ? normalizeEditableWeeklyPlan(daily.weeklyPlan, daily.subject, daily.gradeClass, sanitizeChapter(daily.chapter))[0] : undefined;
      return dailyDay ? { ...dailyDay, day: baseDay.day } : baseDay;
    });

    const now = new Date().toISOString();
    const weekly = prepareNewLessonForUser({
      ...current,
      id: crypto.randomUUID(),
      lessonNumber: `LP-${new Date().getFullYear()}-${Date.now().toString().slice(-4)}`,
      planType: "weekly",
      status: "draft",
      date: weekStart,
      weekStartDate: weekStart,
      weekEndDate: weekEnd,
      topic: buildAutomaticTitle({ ...current, planType: "weekly" }),
      weeklyPlan: combinedPlan,
      createdAt: now,
      updatedAt: now,
      activityLogs: [],
      revisionNotes: [],
      reviewerComments: [],
      revisionRequests: [],
      approvalHistory: [],
      workflowHistory: [],
      versions: []
    }, currentUser);
    lessonRepository.save(weekly, currentUser, `Weekly lesson built from ${matchingDailyPlans.length || 1} daily lesson plan${matchingDailyPlans.length === 1 ? "" : "s"}`);
    notify(`Weekly lesson plan created from ${matchingDailyPlans.length || 1} daily plan${matchingDailyPlans.length === 1 ? "" : "s"}`);
    navigate(`/editor/${weekly.id}`);
  };

  const generateWeek = () => {
    if (!canEditCurrent) return;
    const current = form.getValues();
    const subject = current.subject || "";
    const chapter = sanitizeChapter(current.chapter);
    const grade = current.gradeClass || "";
    const generated: WeeklyPlanDay[] = createVariedWeeklyPlan({ ...current, subject, gradeClass: grade, chapter });
    const totalMinutes = parseMinutes(current.duration);
    const generatedWithDurations = totalMinutes
      ? generated.map((day, index) => ({
        ...day,
        activityDurations: distributeActivityDurations(totalMinutes, { ...day, activityDurations: undefined }, index)
      }))
      : generated;
    if (planType === "daily") {
      const dayIndex = getBusinessDayIndex(current.date);
      const currentPlan = normalizeEditableWeeklyPlan(current.weeklyPlan, subject, grade, chapter);
      const daily = {
        ...generatedWithDurations[dayIndex],
        day: currentPlan[0]?.day || generated[dayIndex].day,
        lockedFields: currentPlan[0]?.lockedFields,
        activityDurations: currentPlan[0]?.activityDurations || generatedWithDurations[dayIndex].activityDurations,
        editedFields: {}
      };
      form.setValue("weeklyPlan", [daily, ...currentPlan.slice(1)], { shouldDirty: true, shouldValidate: false });
    } else {
      form.setValue("weeklyPlan", generatedWithDurations, { shouldDirty: true, shouldValidate: false });
    }
    const generatedTitle = buildAutomaticTitle({ ...current, subject, gradeClass: grade, chapter, planType });
    form.setValue("topic", generatedTitle, { shouldDirty: true });
    notify(planType === "daily" ? "Daily lesson generated automatically" : "Week generated automatically");
  };

  const updateWeeklyDay = (index: number, key: WeeklyEditableKey, value: string) => {
    if (!canEditCurrent) return;
    const next = normalizeEditableWeeklyPlan(form.getValues().weeklyPlan, form.getValues().subject, form.getValues().gradeClass, sanitizeChapter(form.getValues().chapter));
    next[index] = {
      ...next[index],
      [key]: value,
      editedFields: {
        ...(next[index].editedFields || {}),
        [key]: true
      }
    };
    form.setValue("weeklyPlan", next, {
      shouldDirty: true,
      shouldValidate: false
    });
  };

  const regenerateDay = (index: number) => {
    if (!canEditCurrent) return;
    const current = form.getValues();
    const next = normalizeEditableWeeklyPlan(current.weeklyPlan, current.subject, current.gradeClass, sanitizeChapter(current.chapter));
    const suggestion = createLessonBasedSuggestion(current, next[index], index);
    next[index] = {
      ...next[index],
      ...Object.fromEntries(Object.entries(suggestion).filter(([key]) => key === "day" || !next[index].lockedFields?.[key as WeeklyEditableKey]))
    } as WeeklyPlanDay;
    form.setValue("weeklyPlan", next, { shouldDirty: true, shouldValidate: false });
    notify(`${next[index].day} regenerated`);
  };

  const regenerateCell = (index: number, key: WeeklyEditableKey) => {
    if (!canEditCurrent) return;
    const current = form.getValues();
    const next = normalizeEditableWeeklyPlan(current.weeklyPlan, current.subject, current.gradeClass, sanitizeChapter(current.chapter));
    if (next[index].lockedFields?.[key]) {
      notify("Unlock this cell before regenerating it");
      return;
    }
    const suggestion = createLessonBasedSuggestion(current, next[index], index);
    next[index] = { ...next[index], [key]: suggestion[key] };
    form.setValue("weeklyPlan", next, { shouldDirty: true, shouldValidate: false });
    notify(`${next[index].day} ${rowLabel(key)} restored`);
  };

  const regenerateRow = (key: WeeklyEditableKey) => {
    if (!canEditCurrent) return;
    const current = form.getValues();
    const next = normalizeEditableWeeklyPlan(current.weeklyPlan, current.subject, current.gradeClass, sanitizeChapter(current.chapter));
    form.setValue("weeklyPlan", next.map((day, index) => {
      const suggestion = createLessonBasedSuggestion(current, day, index);
      return day.lockedFields?.[key] ? day : { ...day, [key]: suggestion[key] };
    }), {
      shouldDirty: true,
      shouldValidate: false
    });
    notify(`${rowLabel(key)} row regenerated`);
  };

  const toggleCellLock = (index: number, key: WeeklyEditableKey) => {
    if (!canEditCurrent) return;
    const current = form.getValues();
    const next = normalizeEditableWeeklyPlan(current.weeklyPlan, current.subject, current.gradeClass, sanitizeChapter(current.chapter));
    const lockedFields = { ...(next[index].lockedFields || {}), [key]: !next[index].lockedFields?.[key] };
    next[index] = { ...next[index], lockedFields };
    form.setValue("weeklyPlan", next, { shouldDirty: true, shouldValidate: false });
  };

  const updateActivityDuration = (index: number, key: "introduction" | "presentation" | "guidedPractice" | "exitTicket", value: string) => {
    if (!canEditCurrent) return;
    const current = form.getValues();
    const next = normalizeEditableWeeklyPlan(current.weeklyPlan, current.subject, current.gradeClass, sanitizeChapter(current.chapter));
    next[index] = {
      ...next[index],
      activityDurations: {
        ...next[index].activityDurations,
        [key]: Math.max(0, Number(value) || 0)
      }
    };
    form.setValue("weeklyPlan", next, { shouldDirty: true, shouldValidate: false });
  };

  const updateLessonDuration = (value: string) => {
    if (!canEditCurrent) return;
    const totalMinutes = parseMinutes(value);
    const current = form.getValues();
    const next = normalizeEditableWeeklyPlan(current.weeklyPlan, current.subject, current.gradeClass, sanitizeChapter(current.chapter));
    form.setValue("duration", value, {
      shouldDirty: true,
      shouldValidate: false
    });

    if (!totalMinutes) return;

    form.setValue("weeklyPlan", next.map((day, index) => ({
      ...day,
      activityDurations: distributeActivityDurations(totalMinutes, day, index)
    })), {
      shouldDirty: true,
      shouldValidate: false
    });
  };

  const updateSetupField = (field: SetupField, value: string) => {
    if (!canEditCurrent) return;
    if (field === "duration") {
      updateLessonDuration(value);
      return;
    }
    if (field === "weekStartDate") {
      form.setValue("weekEndDate", addBusinessWeekEnd(value), {
        shouldDirty: true,
        shouldValidate: false
      });
    }
    form.setValue(field, value, {
      shouldDirty: true,
      shouldValidate: false
    });
  };

  const applyCurriculumItem = (item = curriculumSuggestions[0]) => {
    if (!item || !canEditCurrent) return;
    form.setValue("chapter", item.unit, { shouldDirty: true });
    form.setValue("topic", item.topic, { shouldDirty: true });
    form.setValue("subtopic", item.subtopic, { shouldDirty: true });
    form.setValue("learningObjectives", item.learningObjectives.map((value, index) => ({ id: `curriculum-objective-${index + 1}`, value })), { shouldDirty: true });
    form.setValue("learningOutcomes", item.learningOutcomes.map((value, index) => ({ id: `curriculum-outcome-${index + 1}`, value })), { shouldDirty: true });
    form.setValue("referenceBook", item.references.join("; "), { shouldDirty: true });
    form.setValue("vocabulary", item.skills.map((value, index) => ({ id: `curriculum-skill-${index + 1}`, value })), { shouldDirty: true });
    form.setValue("crossCurricularConnections", [
      item.competencies.length ? `Competencies: ${item.competencies.join("; ")}` : "",
      item.curriculumStandards.length ? `Standards: ${item.curriculumStandards.join("; ")}` : ""
    ].filter(Boolean).join("\n"), { shouldDirty: true });
    notify("Curriculum suggestions applied");
  };

  if (!canViewCurrent) {
    return (
      <Card className="mx-auto mt-10 max-w-xl p-8 text-center">
        <p className="text-xs font-black uppercase text-cyan-200">Access restricted</p>
        <h1 className="mt-2 text-2xl font-black text-white">You do not have permission to view this lesson plan.</h1>
        <p className="mt-2 text-sm text-muted-foreground">Switch to an authorized role or return to the visible lesson plan library.</p>
        <Button className="mt-5" onClick={() => navigate("/plans")}>Back to plans</Button>
      </Card>
    );
  }

  return (
    <div className="min-w-0 space-y-4 overflow-hidden">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div className="min-w-0">
          <p className="text-xs font-black uppercase text-cyan-200">KCS {planType === "daily" ? "daily" : "weekly"} lesson plan</p>
          <h1 className="truncate text-2xl font-black text-white md:text-3xl">{printableLesson.topic || printableLesson.chapter || printableLesson.subject || "New Lesson Plan"}</h1>
          <p className="text-sm text-muted-foreground">
            KCS stays fixed; the title, lesson details, and teaching content come from your fields.
            {!canEditCurrent && " This plan is read-only for your current role."}
          </p>
          <p className="mt-1 text-xs text-muted-foreground">
            Owner: {printableLesson.ownerName || printableLesson.teachers || "Unassigned"} · Department: {printableLesson.department || "Unassigned"}
            {canReviewCurrent ? " · Department review enabled" : ""}
          </p>
        </div>
        <div className="flex min-w-0 flex-wrap gap-2">
          {canEditCurrent && <Button variant="outline" onClick={() => save(true)} title="Ctrl+S"><Save size={17} /> Save</Button>}
          {canEditCurrent && planType === "weekly" && <Button variant="outline" onClick={splitWeeklyIntoDailyPlans}><Copy size={17} /> Split daily</Button>}
          {canEditCurrent && planType === "daily" && <Button variant="outline" onClick={buildWeeklyFromDailyPlans}><Layers3 size={17} /> Build weekly</Button>}
          {can("lesson:create") && <Button variant="outline" onClick={duplicate}><Copy size={17} /> Duplicate</Button>}
          <Button variant="outline" onClick={() => setPreview(true)}><Printer size={17} /> Preview</Button>
          <Button variant="outline" disabled={Boolean(exporting)} onClick={() => exportDocument("pdf")}>{exporting === "pdf" ? <Loader2 className="animate-spin" size={17} /> : <FileDown size={17} />} {exporting === "pdf" ? "PDF..." : "PDF"}</Button>
          <Button variant="outline" disabled={Boolean(exporting)} onClick={() => exportDocument("docx")}>{exporting === "docx" ? <Loader2 className="animate-spin" size={17} /> : <Download size={17} />} {exporting === "docx" ? "DOCX..." : "DOCX"}</Button>
          {canDeleteCurrent && <Button variant="danger" onClick={() => { if (confirm("Move this lesson plan to deleted items?")) { lessonRepository.remove(values.id, currentUser); navigate("/plans"); } }}><Trash2 size={17} /></Button>}
        </div>
      </div>

      <div className="h-2 overflow-hidden rounded-full bg-white/[0.07]"><div className="h-full rounded-full bg-cyan-300 transition-all" style={{ width: `${completion}%` }} /></div>
      {teacherFeedback && (
        <Card className="border-orange-500/40 bg-orange-500/15 p-4">
          <p className="text-xs font-black uppercase text-orange-100">{teacherFeedback.title}</p>
          <p className="mt-1 text-sm font-bold text-white">{teacherFeedback.message}</p>
          <p className="mt-1 text-xs text-muted-foreground">
            {teacherFeedback.userName} - {new Date(teacherFeedback.timestamp).toLocaleString()}
          </p>
        </Card>
      )}
      {(qualityWarnings.length > 0 || durationWarnings.length > 0) && (
        <Card className="border-amber-500/45 bg-amber-100/80 p-4 dark:border-amber-400/35 dark:bg-amber-500/10">
          <div className="flex flex-wrap items-center justify-between gap-2">
            <p className="text-xs font-black uppercase text-amber-950 dark:text-amber-100">{planType === "daily" ? "Daily" : "Weekly"} plan quality checks</p>
            <div className="flex items-center gap-2">
              <span className="rounded-sm border border-amber-500/40 bg-white/70 px-2 py-1 text-xs font-black text-amber-950 dark:bg-amber-950/30 dark:text-amber-50">
                {qualityWarnings.length + durationWarnings.length} point{qualityWarnings.length + durationWarnings.length > 1 ? "s" : ""} to improve
              </span>
              <Button type="button" variant="outline" className="h-8 px-2 text-amber-950 dark:text-amber-50" onClick={(event) => { event.preventDefault(); event.stopPropagation(); setQualityChecksCollapsed((value) => !value); }}>
                {qualityChecksCollapsed ? <ChevronDown size={15} /> : <ChevronUp size={15} />}
                {qualityChecksCollapsed ? "Show" : "Hide"}
              </Button>
            </div>
          </div>
          {!qualityChecksCollapsed && <div className="mt-3 grid gap-2 text-sm font-semibold text-amber-900 dark:text-amber-50 md:grid-cols-2">
            {qualityWarnings.map((warning) => (
              <div key={warning.id} className="rounded-md border border-amber-500/25 bg-white/60 p-2 dark:bg-amber-950/20">
                {warning.field && <p className="text-xs font-black uppercase text-amber-800 dark:text-amber-200">{warning.field}</p>}
                <p>{warning.message}</p>
                <p className="mt-1 text-xs font-bold text-amber-800 dark:text-amber-100">Solution: {warning.suggestion}</p>
              </div>
            ))}
            {durationWarnings.map((warning) => (
              <div key={warning.id} className="rounded-md border border-amber-500/25 bg-white/60 p-2 dark:bg-amber-950/20">
                <p>{warning.message}</p>
                <p className="mt-1 text-xs font-bold text-amber-800 dark:text-amber-100">Solution: adjust the activity minutes so the total matches the lesson duration.</p>
              </div>
            ))}
          </div>}
        </Card>
      )}

      <div className="grid min-w-0 gap-5 xl:grid-cols-[minmax(0,1fr)_minmax(320px,380px)]">
        <form className="min-w-0 space-y-4" onSubmit={form.handleSubmit(() => save(true))}>
          <fieldset disabled={!canEditCurrent} className="min-w-0 space-y-4 disabled:opacity-75">
          <Card className="w-full max-w-full overflow-hidden p-3 sm:p-4">
            <div className="mb-4 flex flex-wrap items-center justify-between gap-3">
              <div>
                <h2 className="text-lg font-black text-white">1. Essential setup</h2>
                <p className="text-sm text-muted-foreground">Only the changing details are editable. KCS is already known.</p>
              </div>
              <div className="flex gap-2">
                <Button type="button" variant="secondary" onClick={generateWeek}><Sparkles size={17} /> {planType === "daily" ? "Generate day" : "Generate week"}</Button>
                {planType === "weekly" && <Button type="button" variant="outline" onClick={splitWeeklyIntoDailyPlans}><Copy size={17} /> Split daily</Button>}
                {planType === "daily" && <Button type="button" variant="outline" onClick={buildWeeklyFromDailyPlans}><Layers3 size={17} /> Build weekly</Button>}
              </div>
            </div>
            <div className="grid min-w-0 grid-cols-1 gap-3 md:grid-cols-2 xl:grid-cols-3">
              <Field label="Plan Type">
                <Select value={planType} onChange={(event) => updateSetupField("planType", event.target.value)}>
                  <option value="weekly">Weekly Lesson Plan</option>
                  <option value="daily">Daily Lesson Plan</option>
                </Select>
              </Field>
              <Field label="Lesson Plan Title"><Input readOnly value={printableLesson.topic} className="bg-white/[0.03]" /></Field>
              <LockedSchool />
              <Field label="Teacher"><Input value={values.teachers || ""} onChange={(event) => updateSetupField("teachers", event.target.value)} /></Field>
              <Field label="Subject"><Input list="subject-suggestions" value={values.subject || ""} onChange={(event) => updateSetupField("subject", event.target.value)} /></Field>
              <Field label="Grade"><Input list="grade-suggestions" value={values.gradeClass || ""} onChange={(event) => updateSetupField("gradeClass", event.target.value)} /></Field>
              <Field label="Chapter / Unit"><Input list="unit-suggestions" value={values.chapter || ""} onChange={(event) => updateSetupField("chapter", event.target.value)} /></Field>
              <Field label="Date"><Input type="date" value={values.date || ""} onChange={(event) => updateSetupField("date", event.target.value)} /></Field>
              {planType === "weekly" && <Field label="Week">
                <Select value={values.week || ""} onChange={(event) => updateSetupField("week", event.target.value)}>
                  <option value="">Select week</option>
                  {weekOptions.map((week) => <option key={week} value={week}>Week {week}</option>)}
                </Select>
              </Field>}
              {planType === "weekly" && <Field label="Week Start Date"><Input type="date" value={values.weekStartDate || ""} onChange={(event) => updateSetupField("weekStartDate", event.target.value)} /></Field>}
              {planType === "weekly" && <Field label="Week End Date"><Input type="date" value={values.weekEndDate || ""} onChange={(event) => updateSetupField("weekEndDate", event.target.value)} /></Field>}
              {planType === "weekly" && <div className="rounded-md border border-cyan-300/20 bg-cyan-500/10 px-3 py-2 text-sm font-bold text-cyan-100 md:col-span-2 xl:col-span-3">
                {formatWeekRangeLabel(values.week, values.weekStartDate, values.weekEndDate)}
              </div>}
              <Field label="Duration">
                <Select value={values.duration || "45 min"} onChange={(event) => updateSetupField("duration", event.target.value)}>
                  {values.duration && !durationOptions.includes(values.duration) && <option value={values.duration}>{values.duration}</option>}
                  {durationOptions.map((duration) => <option key={duration} value={duration}>{duration}</option>)}
                </Select>
              </Field>
              <Field label="School Year">
                <Select value={normalizeSchoolYear(values.schoolYear) || schoolYearOptions[0]} onChange={(event) => updateSetupField("schoolYear", event.target.value)}>
                  {normalizeSchoolYear(values.schoolYear) && !schoolYearOptions.includes(normalizeSchoolYear(values.schoolYear)) && (
                    <option value={normalizeSchoolYear(values.schoolYear)}>{normalizeSchoolYear(values.schoolYear)}</option>
                  )}
                  {schoolYearOptions.map((schoolYear) => <option key={schoolYear} value={schoolYear}>{schoolYear}</option>)}
                </Select>
              </Field>
              <Field label="Semester">
                <Select value={values.semester || "1st"} onChange={(event) => updateSetupField("semester", event.target.value)}>
                  {semesterOptions.map((semester) => <option key={semester} value={semester}>{semester} Semester</option>)}
                </Select>
              </Field>
              <Field label="Quarter">
                <Select value={values.quarter || "1st"} onChange={(event) => updateSetupField("quarter", event.target.value)}>
                  {quarterOptions.map((quarter) => <option key={quarter} value={quarter}>{quarter} Quarter</option>)}
                </Select>
              </Field>
              <Field label="Term"><Input value={values.term || ""} onChange={(event) => updateSetupField("term", event.target.value)} /></Field>
              <Field label="Classroom"><Input value={values.classroom || ""} onChange={(event) => updateSetupField("classroom", event.target.value)} /></Field>
              <Field label="Number of Students"><Input value={values.numberOfStudents || ""} onChange={(event) => updateSetupField("numberOfStudents", event.target.value)} /></Field>
            </div>
            <datalist id="subject-suggestions">
              {["Mathematics", "English", "English (Writing and Grammar)", "Science", "French", "Computer Science", "History", "Geography", "Physics", "Chemistry", "Biology", "Art", "Music", "Physical Education"].map((item) => <option key={item} value={item} />)}
            </datalist>
            <datalist id="grade-suggestions">
              {["K3", "K4", "K5", ...Array.from({ length: 12 }, (_, i) => `Grade ${i + 1}`)].map((item) => <option key={item} value={item} />)}
            </datalist>
            <datalist id="unit-suggestions">
              {unitOptions.map((item) => <option key={item} value={item} />)}
            </datalist>
          </Card>

          {curriculumSuggestions.length > 0 && (
            <Card className="w-full max-w-full overflow-hidden p-3 sm:p-4">
              <div className="mb-4 flex flex-wrap items-center justify-between gap-3">
                <div>
                  <h2 className="text-lg font-black text-white">Curriculum suggestions</h2>
                  <p className="text-sm text-muted-foreground">Suggestions for {values.gradeClass || "grade"} and {values.subject || "subject"}.</p>
                </div>
                {canEditCurrent && <Button type="button" variant="outline" onClick={() => applyCurriculumItem()}><Sparkles size={17} /> Apply first match</Button>}
              </div>
              <div className="grid gap-3 md:grid-cols-2">
                <Field label="Topic suggestion"><Input list="topic-suggestions" value={values.topic || ""} onChange={(event) => form.setValue("topic", event.target.value, { shouldDirty: true })} /></Field>
                <Field label="Subtopic suggestion"><Input list="subtopic-suggestions" value={values.subtopic || ""} onChange={(event) => form.setValue("subtopic", event.target.value, { shouldDirty: true })} /></Field>
              </div>
              <div className="mt-3 grid gap-3">
                {curriculumSuggestions.slice(0, 4).map((item) => (
                  <div key={item.id} className="rounded-md border border-cyan-300/15 bg-cyan-500/10 p-3">
                    <div className="flex flex-wrap items-start justify-between gap-2">
                      <div>
                        <p className="text-xs font-black uppercase text-cyan-200">{item.academicYear} - {item.term}</p>
                        <p className="font-black text-white">{item.unit}: {item.topic}</p>
                        <p className="text-sm text-muted-foreground">{item.subtopic}</p>
                      </div>
                      {canEditCurrent && <Button type="button" variant="outline" onClick={() => applyCurriculumItem(item)}>Apply</Button>}
                    </div>
                    <p className="mt-2 text-sm text-muted-foreground">Objectives: {item.learningObjectives.slice(0, 2).join("; ")}</p>
                    <p className="mt-1 text-xs text-muted-foreground">Competencies: {item.competencies.join("; ") || "None"} - Standards: {item.curriculumStandards.join("; ") || "None"}</p>
                  </div>
                ))}
              </div>
              <datalist id="topic-suggestions">{topicOptions.map((item) => <option key={item} value={item} />)}</datalist>
              <datalist id="subtopic-suggestions">{subtopicOptions.map((item) => <option key={item} value={item} />)}</datalist>
            </Card>
          )}

          <Card className="w-full max-w-full overflow-hidden p-3 sm:p-4">
            <div className="mb-4 flex flex-wrap items-start justify-between gap-3">
              <div>
                <h2 className="text-lg font-black text-white">2. {planType === "daily" ? "Daily lesson" : "Weekly grid"}</h2>
                <p className="text-sm text-muted-foreground">{planType === "daily" ? "Edit the single lesson for the selected date." : "Use Generate week first, then edit only the parts that need teacher judgement."}</p>
              </div>
              {planType === "weekly" && canEditCurrent && (
                <div className="flex flex-wrap gap-2">
                  <Button type="button" variant="outline" onClick={() => regenerateRow("objectives")}>Objectives row</Button>
                  <Button type="button" variant="outline" onClick={() => regenerateRow("presentation")}>Presentation row</Button>
                  <Button type="button" variant="outline" onClick={() => regenerateRow("assessment")}>Assessment row</Button>
                </div>
              )}
            </div>
            <div className={`grid min-w-0 grid-cols-1 gap-3 ${planType === "weekly" ? "md:grid-cols-2 2xl:grid-cols-5" : ""}`}>
              {displayedPlan.map((day, index) => {
                const durations = getActivityDurations(day, index);
                const allocated = durations.introduction + durations.presentation + durations.guidedPractice + durations.exitTicket;
                const lessonDuration = parseMinutes(values.duration) || allocated;
                return (
                <div key={day.day} className="theme-dark-panel min-w-0 rounded-lg border border-cyan-300/15 bg-[#030d14]/70 p-3">
                  <div className="mb-3 rounded-md border border-cyan-300/20 bg-cyan-500/10 px-3 py-2 text-center">
                    <h3 className="text-sm font-black text-cyan-100">{planType === "daily" ? "Daily Lesson" : day.day}</h3>
                    <div className="mx-auto mt-2 flex max-w-[11rem] items-center justify-center gap-2">
                      <Input
                        type="number"
                        min="1"
                        className="h-8 text-center"
                        value={lessonDuration}
                        onChange={(event) => updateLessonDuration(`${Math.max(1, Number(event.target.value) || 1)} min`)}
                        aria-label={`${planType === "daily" ? "Daily lesson" : day.day} duration`}
                      />
                      <span className="text-[11px] font-bold text-cyan-50/80">min</span>
                    </div>
                    <p className="mt-1 text-[11px] font-bold text-cyan-50/70">{allocated} min in activities</p>
                    {canEditCurrent && <Button type="button" variant="ghost" className="mt-2 h-7 px-2 text-xs" onClick={() => regenerateDay(index)}><Sparkles size={13} /> Regenerate day</Button>}
                  </div>
                  <div className="space-y-2">
                    <WeeklyField label="Lesson" locked={Boolean(day.lockedFields?.lesson)} onRegenerate={() => regenerateCell(index, "lesson")} onToggleLock={() => toggleCellLock(index, "lesson")}>
                      <Textarea className="min-h-16" value={day.lesson} onChange={(event) => updateWeeklyDay(index, "lesson", event.target.value)} />
                    </WeeklyField>
                    <WeeklyField label="Objectives" locked={Boolean(day.lockedFields?.objectives)} onRegenerate={() => regenerateCell(index, "objectives")} onToggleLock={() => toggleCellLock(index, "objectives")}>
                      <Textarea className="min-h-20" value={day.objectives} onChange={(event) => updateWeeklyDay(index, "objectives", event.target.value)} />
                    </WeeklyField>
                    <WeeklyField label={`Introduction (${durations.introduction} min)`} locked={Boolean(day.lockedFields?.introduction)} onRegenerate={() => regenerateCell(index, "introduction")} onToggleLock={() => toggleCellLock(index, "introduction")}>
                      <Textarea className="min-h-16" value={day.introduction} onChange={(event) => updateWeeklyDay(index, "introduction", event.target.value)} />
                      <Input type="number" min="0" className="mt-1 h-8" value={durations.introduction} onChange={(event) => updateActivityDuration(index, "introduction", event.target.value)} />
                    </WeeklyField>
                    <WeeklyField label={`Presentation / Guided Practice (${durations.presentation + durations.guidedPractice} min)`} locked={Boolean(day.lockedFields?.presentation || day.lockedFields?.guidedPractice)} onRegenerate={() => { regenerateCell(index, "presentation"); regenerateCell(index, "guidedPractice"); }} onToggleLock={() => { toggleCellLock(index, "presentation"); toggleCellLock(index, "guidedPractice"); }}>
                      <Label className="text-xs text-cyan-100">Presentation ({durations.presentation} min)</Label>
                      <Textarea className="min-h-16" value={day.presentation} onChange={(event) => updateWeeklyDay(index, "presentation", event.target.value)} />
                      <Input type="number" min="0" className="mt-1 h-8" value={durations.presentation} onChange={(event) => updateActivityDuration(index, "presentation", event.target.value)} />
                      <Label className="mt-2 text-xs text-cyan-100">Guided Practice ({durations.guidedPractice} min)</Label>
                      <Textarea className="min-h-16" value={day.guidedPractice} onChange={(event) => updateWeeklyDay(index, "guidedPractice", event.target.value)} />
                      <Input type="number" min="0" className="mt-1 h-8" value={durations.guidedPractice} onChange={(event) => updateActivityDuration(index, "guidedPractice", event.target.value)} />
                    </WeeklyField>
                    <WeeklyField label={`Exit Ticket / Assessment (${durations.exitTicket} min)`} locked={Boolean(day.lockedFields?.exitTicket || day.lockedFields?.assessment)} onRegenerate={() => { regenerateCell(index, "exitTicket"); regenerateCell(index, "assessment"); }} onToggleLock={() => { toggleCellLock(index, "exitTicket"); toggleCellLock(index, "assessment"); }}>
                      <Label className="text-xs text-cyan-100">Exit Ticket ({durations.exitTicket} min)</Label>
                      <Textarea className="min-h-16" value={day.exitTicket} onChange={(event) => updateWeeklyDay(index, "exitTicket", event.target.value)} />
                      <Input type="number" min="0" className="mt-1 h-8" value={durations.exitTicket} onChange={(event) => updateActivityDuration(index, "exitTicket", event.target.value)} />
                      <Label className="mt-2 text-xs text-cyan-100">Assessment</Label>
                      <Textarea className="min-h-16" value={day.assessment} onChange={(event) => updateWeeklyDay(index, "assessment", event.target.value)} />
                    </WeeklyField>
                    <WeeklyField label="Homework" locked={Boolean(day.lockedFields?.homework)} onRegenerate={() => regenerateCell(index, "homework")} onToggleLock={() => toggleCellLock(index, "homework")}>
                      <Textarea className="min-h-16" value={day.homework} onChange={(event) => updateWeeklyDay(index, "homework", event.target.value)} />
                    </WeeklyField>
                  </div>
                </div>
              );})}
            </div>
          </Card>
          </fieldset>
        </form>

        <aside className="space-y-4">
          <Card className="w-full max-w-full overflow-hidden p-3 sm:p-4">
            <div className="mb-3 flex items-center justify-between gap-3">
              <div>
                <h2 className="text-lg font-black text-white">Lifecycle and history</h2>
                <p className="text-xs text-muted-foreground">Status, revision notes, and activity log.</p>
              </div>
              <span className="rounded-full border border-cyan-300/25 bg-cyan-500/10 px-3 py-1 text-xs font-black uppercase text-cyan-100">{statusLabel(values.status)}</span>
            </div>
            {canEditCurrent && (
              <div className="mb-4 space-y-2">
                <Label>Revision note</Label>
                <Textarea className="min-h-20" value={revisionNote} onChange={(event) => setRevisionNote(event.target.value)} placeholder="Explain what changed or what needs review..." />
                <Button
                  variant="outline"
                  onClick={() => {
                    const next = lessonRepository.addRevisionNote(values.id, revisionNote, currentUser);
                    if (next) form.reset(next);
                    setRevisionNote("");
                    notify("Revision note added");
                  }}
                  disabled={!revisionNote.trim()}
                >
                  Add note
                </Button>
              </div>
            )}
            <div className="space-y-3">
              {(values.revisionNotes || []).slice(0, 3).map((note) => (
                <div key={note.id} className="rounded-md border border-cyan-300/15 bg-white/[0.04] p-3 text-sm">
                  <p className="font-bold text-white">{note.userName}</p>
                  <p className="text-xs text-muted-foreground">{new Date(note.timestamp).toLocaleString()}</p>
                  <p className="mt-1">{note.note}</p>
                </div>
              ))}
              {(values.activityLogs || []).slice(0, 5).map((log) => (
                <div key={log.id} className="rounded-md border border-cyan-300/10 px-3 py-2 text-xs text-muted-foreground">
                  <p><span className="font-bold text-foreground">{log.userName}</span> - {log.description}</p>
                  <p>{new Date(log.timestamp).toLocaleString()}{log.field ? ` - ${log.field}: ${log.oldValue || "-"} -> ${log.newValue || "-"}` : ""}</p>
                </div>
              ))}
              {(values.approvalHistory || []).slice(0, 4).map((event) => (
                <div key={event.id} className="rounded-md border border-emerald-300/15 px-3 py-2 text-xs text-muted-foreground">
                  <p><span className="font-bold text-foreground">{event.userName}</span> - {event.action}</p>
                  <p>{new Date(event.timestamp).toLocaleString()} - {event.fromStatus} {"->"} {event.toStatus}</p>
                  {event.comment && <p className="mt-1">{event.comment}</p>}
                </div>
              ))}
              {!values.activityLogs?.length && <p className="text-sm text-muted-foreground">No activity logged yet.</p>}
            </div>
          </Card>

          <Card className="sticky top-24 w-full max-w-full overflow-hidden p-3 sm:p-4">
            <div className="mb-3 flex items-center justify-between gap-3">
              <div>
                <h2 className="text-lg font-black text-white">Print preview</h2>
                <p className="text-xs text-muted-foreground">Scaled to fit the screen.</p>
              </div>
              <Button type="button" onClick={print}><Printer size={16} /> Print</Button>
            </div>
            <PrintPreview lesson={printableLesson} zoom={0.34} />
          </Card>
        </aside>
      </div>

      <div aria-hidden className="fixed left-[-12000px] top-0">
        <LessonPrint lesson={printableLesson} ref={printRef} />
      </div>

      <Dialog open={preview} title={`${planType === "daily" ? "Daily" : "Weekly"} Lesson Plan Preview`} onClose={() => setPreview(false)} size="preview">
        <div className="mb-4 flex justify-end gap-2">
          <Button onClick={print}><Printer size={17} /> Print</Button>
          <Button variant="outline" disabled={Boolean(exporting)} onClick={() => exportDocument("pdf")}>{exporting === "pdf" ? <Loader2 className="animate-spin" size={17} /> : <FileDown size={17} />} {exporting === "pdf" ? "PDF..." : "PDF"}</Button>
          <Button variant="outline" disabled={Boolean(exporting)} onClick={() => exportDocument("docx")}>{exporting === "docx" ? <Loader2 className="animate-spin" size={17} /> : <Download size={17} />} {exporting === "docx" ? "DOCX..." : "DOCX"}</Button>
        </div>
        <PrintPreview lesson={printableLesson} zoom={0.68} fitWindow />
      </Dialog>
    </div>
  );
};

const toPrintableLesson = (lesson: LessonPlan): LessonPlan => {
  const subject = lesson.subject || "";
  const gradeClass = lesson.gradeClass || "";
  const chapter = sanitizeChapter(lesson.chapter);
  const support = createAutomaticLessonSupport(subject, gradeClass, chapter);
  const weeklyPlan = normalizeEditableWeeklyPlan(lesson.weeklyPlan, subject, gradeClass, chapter);
  const learningObjectives = hasFilledItems(lesson.learningObjectives)
    ? lesson.learningObjectives
    : support.learningObjectives.map((value, index) => ({ id: `auto-objective-${index + 1}`, value }));
  const learningOutcomes = hasFilledItems(lesson.learningOutcomes)
    ? lesson.learningOutcomes
    : support.learningOutcomes.map((value, index) => ({ id: `auto-outcome-${index + 1}`, value }));
  const successCriteria = hasFilledItems(lesson.successCriteria)
    ? lesson.successCriteria
    : support.successCriteria.map((value, index) => ({ id: `auto-criteria-${index + 1}`, value }));

  return {
    ...lesson,
    schoolName: schoolDisplayName,
    planType: lesson.planType || "weekly",
    subject,
    gradeClass,
    chapter,
    weekStartDate: lesson.weekStartDate || getWeekStartFromDate(lesson.date),
    weekEndDate: lesson.weekEndDate || addBusinessWeekEnd(lesson.weekStartDate || getWeekStartFromDate(lesson.date)),
    topic: buildAutomaticTitle({ ...lesson, subject, gradeClass, chapter, planType: lesson.planType || "weekly" }),
    weeklyPlan: (lesson.planType || "weekly") === "daily" ? weeklyPlan.map((day, index) => (index === 0 ? day : weeklyPlan[index])) : weeklyPlan,
    learningObjectives,
    learningOutcomes,
    successCriteria,
    vocabulary: hasFilledItems(lesson.vocabulary) ? lesson.vocabulary : [{ id: "vocabulary", value: support.vocabulary }],
    materialsResources: hasFilledItems(lesson.materialsResources) ? lesson.materialsResources : [{ id: "materials", value: support.materialsResources }],
    differentiation: mergeFilled({
      strugglingLearners: "",
      eslSupport: "",
      giftedLearners: "",
      specialNeeds: "",
      inclusiveStrategies: support.differentiation
    }, lesson.differentiation || {}),
    assessment: mergeFilled({
      diagnostic: "",
      formative: "",
      summative: "",
      observationChecklist: "",
      rubric: "",
      exitTicket: "",
      teacherComments: support.assessment
    }, lesson.assessment || {}),
    reflection: mergeFilled({
      whatWentWell: "",
      challenges: "",
      improvements: "",
      followUpActivities: "",
      teacherNotes: support.reflection
    }, lesson.reflection || {})
  };
};

const normalizeEditableWeeklyPlan = (weeklyPlan: Partial<WeeklyPlanDay>[] | undefined, subject = "", gradeClass = "", chapter = ""): WeeklyPlanDay[] => {
  const base = createFlexibleWeeklyPlan(subject, gradeClass, chapter);

  return base.map((day, index) => ({
    ...day,
    ...(weeklyPlan?.[index] || {}),
    day: weeklyPlan?.[index]?.day || day.day,
    lesson: weeklyPlan?.[index]?.lesson ?? day.lesson,
    objectives: weeklyPlan?.[index]?.objectives ?? day.objectives,
    introduction: weeklyPlan?.[index]?.introduction ?? day.introduction ?? "",
    presentation: weeklyPlan?.[index]?.presentation ?? day.presentation,
    guidedPractice: weeklyPlan?.[index]?.guidedPractice ?? day.guidedPractice,
    exitTicket: weeklyPlan?.[index]?.exitTicket ?? day.exitTicket,
    assessment: weeklyPlan?.[index]?.assessment ?? day.assessment,
    homework: weeklyPlan?.[index]?.homework ?? day.homework
  }));
};

const createLessonBasedSuggestion = (lesson: Partial<LessonPlan>, day: Partial<WeeklyPlanDay> | undefined, index: number) => {
  const lessonTitle = day?.lesson?.trim() || lesson.subtopic?.trim() || sanitizeChapter(lesson.chapter) || lesson.topic || "";
  const generated = createSuggestedWeeklyDay({
    ...lesson,
    chapter: lessonTitle,
    topic: lessonTitle,
    subtopic: lessonTitle
  }, index);

  return {
    ...generated,
    day: day?.day || generated.day,
    lesson: day?.lesson?.trim() || generated.lesson
  };
};

const buildAutomaticTitle = (lesson: Partial<LessonPlan>) => {
  const subject = sanitizeTitlePart(lesson.subject);
  const gradeClass = sanitizeTitlePart(lesson.gradeClass);
  const chapter = sanitizeChapter(lesson.chapter);
  const parts = [
    lesson.planType === "daily" ? "Daily Lesson Plan" : "Weekly Lesson Plan",
    subject,
    gradeClass,
    lesson.planType === "daily" ? lesson.date || "" : lesson.week ? `Week ${lesson.week}` : "",
    chapter
  ]
    .map((part) => part?.trim())
    .filter(Boolean);

  return parts.length > 1 ? parts.join(" - ") : "Weekly Lesson Plan";
};

const sanitizeChapter = (value?: string) => {
  const text = value?.trim() || "";
  return stripPlanTitle(text);
};

const sanitizeTitlePart = (value?: string) => {
  const text = value?.trim() || "";
  return stripPlanTitle(text);
};

const normalizeSchoolYear = (value?: string) => value?.replace(/\s+/g, "") || "";

const formatWeekRangeLabel = (week?: string, start?: string, end?: string) => {
  const weekLabel = week?.toLowerCase().startsWith("week") ? week : `Week ${week || "1"}`;
  return `${weekLabel} from ${formatDateLabel(start)} to ${formatDateLabel(end)}`;
};

const formatDateLabel = (value?: string) => {
  if (!value) return "...";
  const date = new Date(`${value}T00:00:00`);
  if (Number.isNaN(date.getTime())) return "...";
  return new Intl.DateTimeFormat("en-US", { month: "long", day: "numeric", year: "numeric" }).format(date);
};

const getWeekStartFromDate = (value?: string) => {
  const date = value ? new Date(`${value}T00:00:00`) : new Date();
  if (Number.isNaN(date.getTime())) return "";
  date.setDate(date.getDate() - ((date.getDay() + 6) % 7));
  return toIsoDate(date);
};

const addBusinessWeekEnd = (value?: string) => {
  if (!value) return "";
  const date = new Date(`${value}T00:00:00`);
  if (Number.isNaN(date.getTime())) return "";
  date.setDate(date.getDate() + 4);
  return toIsoDate(date);
};

const addDaysToIso = (value: string | undefined, days: number) => {
  const date = value ? new Date(`${value}T00:00:00`) : new Date();
  if (Number.isNaN(date.getTime())) return "";
  date.setDate(date.getDate() + days);
  return toIsoDate(date);
};

const getBusinessDayIndex = (value?: string) => {
  const date = value ? new Date(`${value}T00:00:00`) : new Date();
  if (Number.isNaN(date.getTime())) return 0;
  return Math.min(4, Math.max(0, (date.getDay() + 6) % 7));
};

const toIsoDate = (date: Date) => {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
};

const createDailyObjective = (lessonTitle = "", subject = "", gradeClass = "", dayIndex = 0) => {
  const lesson = lessonTitle.trim() || "the lesson";
  const subjectLabel = subject.trim() || "the subject";
  const gradeLabel = gradeClass.trim() || "the class";
  const actionTurns = [
    "identify, describe, and explain",
    "classify, compare, and justify",
    "construct, solve, and apply",
    "apply, defend, and create",
    "evaluate, correct, and demonstrate mastery of"
  ];
  const actions = actionTurns[dayIndex % actionTurns.length];

  return `By the end of the lesson, learners in ${gradeLabel} should be able to ${actions} ${lesson} in ${subjectLabel}.`;
};

const isGenericObjective = (objective: string, gradeClass = "", chapter = "") => {
  const text = objective.trim();
  if (!text) return true;

  return (
    text.includes("the selected unit") ||
    text.includes("the class") ||
    text === `By the end of the lesson, learners in ${gradeClass || "the class"} should be able to understand and apply the key ideas from ${chapter || "the selected unit"}.`
  );
};

const hasOldSetupText = (value: string, setup: { subject: string; gradeClass: string; chapter: string }) => {
  const text = value.toLowerCase();
  return [setup.subject, setup.gradeClass, setup.chapter]
    .map((item) => item.trim().toLowerCase())
    .filter((item) => item.length > 2)
    .some((item) => text.includes(item));
};

const hasActivityDurations = (day: WeeklyPlanDay) =>
  Boolean(day.activityDurations && Object.values(day.activityDurations).some((value) => typeof value === "number"));

const hasFilledItems = (items?: { value?: string }[]) => Boolean(items?.some((item) => item.value?.trim()));
const unique = (values: string[]) => Array.from(new Set(values.map((value) => value.trim()).filter(Boolean))).sort((a, b) => a.localeCompare(b));

const mergeFilled = <T extends Record<string, string>>(base: T, overrides: Partial<T>): T => {
  const next = { ...base };

  Object.entries(overrides).forEach(([key, value]) => {
    if (typeof value === "string" && value.trim()) {
      next[key as keyof T] = value as T[keyof T];
    }
  });

  return next;
};

const LockedSchool = () => (
  <div className="space-y-1">
    <Label>School</Label>
    <div className="flex h-10 items-center gap-2 rounded-md border border-border bg-input px-3 text-sm font-bold text-foreground shadow-sm dark:border-cyan-300/20 dark:bg-[#030d14]/85 dark:text-[#f8fdff]">
      <img src={schoolImage} alt="KCS logo" className="h-6 w-6 rounded-sm object-contain bg-white" />
      <span className="truncate">{schoolDisplayName}</span>
    </div>
  </div>
);

const Field = ({ label, children, error }: { label: string; children: React.ReactNode; error?: string }) => (
  <div className="min-w-0 space-y-1">
    <Label>{label}</Label>
    {children}
    {error && <p className="text-xs font-semibold text-destructive">{error}</p>}
  </div>
);

const WeeklyField = ({
  label,
  locked,
  onRegenerate,
  onToggleLock,
  children
}: {
  label: string;
  locked: boolean;
  onRegenerate: () => void;
  onToggleLock: () => void;
  children: React.ReactNode;
}) => (
  <div className="min-w-0 space-y-1">
    <div className="flex items-center justify-between gap-2">
      <Label>{label}</Label>
      <div className="flex gap-1">
        <Button type="button" variant="ghost" className="h-7 px-2 text-[11px]" onClick={onRegenerate}>Restore suggestion</Button>
        <Button type="button" variant="ghost" className="h-7 px-2 text-[11px]" onClick={onToggleLock}>{locked ? "Unlock" : "Lock"}</Button>
      </div>
    </div>
    {children}
  </div>
);

const rowLabel = (key: WeeklyEditableKey) => key.replace(/([A-Z])/g, " $1").toLowerCase();

const statusLabel = (status: LessonPlan["status"]) => ({
  draft: "Draft",
  submitted: "Submitted",
  "under-review": "Under Review",
  "revision-requested": "Revision Requested",
  approved: "Approved",
  "final-approved": "Final Approved",
  rejected: "Rejected",
  archived: "Archived",
  published: "Published"
})[status];

const getTeacherFeedback = (lesson: LessonPlan) => {
  if (!["approved", "final-approved", "rejected", "revision-requested"].includes(lesson.status)) return null;
  const source: { note?: string; comment?: string; userName: string; timestamp: string } | undefined =
    lesson.status === "revision-requested"
      ? lesson.revisionRequests?.[0]
      : lesson.reviewerComments?.[0] || lesson.approvalHistory?.[0];
  if (!source) return null;
  return {
    title: lesson.status === "revision-requested" ? "Revision requested" : lesson.status === "rejected" ? "Lesson plan rejected" : "Lesson plan approved",
    message: source.note || source.comment || "No reviewer comment was written.",
    userName: source.userName,
    timestamp: source.timestamp
  };
};

const PrintPreview = ({ lesson, zoom, fitWindow = false }: { lesson: LessonPlan; zoom: number; fitWindow?: boolean }) => {
  const shellRef = useRef<HTMLDivElement>(null);
  const [shellSize, setShellSize] = useState({ width: 0, height: 0 });

  useEffect(() => {
    const shell = shellRef.current;
    if (!shell) return;

    const updateSize = () => {
      const rect = shell.getBoundingClientRect();
      setShellSize({ width: rect.width, height: rect.height });
    };
    updateSize();

    if (typeof ResizeObserver === "undefined") {
      window.addEventListener("resize", updateSize);
      return () => window.removeEventListener("resize", updateSize);
    }

    const observer = new ResizeObserver(updateSize);
    observer.observe(shell);
    return () => observer.disconnect();
  }, []);

  const availableWidth = Math.max(0, shellSize.width - (fitWindow ? 24 : 20));
  const availableHeight = Math.max(0, shellSize.height - (fitWindow ? 24 : 20));
  const widthScale = availableWidth ? availableWidth / 1123 : zoom;
  const heightScale = availableHeight ? availableHeight / 794 : zoom;
  const responsiveScale = fitWindow ? Math.min(widthScale, heightScale) : widthScale;
  const viewportZoom = Math.max(0.18, Math.min(fitWindow ? 1 : zoom, responsiveScale || zoom));
  const width = `${297 * viewportZoom}mm`;
  const height = `${210 * viewportZoom}mm`;
  const style = { "--preview-scale": viewportZoom } as CSSProperties;

  return (
    <div ref={shellRef} className={fitWindow ? "print-preview-shell flex h-[80dvh] max-h-[80dvh] min-h-[420px] max-w-full items-center justify-center overflow-auto rounded-lg border border-cyan-300/15 bg-slate-950/70 p-2 sm:p-3" : "print-preview-shell flex max-h-[72dvh] max-w-full items-start justify-center overflow-auto rounded-lg border border-cyan-300/15 bg-slate-950/70 p-2 sm:p-3 lg:max-h-[62dvh]"}>
      <div style={{ width, height }} className="max-w-full shrink-0 overflow-hidden">
        <div className="origin-top-left scale-[var(--preview-scale)]" style={{ ...style, width: "297mm", height: "210mm" }}>
          <LessonPrint lesson={lesson} />
        </div>
      </div>
    </div>
  );
};

const stripPlanTitle = (value?: string) => {
  const text = value?.trim() || "";
  const parts = text.split(/\s+-\s+/).map((part) => part.trim()).filter(Boolean);
  if (/^(daily|weekly)\s+lesson\s+plan$/i.test(parts[0] || "")) return parts[parts.length - 1] || "";
  return /^(daily|weekly)\s+lesson\s+plan/i.test(text) ? "" : text;
};
