import { useEffect, useState } from "react";
import { Download } from "lucide-react";
import { useI18n } from "../i18n";
type InstallPromptEvent = Event & { prompt: () => Promise<void>; userChoice: Promise<{ outcome: "accepted" | "dismissed" }> };
const INSTALL_STATE_KEY = "edupay-pwa-installed-v1";
const isStandalone = () => window.matchMedia?.("(display-mode: standalone)").matches || (navigator as Navigator & { standalone?: boolean }).standalone === true || localStorage.getItem(INSTALL_STATE_KEY) === "1";
export default function InstallAppButton() {
  const { lang } = useI18n(); const L = (fr: string, en: string) => lang === "fr" ? fr : en;
  const [promptEvent, setPromptEvent] = useState<InstallPromptEvent | null>(null); const [installed, setInstalled] = useState(isStandalone);
  useEffect(() => { const displayMode = window.matchMedia("(display-mode: standalone)"); const capture = (event: Event) => { event.preventDefault(); setPromptEvent(event as InstallPromptEvent); }; const syncInstalledState = () => setInstalled(isStandalone()); const done = () => { localStorage.setItem(INSTALL_STATE_KEY, "1"); setInstalled(true); }; window.addEventListener("beforeinstallprompt", capture); window.addEventListener("appinstalled", done); displayMode.addEventListener?.("change", syncInstalledState); return () => { window.removeEventListener("beforeinstallprompt", capture); window.removeEventListener("appinstalled", done); displayMode.removeEventListener?.("change", syncInstalledState); }; }, []);
  if (installed) return null;
  const install = async () => { if (promptEvent) { await promptEvent.prompt(); const choice = await promptEvent.userChoice; if (choice.outcome === "accepted") { localStorage.setItem(INSTALL_STATE_KEY, "1"); setInstalled(true); } setPromptEvent(null); return; } alert(L("Installation disponible. Chrome ou Edge : utilisez Installer dans la barre d’adresse ou le menu. iPhone et iPad : Partager puis Sur l’écran d’accueil. Safari macOS : Fichier puis Ajouter au Dock.", "Installation is available. In Chrome or Edge, select Install in the address bar or menu. On iPhone and iPad, select Share, then Add to Home Screen. In Safari on macOS, select File, then Add to Dock.")); };
  return <button type="button" onClick={() => void install()} aria-label={L("Installer EduPay", "Install EduPay")} title={L("Installer EduPay", "Install EduPay")} style={{ position: "fixed", right: "max(1rem, env(safe-area-inset-right))", bottom: "max(1rem, env(safe-area-inset-bottom))", zIndex: 2147483647, minHeight: "44px", display: "inline-flex", alignItems: "center", gap: ".5rem", border: "1px solid #7de8ff", borderRadius: "999px", padding: ".65rem .95rem", background: "linear-gradient(135deg, #14b8de, #0786ad)", color: "#03131d", fontWeight: 800, boxShadow: "0 12px 30px rgba(5, 16, 24, .38)", cursor: "pointer", visibility: "visible", opacity: 1 }}><Download size={17} aria-hidden="true" /><span>{L("Installer EduPay", "Install EduPay")}</span></button>;
}
