import {useEffect,useState,type FormEvent} from 'react'
import {BookOpenCheck,CheckCircle2,ClipboardList,Plus,Send} from 'lucide-react'
import PortalSidebar from '@/components/layout/PortalSidebar'
import {electivesAPI} from '@/services/api'
import {useAuthStore} from '@/store/authStore'
type O={id:string;code:string;name:string;description:string;eligibleGrades:string[];capacity:number;status:string;teacher?:any;_count?:any}
type C={id:string;title:string;academicYear:string;semester:number;status:string;offerings:O[];_count:any}
const grades=['Grade 9','Grade 10','Grade 11','Grade 12']
const field='w-full min-w-0 rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-900 dark:border-kcs-blue-700 dark:bg-kcs-blue-950 dark:text-white'
const tn=(t:any)=>t?[t.lastName,t.middleName,t.firstName].filter(Boolean).join(' '):'À attribuer'
export default function ElectivesPage(){
 const {user}=useAuthStore(),admin=user?.role==='admin'&&user.id!=='configured-superadmin',teacher=user?.role==='teacher',student=user?.role==='student'
 const [data,setData]=useState<any>({cycles:[]}),[teachers,setTeachers]=useState<any[]>([]),[selected,setSelected]=useState(''),[choices,setChoices]=useState<string[]>(Array(6).fill('')),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[report,setReport]=useState<any>(null)
 const [cf,setCf]=useState({title:'Sélection des cours électifs',academicYear:'2026-2027',semester:1,eligibleGrades:grades})
 const [of,setOf]=useState({code:'',name:'',description:'',eligibleGrades:grades,capacity:24,teacherUserId:''})
 const load=async()=>{const r=await electivesAPI.list(),d=r.data.data||{cycles:[]};setData(d);if(!selected&&d.cycles?.[0])setSelected(d.cycles[0].id);if(student&&d.choices){const x=[...d.choices].sort((a:any,b:any)=>a.rank-b.rank).map((a:any)=>a.offeringId);setChoices([...x,...Array(6).fill('')].slice(0,6))}}
 useEffect(()=>{void load();if(admin)electivesAPI.teachers().then(r=>setTeachers(r.data.data||[]))},[])
 const cycles:C[]=data.cycles||[],cycle=cycles.find(c=>c.id===selected)||cycles[0]
 const approved=cycle?.offerings.filter(o=>o.status==='APPROVED'&&(!data.grade||o.eligibleGrades.includes(data.grade)))||[]
 const act=async(fn:()=>Promise<any>)=>{setBusy(true);setMessage('');try{const r=await fn();setMessage(r.data.message);await load();return r}catch(e:any){setMessage(e?.response?.data?.message||'Opération impossible')}finally{setBusy(false)}}
 const add=(e:FormEvent)=>{e.preventDefault();if(cycle)void act(()=>electivesAPI.addOffering(cycle.id,{...of,teacherUserId:of.teacherUserId||null}))}
 const toggle=(g:string,current:string[],set:(v:string[])=>void)=>set(current.includes(g)?current.filter(x=>x!==g):[...current,g])
 return <div className="portal-shell flex"><PortalSidebar/><main className="min-w-0 flex-1 overflow-y-auto bg-slate-50 p-4 pt-20 dark:bg-kcs-blue-950 lg:p-8 lg:pt-8"><div className="mx-auto max-w-7xl space-y-6">
 <header className="rounded-3xl bg-gradient-to-br from-kcs-blue-950 to-kcs-blue-600 p-6 text-white"><BookOpenCheck className="text-kcs-gold-400"/><h1 className="mt-2 text-3xl font-black">Cours électifs</h1><p className="mt-2 text-blue-100">Six choix distincts par élève · capacité maximale stricte de 24 élèves par cours · Grade 9 à Grade 12.</p></header>
 {message&&<p className="rounded-xl bg-kcs-gold-50 p-4 font-semibold text-kcs-blue-950">{message}</p>}
 {admin&&<form onSubmit={e=>{e.preventDefault();void act(()=>electivesAPI.createCycle(cf))}} className="grid gap-3 rounded-3xl bg-white p-5 shadow dark:bg-kcs-blue-900 sm:grid-cols-2 lg:grid-cols-4"><h2 className="col-span-full text-xl font-black dark:text-white">1. Créer le semestre</h2><input className={field} value={cf.title} onChange={e=>setCf({...cf,title:e.target.value})}/><input className={field} value={cf.academicYear} onChange={e=>setCf({...cf,academicYear:e.target.value})}/><select className={field} value={cf.semester} onChange={e=>setCf({...cf,semester:Number(e.target.value)})}><option value={1}>Semestre 1</option><option value={2}>Semestre 2</option></select><button disabled={busy} className="rounded-xl bg-kcs-blue-700 font-bold text-white"><Plus className="inline" size={16}/> Créer</button><div className="col-span-full flex flex-wrap gap-2">{grades.map(g=><label key={g} className="rounded-full border px-3 py-2 text-sm dark:text-white"><input type="checkbox" checked={cf.eligibleGrades.includes(g)} onChange={()=>toggle(g,cf.eligibleGrades,v=>setCf({...cf,eligibleGrades:v}))}/> {g}</label>)}</div></form>}
 {cycle&&<><section className="rounded-3xl bg-white p-5 shadow dark:bg-kcs-blue-900 dark:text-white"><select className={field} value={cycle.id} onChange={e=>{setSelected(e.target.value);setReport(null)}}>{cycles.map(c=><option key={c.id} value={c.id}>{c.title} · {c.academicYear} S{c.semester}</option>)}</select><p className="mt-3 font-bold">Statut : {cycle.status} · {cycle.offerings.length} cours</p>{admin&&<div className="mt-4 flex flex-wrap gap-2"><button disabled={busy||cycle.status!=='DRAFT'} onClick={()=>void act(()=>electivesAPI.setStatus(cycle.id,'OPEN'))} className="rounded-xl bg-emerald-700 px-4 py-2 text-white disabled:opacity-40">Ouvrir</button><button disabled={busy||cycle.status!=='OPEN'} onClick={()=>void act(()=>electivesAPI.setStatus(cycle.id,'CLOSED'))} className="rounded-xl bg-amber-600 px-4 py-2 text-white disabled:opacity-40">Clôturer</button><button disabled={busy||!['CLOSED','ALLOCATED'].includes(cycle.status)} onClick={()=>void act(()=>electivesAPI.allocate(cycle.id))} className="rounded-xl bg-indigo-700 px-4 py-2 text-white disabled:opacity-40">Calculer les attributions</button><button disabled={busy||cycle.status!=='ALLOCATED'} onClick={()=>void act(()=>electivesAPI.publish(cycle.id))} className="rounded-xl bg-kcs-blue-950 px-4 py-2 text-white disabled:opacity-40">Publier</button><button onClick={()=>{setBusy(true);electivesAPI.report(cycle.id).then(r=>setReport(r.data.data)).finally(()=>setBusy(false))}} className="rounded-xl border px-4 py-2"><ClipboardList className="inline" size={16}/> Rapport final</button></div>}</section>
 {(admin||teacher)&&<form onSubmit={add} className="grid gap-3 rounded-3xl bg-white p-5 shadow dark:bg-kcs-blue-900 sm:grid-cols-2 lg:grid-cols-3"><h2 className="col-span-full text-xl font-black dark:text-white">{teacher?'Proposer un cours':'2. Construire le catalogue avec les enseignants'}</h2><input required className={field} placeholder="Code" value={of.code} onChange={e=>setOf({...of,code:e.target.value})}/><input required className={field} placeholder="Nom du cours" value={of.name} onChange={e=>setOf({...of,name:e.target.value})}/>{admin&&<select className={field} value={of.teacherUserId} onChange={e=>setOf({...of,teacherUserId:e.target.value})}><option value="">Enseignant à attribuer</option>{teachers.map(t=><option key={t.id} value={t.id}>{tn(t)}</option>)}</select>}<textarea required minLength={10} className={field+' min-h-24 sm:col-span-2 lg:col-span-3'} placeholder="Description, objectifs et prérequis" value={of.description} onChange={e=>setOf({...of,description:e.target.value})}/><div className="flex flex-wrap gap-2 sm:col-span-2">{grades.map(g=><label key={g} className="rounded-full border px-3 py-2 text-sm dark:text-white"><input type="checkbox" checked={of.eligibleGrades.includes(g)} onChange={()=>toggle(g,of.eligibleGrades,v=>setOf({...of,eligibleGrades:v}))}/> {g}</label>)}</div><input aria-label="Capacité" type="number" min={1} max={24} className={field} value={of.capacity} onChange={e=>setOf({...of,capacity:Number(e.target.value)})}/><button disabled={busy} className="rounded-xl bg-kcs-gold-500 p-3 font-black text-kcs-blue-950"><Send className="inline" size={16}/> {teacher?'Soumettre':'Ajouter'}</button></form>}
 <section className="rounded-3xl bg-white p-5 shadow dark:bg-kcs-blue-900 dark:text-white"><h2 className="text-xl font-black">Catalogue officiel</h2><div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{cycle.offerings.map(o=><article key={o.id} className="rounded-2xl border p-4"><div className="flex justify-between gap-2"><h3 className="font-black">{o.code} · {o.name}</h3><span className="text-xs">max {o.capacity}</span></div><p className="mt-2 text-sm text-slate-500 dark:text-slate-300">{o.description}</p><p className="mt-2 text-xs">{o.eligibleGrades.join(', ')} · {tn(o.teacher)} · {o.status}</p>{admin&&o.status==='PROPOSED'&&<button onClick={()=>void act(()=>electivesAPI.updateOffering(o.id,{status:'APPROVED'}))} className="mt-3 rounded-lg bg-emerald-700 px-3 py-2 text-xs text-white">Approuver la proposition</button>}</article>)}</div></section>
 {student&&data.eligible&&<section className="rounded-3xl bg-white p-5 shadow dark:bg-kcs-blue-900 dark:text-white"><h2 className="text-xl font-black">Mes six choix classés</h2>{cycle.status==='OPEN'?<div className="mt-4 grid gap-3 md:grid-cols-2">{choices.map((v,i)=><label key={i} className="text-sm font-bold">Préférence #{i+1}<select className={field+' mt-1'} value={v} onChange={e=>setChoices(choices.map((x,n)=>n===i?e.target.value:x))}><option value="">Choisir</option>{approved.filter(o=>!choices.includes(o.id)||o.id===v).map(o=><option key={o.id} value={o.id}>{o.code} · {o.name}</option>)}</select></label>)}<button disabled={busy||new Set(choices.filter(Boolean)).size!==6} onClick={()=>void act(()=>electivesAPI.submitChoices(cycle.id,choices))} className="rounded-xl bg-kcs-blue-700 p-3 font-bold text-white disabled:opacity-40 md:col-span-2"><CheckCircle2 className="inline"/> Enregistrer mes six choix</button></div>:<p className="mt-3 rounded-xl bg-slate-100 p-4 text-slate-700">La période de choix n’est pas ouverte.</p>}{data.allocations?.filter((a:any)=>a.cycleId===cycle.id).length>0&&<div className="mt-5"><h3 className="font-black">Liste finale publiée</h3>{data.allocations.filter((a:any)=>a.cycleId===cycle.id).map((a:any)=><p key={a.id} className="mt-2 rounded-xl border p-3">{a.offering.code} · {a.offering.name} · préférence #{a.preferenceRank}</p>)}</div>}</section>}
 {report&&admin&&<section className="rounded-3xl bg-white p-5 shadow dark:bg-kcs-blue-900 dark:text-white"><h2 className="text-xl font-black">Rapport final</h2><div className="mt-3 grid gap-3 sm:grid-cols-4">{Object.entries(report.summary).map(([k,v])=><div key={k} className="rounded-xl bg-slate-100 p-4 text-center text-slate-900"><b className="block text-2xl">{String(v)}</b>{k}</div>)}</div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[700px] text-sm"><thead><tr><th>Cours</th><th>Enseignant</th><th>Demandes</th><th>Attribués</th><th>Capacité</th></tr></thead><tbody>{report.offerings.map((o:any)=><tr key={o.id} className="border-t"><td className="p-2">{o.code} · {o.name}</td><td>{tn(o.teacher)}</td><td>{o._count.choices}</td><td>{o._count.allocations}</td><td>{o.capacity}</td></tr>)}</tbody></table></div></section>}</>}
 </div></main></div>
}
