import test from "node:test";import assert from "node:assert/strict";import { assertCommitAllowed,importFingerprint,rollbackDecision,runBatchTransactional,summarizeOperations,versionUnchanged } from "./ledger-policy.js";
test("successful commit requires READY, no errors and explicit confirmation",()=>{assert.doesNotThrow(()=>assertCommitAllowed({status:"READY",errors:0,confirmation:"CONFIRM AND IMPORT"}));assert.throws(()=>assertCommitAllowed({status:"READY",errors:1,confirmation:"CONFIRM AND IMPORT"}));assert.throws(()=>assertCommitAllowed({status:"READY",errors:0,confirmation:"yes"}))});
test("successful commit reports created updated merged and skipped",()=>{assert.deepEqual(summarizeOperations([{id:"1",action:"CREATE"},{id:"2",action:"UPDATE"},{id:"3",action:"MERGE"},{id:"4",action:"SKIP"}]),{created:1,updated:1,merged:1,skipped:1,failed:0})});
test("partial batch failure preserves prior committed batches only",async()=>{const committed:string[]=[];const result=await runBatchTransactional(["a","b","bad","d"],2,async batch=>{if(batch.includes("bad"))throw new Error("batch failed");committed.push(...batch)});assert.deepEqual(committed,["a","b"]);assert.deepEqual(result,{committed:2,failed:2,status:"PARTIAL"})});
test("created record rollback is allowed only for this job without critical data",()=>{assert.equal(rollbackDecision({operation:"CREATE",versionUnchanged:true,criticalDependents:false,createdByJob:true}).allowed,true);assert.equal(rollbackDecision({operation:"CREATE",versionUnchanged:true,criticalDependents:true,createdByJob:true}).reason,"CRITICAL_DEPENDENCIES");assert.equal(rollbackDecision({operation:"CREATE",versionUnchanged:true,criticalDependents:false,createdByJob:false}).reason,"PREEXISTING_ENTITY")});
test("updated records and relationships can be restored from ledger",()=>{assert.equal(rollbackDecision({operation:"UPDATE",versionUnchanged:true,criticalDependents:false,createdByJob:true}).allowed,true);assert.equal(rollbackDecision({operation:"CREATE_RELATION",versionUnchanged:true,criticalDependents:false,createdByJob:true}).allowed,true)});
test("rollback blocks an entity changed after import",()=>{assert.equal(versionUnchanged("2026-01-01T00:00:00.000Z","2026-01-01T00:00:00.000Z"),true);assert.equal(rollbackDecision({operation:"UPDATE",versionUnchanged:false,criticalDependents:false,createdByJob:true}).reason,"MODIFIED_AFTER_IMPORT")});
test("same file source and entity has a stable idempotence key",()=>{const first=importFingerprint("hash","QUICKSCHOOL","STUDENT");const second=importFingerprint("hash","QUICKSCHOOL","STUDENT");assert.equal(first,second);assert.notEqual(first,importFingerprint("hash","GENERIC","STUDENT"))});
test("duplicate prevention treats one identity as update instead of create",()=>{const operations=summarizeOperations([{id:"existing-user",action:"UPDATE"}]);assert.equal(operations.created,0);assert.equal(operations.updated,1)});
