ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "liveStreamEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "liveStreamUrl" TEXT;
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "liveStreamPlatform" TEXT;
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "liveStreamStatus" TEXT NOT NULL DEFAULT 'scheduled';
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "liveStreamStartsAt" TIMESTAMP(3);
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "replayUrl" TEXT;
