import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, Download, FileSpreadsheet, RotateCcw, Upload } from "lucide-react";
import PortalSidebar from "@/components/layout/PortalSidebar";
import { dataMigrationAPI } from "@/services/api";
type Mapping={sourceColumn:string;targetField:string;detectedType:string;required:boolean;transformation:string;confidence:number;status:string};
type Row={row:number;normalized:Record<string,string>;status:string;action:string};
type Report={total:number;valid:number;warning:number;error:number;newRecords:number;matched:number;possibleDuplicates:number;updateCandidates:number;rows:Row[]};
type Result={jobId:string;status:string;created:number;updated:number;merged:number;skipped:number;failed:number;idempotent?:boolean};
const fields=["firstName","middleName","lastName","dateOfBirth","gender","phone","personalEmail","institutionalEmail","studentId","employeeId","grade","class","parent","guardian","father","mother","address","orbitId"];
const downloadBlob=async(request:Promise<any>,name:string)=>{const response=await request;const url=URL.createObjectURL(response.data);const link=document.createElement("a");link.href=url;link.download=name;link.click();URL.revokeObjectURL(url)};
const card="rounded-2xl bg-white p-5 shadow-sm dark:bg-kcs-blue-900/50";
const initialEntityType=()=>{const entity=new URLSearchParams(window.location.search).get("entity")?.toUpperCase();return ["STUDENT","PARENT","TEACHER","STAFF","CLASS","ACADEMIC_DIRECTORY"].includes(entity||"")?entity!:"STUDENT"};
export default function DataMigrationCenter(){
 const[file,setFile]=useState<File|null>(null),[entityType,setEntityType]=useState(initialEntityType),[sourceSystem,setSourceSystem]=useState("QUICKSCHOOL"),[mapping,setMapping]=useState<Mapping[]>([]),[report,setReport]=useState<Report|null>(null),[jobId,setJobId]=useState(""),[history,setHistory]=useState<any[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[confirmText,setConfirmText]=useState(""),[rollbackText,setRollbackText]=useState(""),[result,setResult]=useState<Result|null>(null),[rollbackResult,setRollbackResult]=useState<any>(null);
 const loadHistory=()=>dataMigrationAPI.jobs().then(r=>setHistory(r.data.data)).catch(()=>setHistory([]));useEffect(()=>{void loadHistory()},[]);
 const preview=async()=>{if(!file)return;setBusy(true);setError("");setResult(null);try{const form=new FormData();form.append("file",file);form.append("entityType",entityType);form.append("sourceSystem",sourceSystem);if(mapping.length)form.append("mapping",JSON.stringify(mapping));const response=await dataMigrationAPI.preview(form);setMapping(response.data.data.mapping);setReport(response.data.data.report);setJobId(response.data.data.jobId);setConfirmText("");void loadHistory()}catch(e:any){setError(e?.response?.data?.message||"Import preview failed")}finally{setBusy(false)}};
 const commit=async()=>{setBusy(true);setError("");try{const response=await dataMigrationAPI.confirm(jobId,{confirmation:confirmText});setResult(response.data.data);setRollbackResult(null);void loadHistory()}catch(e:any){setError(e?.response?.data?.message||"Import commit failed")}finally{setBusy(false)}};
 const rollback=async()=>{setBusy(true);setError("");try{const response=await dataMigrationAPI.rollback(jobId,rollbackText);setRollbackResult(response.data.data);void loadHistory()}catch(e:any){setError(e?.response?.data?.message||"Rollback failed")}finally{setBusy(false)}};
 const stats=useMemo(()=>report?[["TOTAL",report.total],["VALID",report.valid],["WARNING",report.warning],["ERROR",report.error],["NEW",report.newRecords],["MATCHED",report.matched],["POSSIBLE DUPLICATES",report.possibleDuplicates],["UPDATE CANDIDATES",report.updateCandidates]]:[],[report]);
 const confirmation=useMemo(()=>report?{newRecords:report.rows.filter(r=>r.action==="IMPORT").length,updates:report.rows.filter(r=>r.action==="UPDATE").length,merges:report.rows.filter(r=>r.action==="MERGE").length,skips:report.rows.filter(r=>r.action==="SKIP"||r.action==="REVIEW").length,warnings:report.warning,errors:report.error}:null,[report]);
 return <div className="portal-shell flex"><PortalSidebar/><main className="min-h-screen flex-1 bg-gray-50 p-4 dark:bg-kcs-blue-950 sm:p-6">
  <header className="mb-6"><p className="text-xs font-bold uppercase tracking-[.18em] text-kcs-gold-600">Super Administration · secure migration</p><h1 className="font-display text-3xl font-bold text-kcs-blue-900 dark:text-white">Data Migration Center</h1><p className="mt-2 text-sm text-gray-600 dark:text-gray-300">Upload, map, validate and dry-run before an explicitly confirmed transactional import.</p></header>
  {error&&<p className="mb-4 rounded-xl bg-red-50 p-3 text-red-700"><AlertTriangle className="mr-2 inline" size={18}/>{error}</p>}
  <section className={card}><div className="grid gap-4 md:grid-cols-4"><label className="text-sm font-semibold">Entity<select value={entityType} onChange={e=>{setEntityType(e.target.value);setMapping([]);setReport(null)}} className="mt-2 w-full rounded-xl border p-3 dark:bg-kcs-blue-900">{['STUDENT','PARENT','TEACHER','STAFF','CLASS','ACADEMIC_DIRECTORY'].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-sm font-semibold">Source<select value={sourceSystem} onChange={e=>setSourceSystem(e.target.value)} className="mt-2 w-full rounded-xl border p-3 dark:bg-kcs-blue-900"><option>QUICKSCHOOL</option><option>GENERIC</option><option>GOOGLE_SHEETS_EXPORT</option></select></label><label className="text-sm font-semibold md:col-span-2">CSV, TSV, XLSX, XLS or JSON<input type="file" accept=".csv,.tsv,.xlsx,.xls,.json" onChange={e=>{setFile(e.target.files?.[0]||null);setMapping([]);setReport(null)}} className="mt-2 block w-full rounded-xl border p-2"/></label></div><div className="mt-4 flex flex-wrap gap-2"><button disabled={!file||busy} onClick={preview} className="rounded-xl bg-kcs-blue-700 px-4 py-2.5 font-semibold text-white disabled:opacity-50"><Upload className="mr-2 inline" size={17}/>{mapping.length?'Re-run dry run':'Analyze file'}</button>{['students','parents','teachers','staff'].map(x=><button key={x} type="button" onClick={()=>void downloadBlob(dataMigrationAPI.template(x),`KCS-${x}-import-template.xlsx`)} className="rounded-xl border px-3 py-2 text-sm font-semibold"><Download className="mr-1 inline" size={15}/>{x}</button>)}</div></section>
  {mapping.length>0&&<section className={`${card} mt-6 overflow-x-auto`}><h2 className="mb-4 text-xl font-bold">Column Mapping Wizard</h2><table className="w-full text-left text-sm"><thead><tr>{['SOURCE COLUMN','TARGET FIELD','TYPE','REQUIRED','TRANSFORMATION','STATUS'].map(h=><th key={h} className="border-b p-2 text-xs">{h}</th>)}</tr></thead><tbody>{mapping.map((m,i)=><tr key={m.sourceColumn}><td className="p-2 font-semibold">{m.sourceColumn}</td><td className="p-2"><select value={m.targetField} onChange={e=>setMapping(v=>v.map((x,j)=>j===i?{...x,targetField:e.target.value,status:'CONFIRMED'}:x))} className="rounded-lg border p-2 dark:bg-kcs-blue-900">{fields.map(f=><option key={f}>{f}</option>)}</select></td><td>{m.detectedType}</td><td>{m.required?'Yes':'No'}</td><td>{m.transformation}</td><td>{m.status} {Math.round(m.confidence*100)}%</td></tr>)}</tbody></table></section>}
  {report&&<><section className="mt-6 grid grid-cols-2 gap-3 lg:grid-cols-4">{stats.map(([label,value])=><div key={label} className={card}><p className="text-xs font-bold text-gray-500">{label}</p><p className="text-2xl font-bold text-kcs-blue-800 dark:text-white">{value}</p></div>)}</section><section className={`${card} mt-6 overflow-x-auto`}><div className="flex justify-between"><h2 className="text-xl font-bold">Dry-run preview</h2>{jobId&&<button onClick={()=>void downloadBlob(dataMigrationAPI.errorReport(jobId),`import-errors-${jobId}.csv`)} className="text-sm font-semibold text-kcs-blue-700"><Download className="inline" size={16}/> Error report</button>}</div><table className="mt-4 w-full text-left text-sm"><thead><tr>{['Row','Name','Email','Phone','Class','Status','Action'].map(h=><th key={h} className="border-b p-2">{h}</th>)}</tr></thead><tbody>{report.rows.slice(0,200).map(r=><tr key={r.row}><td className="p-2">{r.row}</td><td>{r.normalized.firstName} {r.normalized.lastName}</td><td>{r.normalized.institutionalEmail||r.normalized.personalEmail}</td><td>{r.normalized.phone}</td><td>{r.normalized.class||r.normalized.grade}</td><td>{r.status}</td><td>{r.action}</td></tr>)}</tbody></table></section></>}
  {confirmation&&!result&&<section className={`${card} mt-6 border-2 ${confirmation.errors?'border-red-300':'border-amber-300'}`}><h2 className="text-xl font-bold">Final import confirmation</h2><div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-6">{Object.entries(confirmation).map(([k,v])=><div key={k} className="rounded-xl bg-gray-50 p-3 dark:bg-kcs-blue-950"><p className="text-xs uppercase text-gray-500">{k}</p><b>{v}</b></div>)}</div><p className="mt-4 text-sm">Type <b>CONFIRM AND IMPORT</b>. Invitations remain off.</p><div className="mt-3 flex gap-3"><input value={confirmText} onChange={e=>setConfirmText(e.target.value)} className="flex-1 rounded-xl border p-3 dark:bg-kcs-blue-950"/><button disabled={busy||confirmation.errors>0||confirmText!=="CONFIRM AND IMPORT"} onClick={commit} className="rounded-xl bg-red-700 px-5 py-3 font-bold text-white disabled:opacity-40">Confirm and import</button></div></section>}
  {result&&<section className={`${card} mt-6 border-2 border-emerald-300`}><h2 className="text-xl font-bold">Import result · {result.status}</h2><div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-5">{['created','updated','merged','skipped','failed'].map(k=><div key={k} className="rounded-xl bg-gray-50 p-3 dark:bg-kcs-blue-950"><p className="text-xs uppercase text-gray-500">{k}</p><b>{result[k as keyof Result] as any}</b></div>)}</div><div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>void downloadBlob(dataMigrationAPI.successReport(jobId),`import-success-${jobId}.csv`)} className="rounded-xl border px-4 py-2"><Download className="mr-1 inline" size={16}/>Success report</button><button onClick={()=>void downloadBlob(dataMigrationAPI.errorReport(jobId),`import-errors-${jobId}.csv`)} className="rounded-xl border px-4 py-2"><Download className="mr-1 inline" size={16}/>Error report</button></div><div className="mt-5 border-t pt-4"><p className="text-sm">Type <b>ROLLBACK IMPORT</b> to reverse this job. Later modifications and critical dependencies will be blocked.</p><div className="mt-2 flex gap-3"><input value={rollbackText} onChange={e=>setRollbackText(e.target.value)} className="flex-1 rounded-xl border p-3 dark:bg-kcs-blue-950"/><button disabled={busy||rollbackText!=="ROLLBACK IMPORT"} onClick={rollback} className="rounded-xl border border-red-500 px-4 py-2 font-bold text-red-700 disabled:opacity-40"><RotateCcw className="mr-1 inline" size={16}/>Rollback import</button></div></div></section>}
  {rollbackResult&&<section className={`${card} mt-6`}><h2 className="text-xl font-bold">Rollback result · {rollbackResult.status}</h2><p className="mt-2">Restored {rollbackResult.restored} · Removed {rollbackResult.removed} · Blocked {rollbackResult.blocked}</p><button onClick={()=>void downloadBlob(dataMigrationAPI.rollbackReport(jobId),`rollback-${jobId}.csv`)} className="mt-3 rounded-xl border px-4 py-2"><Download className="mr-1 inline" size={16}/>Rollback report</button></section>}
  <section className={`${card} mt-6`}><h2 className="mb-3 text-xl font-bold"><FileSpreadsheet className="mr-2 inline"/>Import History</h2>{history.length?history.map(j=><div key={j.id} className="grid gap-2 border-t py-3 text-sm md:grid-cols-7"><span>{new Date(j.createdAt).toLocaleString()}</span><b>{j.originalFileName}</b><span>{j.entityType}</span><span>{j.totalRows} rows</span><span>{j.status}</span><span>{j.createdRows} created</span><span>{j.failedRows} failed</span></div>):<p className="text-sm text-gray-500"><CheckCircle2 className="mr-2 inline" size={17}/>No migration job yet.</p>}</section>
 </main></div>
}
