import { useEffect, useMemo, useState } from 'react'
import { Building2, Eye, Landmark, MapPin, Pencil, Plus, RefreshCw, Search, ShieldAlert, Trash2, UserRound, UsersRound, X } from 'lucide-react'
import InternationalPhoneInput from '../../components/InternationalPhoneInput'
import { employeesAPI } from '../../services/api'

type Employee=Record<string,any>
const empty={first_name:'',middle_name:'',last_name:'',user_email:'',phone:'',employee_id:'',employee_type:'teacher',gender:'',department:'',job_title:'',specialization:'',qualification:'',hire_date:'',contract_type:'',contract_duration_months:'',birth_date:'',birth_place:'',nationality:'Congolaise',identity_document_type:'',identity_document_other:'',residential_address:'',secondary_phone:'',personal_email:'',email_contact_preference:'work',employment_status:'active',work_location:'',work_email:'',office_phone_extension:'',payroll_reference:'',national_id_number:'',social_security_number:'',onem_number:'',tax_number:'',bank_name:'',bank_account_number:'',bank_swift_iban:'',salary_grade:'',base_salary:'',pay_frequency:'monthly',supervisor_name:'',emergency_contact_name:'',emergency_contact_relationship:'',emergency_contact_phone:'',marital_status:'',spouse_full_name:'',spouse_phone:'',spouse_occupation:'',bio:'',employment_notes:''}
const sections=[
 {number:'1',title:'Informations administratives',description:'Données réservées aux RH, au contrat, à l’affectation et à la paie.',icon:Building2,fields:[['employee_id','Matricule','text'],['hire_date','Date d’intégration','date'],['employee_type','Catégorie','select:teacher:Enseignant|administrative:Administratif|support:Support|leadership:Leadership|specialist:Spécialiste'],['contract_type','Type de contrat','text'],['contract_duration_months','Durée du contrat (mois)','number'],['department','Département / service','text'],['job_title','Intitulé du poste','text'],['specialization','Spécialisation / matière','text'],['qualification','Qualification','text'],['employment_status','Statut professionnel','select:active:Actif|leave:Congé|inactive:Inactif'],['work_location','Lieu de travail','text'],['payroll_reference','Référence paie','text'],['supervisor_name','Responsable hiérarchique','text']]},
 {number:'2',title:'État civil et identité',description:'Identité officielle selon l’ordre administratif KCS : nom, post-nom, prénom.',icon:UserRound,fields:[['last_name','Nom','text'],['middle_name','Post-nom','text'],['first_name','Prénom','text'],['gender','Genre','select:|male:Homme|female:Femme'],['birth_date','Date de naissance','date'],['birth_place','Lieu de naissance','text'],['nationality','Nationalité','text'],['identity_document_type','Pièce d’identité','text'],['identity_document_other','Référence de la pièce','text'],['national_id_number','Numéro de la pièce','text']]},
 {number:'3',title:'Coordonnées de contact',description:'Coordonnées personnelles et professionnelles utilisées pour les opérations administratives.',icon:MapPin,fields:[['residential_address','Adresse résidentielle','text'],['phone','Téléphone principal','phone'],['secondary_phone','Téléphone secondaire','phone'],['personal_email','E-mail personnel','email'],['user_email','E-mail principal','email'],['work_email','E-mail professionnel','email'],['email_contact_preference','Préférence e-mail','select:work:Professionnel uniquement|personal:Personnel uniquement|both:Les deux adresses'],['office_phone_extension','Extension bureau','text']]},
 {number:'4',title:'Informations fiscales, bancaires et paie',description:'Informations confidentielles réservées aux opérations RH et financières autorisées.',icon:Landmark,fields:[['social_security_number','Numéro CNSS','text'],['onem_number','Numéro ONEM','text'],['tax_number','Numéro fiscal','text'],['bank_name','Nom de la banque','text'],['bank_account_number','Numéro de compte bancaire','text'],['bank_swift_iban','Code SWIFT / IBAN','text'],['salary_grade','Grade salarial','text'],['base_salary','Salaire de base','number'],['pay_frequency','Fréquence de paie','select:monthly:Mensuelle|weekly:Hebdomadaire']]},
 {number:'5',title:'Contact d’urgence',description:'Personne à joindre prioritairement en cas d’urgence concernant l’employé.',icon:ShieldAlert,fields:[['emergency_contact_name','Nom complet du contact','text'],['emergency_contact_relationship','Lien de parenté','text'],['emergency_contact_phone','Téléphone d’urgence','phone']]},
 {number:'6',title:'Situation familiale',description:'Situation matrimoniale et informations déclarées sur le conjoint.',icon:UsersRound,fields:[['marital_status','Situation matrimoniale','text'],['spouse_full_name','Nom complet du conjoint','text'],['spouse_phone','Téléphone du conjoint','phone'],['spouse_occupation','Profession du conjoint','text']]},
] as const
const value=(e:Employee,k:string)=>e[k]??e.user?.[k]??''
const payload=(f:Record<string,string>,editing:boolean)=>editing?f:{...f,user:{first_name:f.first_name,middle_name:f.middle_name,last_name:f.last_name,email:f.user_email,phone:f.phone},teacher_id:f.employee_id||undefined}
const message=(error:any)=>error?.response?.data?.message||error?.response?.data?.detail||Object.values(error?.response?.data||{}).flat().join(' · ')||'Opération impossible.'

export default function EmployeesPanel(){
 const [rows,setRows]=useState<Employee[]>([]),[form,setForm]=useState<Record<string,string>>(empty),[editing,setEditing]=useState<Employee|null>(null),[viewing,setViewing]=useState<Employee|null>(null),[credentials,setCredentials]=useState<any>(null)
 const [query,setQuery]=useState(''),[type,setType]=useState('all'),[department,setDepartment]=useState('all'),[busy,setBusy]=useState(false),[notice,setNotice]=useState('')
 const load=async()=>{setBusy(true);try{const response=await employeesAPI.getAll();setRows(response.data?.data||[]);setNotice('')}catch(e){setNotice(message(e))}finally{setBusy(false)}}
 useEffect(()=>{void load()},[])
 const departments=useMemo(()=>Array.from(new Set(rows.map(x=>x.department).filter(Boolean))).sort(),[rows])
 const filtered=useMemo(()=>rows.filter(e=>{if(type!=='all'&&e.employee_type!==type)return false;if(department!=='all'&&e.department!==department)return false;const h=[e.full_name,e.employee_id,e.teacher_id,e.email,e.contact_phone,e.department,e.job_title,e.specialization,e.work_email,e.national_id_number].join(' ').toLowerCase();return query.toLowerCase().trim().split(/\s+/).every(t=>h.includes(t))}),[rows,query,type,department])
 const change=(k:string,v:string)=>setForm(x=>({...x,[k]:v}))
 const reset=()=>{setForm(empty);setEditing(null)}
 const edit=(e:Employee)=>{const f={...empty};Object.keys(f).forEach(k=>{f[k as keyof typeof f]=String(k==='first_name'?e.full_name?.split(' ').at(-1)||'':k==='last_name'?e.full_name?.split(' ').slice(0,-1).join(' ')||'':k==='user_email'?e.email||'':k==='phone'?e.contact_phone||'':value(e,k))});setForm(f);setEditing(e);window.scrollTo({top:0,behavior:'smooth'})}
 const save=async()=>{if(!form.first_name.trim()||!form.last_name.trim()){setNotice('Le prénom et le nom sont obligatoires.');return}setBusy(true);try{const response=editing?await employeesAPI.update(String(editing.id),payload(form,true)):await employeesAPI.create(payload(form,false));const data=response.data?.data;if(data?.temporaryCredentials)setCredentials(data.temporaryCredentials);setNotice(editing?'Employé mis à jour dans tout l’écosystème.':'Employé créé dans tout l’écosystème.');reset();await load()}catch(e){setNotice(message(e))}finally{setBusy(false)}}
 const remove=async(e:Employee)=>{if(!confirm('Désactiver '+e.full_name+' dans tout l’écosystème ?'))return;try{await employeesAPI.delete(String(e.id));await load()}catch(x){setNotice(message(x))}}
 return <div className="space-y-6">
  <section className="rounded-2xl border bg-white p-5 dark:border-kcs-blue-800 dark:bg-kcs-blue-900/50"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-bold dark:text-white">{editing?'Modifier le dossier employé':'Nouveau dossier employé'}</h2><p className="text-sm text-gray-500">Source RH Savanex · synchronisation Orbit, EduPay et Nexus selon le rôle.</p></div>{editing&&<button onClick={reset} className="rounded-xl border px-4 py-2">Annuler</button>}</div>
  <div className="mt-6 space-y-5">{sections.map(({number,title,description,icon:Icon,fields})=><fieldset key={number} className="overflow-hidden rounded-2xl border border-kcs-blue-100 bg-slate-50/70 shadow-sm dark:border-kcs-blue-700 dark:bg-kcs-blue-950/35"><legend className="sr-only">{title}</legend><div className="flex items-start gap-4 border-b border-kcs-blue-100 bg-gradient-to-r from-kcs-blue-50 to-white px-5 py-4 dark:border-kcs-blue-700 dark:from-kcs-blue-900 dark:to-kcs-blue-950"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-kcs-blue-700 font-black text-white shadow-md">{number}</span><div className="min-w-0"><p className="text-xs font-black uppercase tracking-[0.18em] text-kcs-gold-600">Section {number}</p><h3 className="mt-1 flex items-center gap-2 text-lg font-bold text-kcs-blue-950 dark:text-white"><Icon size={19}/>{title}</h3><p className="mt-1 text-xs font-medium text-gray-500 dark:text-gray-300">{description}</p></div></div><div className="grid gap-4 p-5 md:grid-cols-2 xl:grid-cols-3">{fields.map(([k,label,kind])=><label key={k} className="text-xs font-semibold text-gray-600 dark:text-gray-300">{label}{kind==='phone'?<InternationalPhoneInput value={form[k]} onChange={v=>change(k,v)}/>:kind.startsWith('select:')?<select value={form[k]} onChange={e=>change(k,e.target.value)} className="mt-1 w-full rounded-xl border bg-white p-3 text-kcs-blue-950 dark:border-kcs-blue-700 dark:bg-kcs-blue-950 dark:text-white">{kind.slice(7).split('|').map(o=>{const [v,l]=o.split(':');return <option key={v} value={v}>{l||'—'}</option>})}</select>:<input type={kind} value={form[k]} onChange={e=>change(k,e.target.value)} className="mt-1 w-full rounded-xl border bg-white p-3 text-kcs-blue-950 dark:border-kcs-blue-700 dark:bg-kcs-blue-950 dark:text-white"/>}</label>)}</div></fieldset>)}</div>
  <div className="mt-5 grid gap-3 md:grid-cols-2"><textarea value={form.bio} onChange={e=>change('bio',e.target.value)} placeholder="Biographie professionnelle" className="min-h-24 rounded-xl border p-3 dark:bg-kcs-blue-950"/><textarea value={form.employment_notes} onChange={e=>change('employment_notes',e.target.value)} placeholder="Notes RH" className="min-h-24 rounded-xl border p-3 dark:bg-kcs-blue-950"/></div>
  <button disabled={busy} onClick={()=>void save()} className="mt-5 rounded-xl bg-kcs-blue-700 px-5 py-3 font-bold text-white"><Plus className="mr-2 inline" size={18}/>{busy?'Traitement...':editing?'Enregistrer et synchroniser':'Créer et synchroniser'}</button>{notice&&<p className="mt-3 text-sm font-semibold text-kcs-blue-700 dark:text-kcs-blue-200">{notice}</p>}</section>
  <section className="rounded-2xl border bg-white p-5 dark:border-kcs-blue-800 dark:bg-kcs-blue-900/50"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold dark:text-white">Employés</h2><p className="text-sm text-gray-500">{filtered.length} résultat(s) sur {rows.length}</p></div><button onClick={()=>void load()} className="rounded-xl border px-4 py-2"><RefreshCw className="mr-2 inline" size={16}/>Actualiser</button></div><div className="mt-4 grid gap-3 md:grid-cols-3"><label className="relative"><Search className="absolute left-3 top-3.5" size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nom, matricule, contact, poste..." className="w-full rounded-xl border py-3 pl-10 pr-3 dark:bg-kcs-blue-950"/></label><select value={type} onChange={e=>setType(e.target.value)} className="rounded-xl border p-3 dark:bg-kcs-blue-950"><option value="all">Toutes catégories</option><option value="teacher">Enseignants</option><option value="administrative">Administratifs</option><option value="support">Support</option><option value="leadership">Leadership</option><option value="specialist">Spécialistes</option></select><select value={department} onChange={e=>setDepartment(e.target.value)} className="rounded-xl border p-3 dark:bg-kcs-blue-950"><option value="all">Tous départements</option>{departments.map(x=><option key={x}>{x}</option>)}</select></div>
  <div className="mt-4 space-y-3">{filtered.map(e=><article key={e.id} className="rounded-xl border p-4 dark:border-kcs-blue-800"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-bold dark:text-white">{e.full_name}</h3><p className="text-sm text-gray-500">{e.employee_id} · {e.job_title||e.employee_label} · {e.department||'Département non renseigné'}</p><p className="text-xs text-gray-400">{e.email||e.work_email||'Sans e-mail'} · {e.contact_phone||'Sans téléphone'}</p></div><div className="flex gap-2"><button onClick={()=>setViewing(e)} className="rounded-lg bg-blue-100 p-2 text-blue-700" title="Voir"><Eye size={17}/></button><button onClick={()=>edit(e)} className="rounded-lg bg-amber-100 p-2 text-amber-700" title="Modifier"><Pencil size={17}/></button><button onClick={()=>void remove(e)} className="rounded-lg bg-red-100 p-2 text-red-700" title="Désactiver"><Trash2 size={17}/></button></div></div></article>)}{!busy&&!filtered.length&&<p className="rounded-xl bg-gray-50 p-6 text-center text-gray-500">Aucun employé réel ne correspond aux filtres.</p>}</div></section>
  {viewing&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/60 p-4"><div className="max-h-[90vh] w-full max-w-3xl overflow-auto rounded-2xl bg-white p-6 dark:bg-kcs-blue-950"><button onClick={()=>setViewing(null)} className="float-right"><X/></button><h2 className="text-2xl font-bold dark:text-white">{viewing.full_name}</h2><div className="mt-5 grid gap-3 md:grid-cols-2">{Object.entries(viewing).filter(([,v])=>v!==null&&v!==''&&typeof v!=='object').map(([k,v])=><div key={k} className="rounded-xl bg-gray-50 p-3 dark:bg-kcs-blue-900"><p className="text-xs uppercase text-gray-400">{k.replace(/_/g,' ')}</p><p className="font-semibold dark:text-white">{String(v)}</p></div>)}</div></div></div>}
  {credentials&&<div className="fixed inset-0 z-[110] flex items-center justify-center bg-black/60 p-4"><div className="w-full max-w-xl rounded-2xl bg-white p-6 dark:bg-kcs-blue-950"><button onClick={()=>setCredentials(null)} className="float-right"><X/></button><h2 className="text-xl font-bold dark:text-white">Accès institutionnels générés</h2><div className="mt-4 rounded-xl bg-green-50 p-4 text-sm"><p>Identifiant : <b>{credentials.email||credentials.username}</b></p><p>Code accès : <b>{credentials.accessCode}</b></p><p>Mot de passe temporaire : <b>{credentials.temporaryPassword}</b></p></div></div></div>}
 </div>
}
