# Generated by Django 4.2.13 on 2026-05-05 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=20, unique=True, verbose_name='Teacher ID')),
                ('qualification', models.CharField(blank=True, max_length=200, verbose_name='Qualification')),
                ('specialization', models.CharField(blank=True, max_length=100, verbose_name='Specialization')),
                ('hire_date', models.DateField(verbose_name='Hire Date')),
                ('bio', models.TextField(blank=True, verbose_name='Biography')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'db_table': 'teachers',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
