# Generated by Django 4.2.13 on 2026-08-25 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_employee_personal_hr_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='email_contact_preference',
            field=models.CharField(blank=True, default='work', max_length=20, verbose_name='Email Contact Preference'),
        ),
    ]
