export type ImportEntityType = "STUDENT" | "PARENT" | "TEACHER" | "STAFF" | "CLASS" | "ACADEMIC_DIRECTORY";
export type ImportJobStatus = "UPLOADED" | "MAPPED" | "VALIDATED" | "READY" | "IMPORTING" | "COMPLETED" | "PARTIAL" | "FAILED" | "ROLLED_BACK";
export type ImportSeverity = "VALID" | "WARNING" | "ERROR";
export type ImportAction = "IMPORT" | "UPDATE" | "SKIP" | "MERGE" | "REVIEW";
export type ImportRow = Record<string, unknown>;
export type TargetField = "firstName" | "middleName" | "lastName" | "dateOfBirth" | "gender" | "phone" | "personalEmail" | "institutionalEmail" | "studentId" | "employeeId" | "grade" | "class" | "parent" | "guardian" | "father" | "mother" | "address" | "orbitId";
export type ColumnMapping = { sourceColumn: string; targetField: TargetField; detectedType: "text" | "email" | "phone" | "date" | "identifier"; required: boolean; transformation: "trim" | "email" | "phone" | "date" | "gender" | "grade"; confidence: number; status: "SUGGESTED" | "CONFIRMED" | "UNMAPPED" };
export type ExistingIdentity = Partial<Record<TargetField, string>> & { id: string; parentId?: string };
export type DuplicateCandidate = { id: string; confidence: number; reasons: string[]; level: "EXACT" | "HIGH" | "MEDIUM" | "LOW" };
export type ValidationIssue = { field?: TargetField; code: string; message: string; suggestedCorrection?: string };
export type DryRunRow = { row: number; source: ImportRow; normalized: Partial<Record<TargetField, string>>; status: ImportSeverity; action: ImportAction; warnings: ValidationIssue[]; errors: ValidationIssue[]; duplicates: DuplicateCandidate[] };
export type DryRunReport = { total: number; valid: number; warning: number; error: number; newRecords: number; matched: number; possibleDuplicates: number; updateCandidates: number; rows: DryRunRow[] };

const aliases: Record<TargetField, string[]> = {
 firstName:["first name","firstname","given name","prenom","prénom"], middleName:["middle name","middlename","postnom","second name"], lastName:["last name","lastname","surname","family name","nom"],
 dateOfBirth:["date of birth","dob","birth date","date naissance","date de naissance"], gender:["gender","sex","sexe","genre"], phone:["phone","telephone","téléphone","mobile","cell","contact"],
 personalEmail:["personal email","private email","email personnel"], institutionalEmail:["institutional email","school email","school mail","kcs email","email institutionnel"],
 studentId:["student id","student number","matricule","legacy student id"], employeeId:["employee id","staff id","teacher id","matricule employe","matricule employé"],
 grade:["grade","level","niveau","classe niveau"], class:["class","classroom","section","classe"], parent:["parent","parent name","nom parent"], guardian:["guardian","tuteur","responsable"], father:["father","père","pere"], mother:["mother","mère","mere"], address:["address","adresse","physical address"], orbitId:["orbit id","orbitid"]
};
const requiredByEntity: Record<ImportEntityType, TargetField[]> = { STUDENT:["firstName","lastName"], PARENT:["firstName","lastName"], TEACHER:["firstName","lastName"], STAFF:["firstName","lastName"], CLASS:["class"], ACADEMIC_DIRECTORY:["firstName","lastName"] };
const typeFor=(field:TargetField):ColumnMapping["detectedType"]=>field.toLowerCase().includes("email")?"email":field==="phone"?"phone":field==="dateOfBirth"?"date":field.endsWith("Id")?"identifier":"text";
const transformFor=(field:TargetField):ColumnMapping["transformation"]=>field.toLowerCase().includes("email")?"email":field==="phone"?"phone":field==="dateOfBirth"?"date":field==="gender"?"gender":field==="grade"||field==="class"?"grade":"trim";
export const normalizeHeader=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[_-]+/g," ").replace(/[^a-z0-9 ]/g,"").replace(/\s+/g," ").trim();
export function suggestMappings(columns:string[], entityType:ImportEntityType):ColumnMapping[]{ return columns.map(sourceColumn=>{ const key=normalizeHeader(sourceColumn); let best:TargetField|undefined; let score=0; for(const [field,names] of Object.entries(aliases) as [TargetField,string[]][]){ for(const name of [field,...names]){ const candidate=normalizeHeader(name); const next=key===candidate?1:key.includes(candidate)||candidate.includes(key)?0.82:0; if(next>score){best=field;score=next} } } return {sourceColumn,targetField:best||"firstName",detectedType:typeFor(best||"firstName"),required:best?requiredByEntity[entityType].includes(best):false,transformation:transformFor(best||"firstName"),confidence:score,status:best&&score>=.8?"SUGGESTED":"UNMAPPED"}; }); }
export function normalizePhone(value:unknown){ const raw=String(value??"").trim(); if(!raw)return ""; const digits=raw.replace(/\D/g,""); if(digits.startsWith("243"))return `+${digits}`; if(digits.startsWith("0")&&digits.length>=9)return `+243${digits.slice(1)}`; return raw.startsWith("+")?`+${digits}`:digits; }
export function normalizeDate(value:unknown):{value:string;ambiguous:boolean;valid:boolean}{ if(value instanceof Date&&!Number.isNaN(value.valueOf()))return {value:value.toISOString().slice(0,10),ambiguous:false,valid:true}; if(typeof value==="number"){const d=new Date(Date.UTC(1899,11,30)+value*86400000);return {value:d.toISOString().slice(0,10),ambiguous:false,valid:true}} const raw=String(value??"").trim(); const m=raw.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})$/); if(m){const a=+m[1],b=+m[2],y=+m[3],ambiguous=a<=12&&b<=12; const day=a,month=b; const d=new Date(Date.UTC(y,month-1,day)); return {value:`${y}-${String(month).padStart(2,"0")}-${String(day).padStart(2,"0")}`,ambiguous,valid:d.getUTCFullYear()===y&&d.getUTCMonth()===month-1&&d.getUTCDate()===day};} const d=new Date(raw); return {value:Number.isNaN(d.valueOf())?raw:d.toISOString().slice(0,10),ambiguous:false,valid:!Number.isNaN(d.valueOf())}; }
export function normalizeValue(field:TargetField,value:unknown){ const raw=String(value??"").trim().replace(/\s+/g," "); if(field==="phone")return normalizePhone(raw); if(field.toLowerCase().includes("email"))return raw.toLowerCase(); if(field==="gender"){const k=normalizeHeader(raw);return ["m","male","homme","masculin"].includes(k)?"MALE":["f","female","femme","feminin"].includes(k)?"FEMALE":raw.toUpperCase()} if(field==="grade"||field==="class"){const n=raw.match(/\d+/)?.[0];return n?`Grade ${Number(n)}`:raw} if(field==="dateOfBirth")return normalizeDate(value).value; return raw; }
const same=(a?:string,b?:string)=>!!a&&!!b&&a.trim().toLowerCase()===b.trim().toLowerCase();
export function findDuplicates(row:Partial<Record<TargetField,string>>, existing:ExistingIdentity[]):DuplicateCandidate[]{ return existing.map(item=>{let score=0;const reasons:string[]=[];const add=(points:number,why:string)=>{score=Math.max(score,points);reasons.push(why)};if(same(row.orbitId,item.orbitId))add(100,"ORBIT_ID");if(same(row.studentId,item.studentId)||same(row.employeeId,item.employeeId))add(95,"LEGACY_ID");if(same(row.institutionalEmail,item.institutionalEmail))add(100,"INSTITUTIONAL_EMAIL");if(same(row.personalEmail,item.personalEmail))add(90,"PERSONAL_EMAIL");if(same(row.phone,item.phone))add(80,"PHONE");if(same(row.firstName,item.firstName)&&same(row.lastName,item.lastName)&&same(row.dateOfBirth,item.dateOfBirth))add(85,"NAME_DOB");else if(same(row.firstName,item.firstName)&&same(row.lastName,item.lastName))add(50,"NAME_ONLY");return {id:item.id,confidence:score,reasons,level:score===100?"EXACT":score>=85?"HIGH":score>=70?"MEDIUM":"LOW"} as DuplicateCandidate}).filter(x=>x.confidence>0).sort((a,b)=>b.confidence-a.confidence); }
export function resolveInstitutionalEmail(imported:string|undefined,current:string|undefined,existingOwners:Map<string,string>,recordId?:string,generated?:string){const candidate=(imported||"").trim().toLowerCase();if(candidate){if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(candidate))return {email:candidate,source:"IMPORTED",conflict:"INVALID_EMAIL"};const owner=existingOwners.get(candidate);if(owner&&owner!==recordId)return {email:candidate,source:"IMPORTED",conflict:"DUPLICATE_EMAIL"};return {email:candidate,source:"IMPORTED"}}if(current)return {email:current,source:"CURRENT"};return {email:generated||"",source:"GENERATED"};}
export function buildDryRun(input:{rows:ImportRow[];mapping:ColumnMapping[];entityType:ImportEntityType;existing?:ExistingIdentity[];validClasses?:string[]}):DryRunReport{const required=requiredByEntity[input.entityType];const validClasses=new Set((input.validClasses||[]).map(normalizeHeader));const rows=input.rows.map((source,index)=>{const normalized:Partial<Record<TargetField,string>>={};for(const map of input.mapping)if(map.status!=="UNMAPPED")normalized[map.targetField]=normalizeValue(map.targetField,source[map.sourceColumn]);const errors:ValidationIssue[]=[];const warnings:ValidationIssue[]=[];for(const field of required)if(!normalized[field])errors.push({field,code:"REQUIRED",message:`${field} is required`});for(const field of ["personalEmail","institutionalEmail"] as TargetField[]){const v=normalized[field];if(v&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v))errors.push({field,code:"INVALID_EMAIL",message:"Invalid email"})}if(normalized.dateOfBirth){const d=normalizeDate(source[input.mapping.find(m=>m.targetField==="dateOfBirth")?.sourceColumn||""]);if(!d.valid)errors.push({field:"dateOfBirth",code:"INVALID_DATE",message:"Impossible date"});else if(d.ambiguous)warnings.push({field:"dateOfBirth",code:"AMBIGUOUS_DATE",message:"DD/MM and MM/DD are both possible"})}if(normalized.class&&validClasses.size&&!validClasses.has(normalizeHeader(normalized.class)))warnings.push({field:"class",code:"CLASS_NOT_FOUND",message:"Class does not exactly match the directory"});const duplicates=findDuplicates(normalized,input.existing||[]);if(duplicates[0]?.confidence<70)warnings.push({code:"LOW_CONFIDENCE_DUPLICATE",message:"Possible duplicate requires review"});const status:ImportSeverity=errors.length?"ERROR":warnings.length||duplicates.length?"WARNING":"VALID";const action:ImportAction=errors.length?"REVIEW":duplicates[0]?.confidence>=85?"UPDATE":duplicates.length?"REVIEW":"IMPORT";return {row:index+2,source,normalized,status,action,warnings,errors,duplicates}});return {total:rows.length,valid:rows.filter(r=>r.status==="VALID").length,warning:rows.filter(r=>r.status==="WARNING").length,error:rows.filter(r=>r.status==="ERROR").length,newRecords:rows.filter(r=>r.action==="IMPORT").length,matched:rows.filter(r=>r.duplicates[0]?.confidence>=85).length,possibleDuplicates:rows.filter(r=>r.duplicates.length>0).length,updateCandidates:rows.filter(r=>r.action==="UPDATE").length,rows};}
export function groupFamilyRows(rows:DryRunRow[]){const families=new Map<string,DryRunRow[]>();for(const row of rows){const n=row.normalized;const key=(n.personalEmail||n.phone||`${n.parent||n.guardian||n.father||n.mother||""}`).toLowerCase();if(!key)continue;families.set(key,[...(families.get(key)||[]),row])}return families;}
export function errorReportCsv(report:DryRunReport){const esc=(v:unknown)=>`"${String(v??"").replace(/"/g,'""')}"`;return ["row,entity,source_values,error,suggested_correction",...report.rows.filter(r=>r.errors.length||r.warnings.length).map(r=>[r.row,"record",JSON.stringify(r.source),[...r.errors,...r.warnings].map(i=>i.message).join("; "),[...r.errors,...r.warnings].map(i=>i.suggestedCorrection||"").filter(Boolean).join("; ")].map(esc).join(","))].join("\r\n")}
