import test from "node:test";
import assert from "node:assert/strict";
import { buildDryRun, errorReportCsv, findDuplicates, groupFamilyRows, normalizeDate, normalizePhone, resolveInstitutionalEmail, suggestMappings } from "./data-migration.js";

test("auto maps English and French QuickSchool columns",()=>{const m=suggestMappings(["Prénom","Surname","School Mail","Téléphone","Niveau"],"STUDENT");assert.deepEqual(m.map(x=>x.targetField),["firstName","lastName","institutionalEmail","phone","grade"]);assert.ok(m.every(x=>x.confidence>=.8))});
test("normalizes Congo phones and Excel/date values",()=>{assert.equal(normalizePhone("081 234 5678"),"+243812345678");assert.equal(normalizeDate(45292).value,"2024-01-01");assert.equal(normalizeDate("02/03/2012").ambiguous,true)});
test("preserves valid legacy email, generates only when missing, rejects conflict",()=>{const owners=new Map([["used@ourkcs.org","other"]]);assert.deepEqual(resolveInstitutionalEmail("old@ourkcs.org",undefined,owners,"one","new@ourkcs.org"),{email:"old@ourkcs.org",source:"IMPORTED"});assert.equal(resolveInstitutionalEmail(undefined,undefined,owners,"one","new@ourkcs.org").source,"GENERATED");assert.equal(resolveInstitutionalEmail("used@ourkcs.org",undefined,owners,"one").conflict,"DUPLICATE_EMAIL")});
test("blocks email-only identity conflicts during dry run",()=>{const source=[{"First Name":"Other","Last Name":"Identity","Student ID":"NEW-2","Institutional Email":"used@ourkcs.org"}];const report=buildDryRun({rows:source,mapping:suggestMappings(Object.keys(source[0]),"STUDENT"),entityType:"STUDENT",existing:[{id:"existing",studentId:"OLD-1",institutionalEmail:"used@ourkcs.org",firstName:"Existing",lastName:"Student"}]});assert.equal(report.error,1);assert.equal(report.rows[0].action,"REVIEW");assert.equal(report.rows[0].errors[0].code,"DUPLICATE_EMAIL")});
test("scores exact IDs and never treats name-only as automatic update",()=>{const exact=findDuplicates({studentId:"QS-1"},[{id:"s1",studentId:"QS-1"}]);assert.equal(exact[0].confidence,95);const low=findDuplicates({firstName:"Jean",lastName:"Kabuya"},[{id:"s2",firstName:"Jean",lastName:"Kabuya"}]);assert.equal(low[0].confidence,50)});
test("dry run validates without mutation and links repeated parent",()=>{const source=[{"First Name":"A","Surname":"One","Parent Email":"parent@example.org"},{"First Name":"B","Surname":"Two","Parent Email":"parent@example.org"}];const mapping=suggestMappings(Object.keys(source[0]),"STUDENT").map(m=>m.sourceColumn==="Parent Email"?{...m,targetField:"personalEmail" as const,status:"CONFIRMED" as const}:m);const before=JSON.stringify(source);const report=buildDryRun({rows:source,mapping,entityType:"STUDENT"});assert.equal(report.total,2);assert.equal(report.error,0);assert.equal(groupFamilyRows(report.rows).size,1);assert.equal(JSON.stringify(source),before)});
test("invalid data and unknown class produce errors/warnings and CSV report",()=>{const source=[{"First Name":"","Surname":"Test","DOB":"31/31/2020","Class":"Grad 12"}];const report=buildDryRun({rows:source,mapping:suggestMappings(Object.keys(source[0]),"STUDENT"),entityType:"STUDENT",validClasses:["Grade 12"]});assert.equal(report.error,1);assert.match(errorReportCsv(report),/firstName is required/)});
test("handles a 10k row dry run",()=>{const rows=Array.from({length:10000},(_,i)=>({First:`Name${i}`,Last:"Student"}));const mapping=[{sourceColumn:"First",targetField:"firstName",detectedType:"text",required:true,transformation:"trim",confidence:1,status:"CONFIRMED"},{sourceColumn:"Last",targetField:"lastName",detectedType:"text",required:true,transformation:"trim",confidence:1,status:"CONFIRMED"}] as const;assert.equal(buildDryRun({rows,mapping:[...mapping],entityType:"STUDENT"}).valid,10000)});
