import { useEffect, useMemo, useState } from 'react'
import { BookOpen, Download, FileText, RefreshCw, Upload } from 'lucide-react'
import PortalSidebar from '@/components/layout/PortalSidebar'
import { syllabiAPI } from '@/services/api'
import { useAuthStore } from '@/store/authStore'
import { useUIStore } from '@/store/uiStore'
import { getLocalizedGreeting, getLocalizedPortalDate } from '@/utils/portalGreeting'

type Item={id:string;academicYear:string;title:string;description?:string;fileName:string;fileSize:number;publishedAt:string;course:{name:string;code:string;grade:string;teacher?:{user?:{firstName:string;middleName?:string;lastName:string}}}}
type Course={id:string;name:string;code:string;grade:string;syllabus?:Item|null}
const card='rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-kcs-blue-800 dark:bg-kcs-blue-900'
const field='w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm dark:border-kcs-blue-700 dark:bg-kcs-blue-950 dark:text-white'

export default function CourseSyllabi(){
 const user=useAuthStore(s=>s.user);const language=useUIStore(s=>s.language);const fr=language==='fr';const teacher=user?.role==='teacher'
 const [items,setItems]=useState<Item[]>([]),[courses,setCourses]=useState<Course[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const [courseId,setCourseId]=useState(''),[year,setYear]=useState('2026-2027'),[title,setTitle]=useState(''),[description,setDescription]=useState(''),[file,setFile]=useState<File|null>(null)
 const tr=(a:string,b:string)=>fr?a:b
 const load=async()=>{setLoading(true);setError('');try{const [list,owned]=await Promise.all([syllabiAPI.list(),teacher?syllabiAPI.teacherCourses():Promise.resolve(null)]);setItems(list.data.data||[]);if(owned)setCourses(owned.data.data||[])}catch(e:any){setError(e.response?.data?.message||tr('Impossible de charger les syllabus.','Unable to load syllabi.'))}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 const selected=useMemo(()=>courses.find(c=>c.id===courseId),[courses,courseId])
 useEffect(()=>{if(selected){setTitle(tr('Syllabus de ','Syllabus for ')+selected.name)}},[courseId,selected])
 const publish=async()=>{if(!courseId||!file||!title.trim()){setError(tr('Sélectionnez le cours, le document et indiquez un titre.','Select the course and document, then enter a title.'));return}setBusy(true);setError('');try{const form=new FormData();form.append('academicYear',year);form.append('title',title);form.append('description',description);form.append('file',file);await syllabiAPI.publish(courseId,form);setFile(null);setDescription('');await load()}catch(e:any){setError(e.response?.data?.message||tr('Publication impossible.','Publication failed.'))}finally{setBusy(false)}}
 const download=async(item:Item)=>{try{const response=await syllabiAPI.download(item.id);const url=URL.createObjectURL(response.data);const a=document.createElement('a');a.href=url;a.download=item.fileName;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch{setError(tr('Téléchargement impossible.','Download failed.'))}}
 const name=(i:Item)=>{const u=i.course.teacher?.user;return u?[u.lastName,u.middleName,u.firstName].filter(Boolean).join(' '):tr('Enseignant du cours','Course teacher')}
 return <div className="portal-shell flex min-h-screen bg-slate-50 dark:bg-kcs-blue-950"><PortalSidebar/><main className="min-h-0 min-w-0 flex-1 overflow-x-hidden overflow-y-auto"><div className="portal-dashboard-topbar sticky top-0 z-20 border-b px-4 py-3 backdrop-blur-2xl sm:px-6 sm:py-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0"><h1 className="portal-dashboard-title font-display text-xl font-bold leading-tight sm:text-2xl">{getLocalizedGreeting(language)}, {user?.firstName || 'KCS'}</h1><p className="mt-1 text-sm font-medium text-kcs-blue-700 dark:text-kcs-blue-100">{getLocalizedPortalDate(language)} - {tr('Vos documents académiques officiels, accessibles depuis votre espace élève.','Your official academic documents, available from your student portal.')}</p></div><button onClick={()=>void load()} disabled={loading} className="rounded-xl bg-kcs-blue-700 px-4 py-3 text-sm font-bold text-white disabled:opacity-60"><RefreshCw size={16} className={loading?"mr-2 inline animate-spin":"mr-2 inline"}/>{tr("Actualiser","Refresh")}</button></div></div><div className="w-full max-w-none p-4 sm:p-6 lg:p-8"><div className="mb-6"><p className="text-xs font-black uppercase tracking-[.2em] text-kcs-gold-600">KCS Nexus · Academic documents</p><h1 className="mt-2 text-3xl font-bold text-kcs-blue-950 dark:text-white">{tr('Syllabus des cours','Course syllabi')}</h1><p className="mt-2 max-w-3xl text-sm text-slate-600 dark:text-slate-300">{tr('Documents officiels publiés par chaque enseignant pour les élèves réellement inscrits à son cours.','Official documents published by each teacher for learners actually enrolled in the course.')}</p></div>
 {error&&<p className="mb-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</p>}
 {teacher&&<section className={card}><h2 className="flex items-center gap-2 text-xl font-bold text-kcs-blue-950 dark:text-white"><Upload size={20}/>{tr('Publier ou remplacer un syllabus','Publish or replace a syllabus')}</h2><p className="mt-2 text-sm text-slate-500">{tr('PDF, DOC ou DOCX · 15 Mo maximum. Les élèves inscrits seront immédiatement avertis dans leur dashboard.','PDF, DOC or DOCX · 15 MB maximum. Enrolled learners will immediately be notified in their dashboard.')}</p><div className="mt-5 grid gap-4 md:grid-cols-2"><select className={field} value={courseId} onChange={e=>setCourseId(e.target.value)}><option value="">{tr('Choisir un de mes cours','Choose one of my courses')}</option>{courses.map(c=><option key={c.id} value={c.id}>{c.name} · {c.grade} · {c.code}</option>)}</select><input className={field} value={year} onChange={e=>setYear(e.target.value)} pattern="\d{4}-\d{4}" placeholder="2026-2027"/><input className={field} value={title} onChange={e=>setTitle(e.target.value)} placeholder={tr('Titre du document','Document title')}/><input className={field} value={description} onChange={e=>setDescription(e.target.value)} placeholder={tr('Description facultative','Optional description')}/><label className="md:col-span-2 flex cursor-pointer items-center justify-center rounded-xl border-2 border-dashed border-kcs-blue-300 p-5 text-sm font-bold text-kcs-blue-700 dark:text-sky-200"><FileText className="mr-2"/>{file?.name||tr('Sélectionner le syllabus','Select syllabus document')}<input className="sr-only" type="file" accept=".pdf,.doc,.docx" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button disabled={busy} onClick={()=>void publish()} className="md:col-span-2 rounded-xl bg-emerald-700 px-5 py-3 font-bold text-white disabled:opacity-50">{busy?tr('Publication…','Publishing…'):tr('Publier et avertir les élèves','Publish and notify learners')}</button></div></section>}
 <section className="mt-6"><div className="mb-3 flex items-center justify-between"><h2 className="text-xl font-bold text-kcs-blue-950 dark:text-white">{tr('Documents disponibles','Available documents')}</h2><span className="text-sm text-slate-500">{items.length} {tr('document(s)','document(s)')}</span></div>{loading?<div className={card}>{tr('Chargement…','Loading…')}</div>:items.length===0?<div className={card}><BookOpen className="text-kcs-blue-500"/><p className="mt-3 font-bold dark:text-white">{tr('Aucun syllabus publié pour le moment.','No syllabus has been published yet.')}</p></div>:<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map(i=><article key={i.id} className={card}><div className="flex items-start justify-between gap-3"><FileText className="text-kcs-blue-600"/><span className="rounded-full bg-kcs-blue-50 px-3 py-1 text-xs font-bold text-kcs-blue-700">{i.academicYear}</span></div><h3 className="mt-4 text-lg font-bold text-kcs-blue-950 dark:text-white">{i.title}</h3><p className="mt-1 text-sm font-semibold text-slate-600 dark:text-slate-300">{i.course.name} · {i.course.grade}</p><p className="mt-1 text-xs text-slate-500">{name(i)}</p>{i.description&&<p className="mt-3 text-sm text-slate-600 dark:text-slate-300">{i.description}</p>}<p className="mt-3 truncate text-xs text-slate-500">{i.fileName} · {(i.fileSize/1024/1024).toFixed(2)} Mo</p><button onClick={()=>void download(i)} className="mt-4 w-full rounded-xl bg-kcs-blue-700 px-4 py-3 text-sm font-bold text-white"><Download size={16} className="mr-2 inline"/>{tr('Télécharger','Download')}</button></article>)}</div>}</section></div></main></div>
}
