import { FormEvent, useEffect, useMemo, useState } from "react";
import { api, apiBlob } from "../services/api";
import { useAuthStore } from "../store/auth";
import { useI18n } from "../i18n";

type Installment={id:string;label:string;dueDate:string;amountDue:number;amountPaid:number;outstanding:number;status:string};
type Child={id:string;fullName:string;class:{name:string};installments:Installment[]};
type Allocation={studentId:string;installmentId:string;amount:number};
type Proof={id:string;version:number;originalFileName:string;uploadedAt:string;status:string;mimeType:string;fileSize:number};
type Row={id:string;status:string;amount:number;bankName:string;referenceNumber:string;paymentDate:string;submittedAt?:string;reviewReason?:string;parent:{fullName:string};allocations:Array<{student:{fullName:string};installment:Installment;feeLabel:string;amount:number}>;proofs:Proof[];payment?:{receipt?:{receiptNumber:string}}};

export function BankTransferVerificationPage(){
 const {lang}=useI18n(),L=(fr:string,en:string)=>lang==="fr"?fr:en;
 const parent=useAuthStore(s=>s.role)==="PARENT";
 const [rows,setRows]=useState<Row[]>([]),[children,setChildren]=useState<Child[]>([]),[allocations,setAllocations]=useState<Allocation[]>([{studentId:"",installmentId:"",amount:0}]),[amount,setAmount]=useState(0),[message,setMessage]=useState("");
 const allocated=useMemo(()=>allocations.reduce((sum,x)=>sum+(Number(x.amount)||0),0),[allocations]),balanced=amount>0&&Math.abs(allocated-amount)<0.005;
 const load=async()=>{try{setRows(await api<Row[]>("/api/bank-transfer-requests"));if(parent)setChildren(await api<Child[]>("/api/bank-transfer-requests/options"))}catch(e){setMessage(String(e))}};
 useEffect(()=>{void load()},[]);
 const update=(index:number,patch:Partial<Allocation>)=>setAllocations(current=>current.map((x,i)=>i===index?{...x,...patch}:x));
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!balanced)return;const f=e.currentTarget,d=new FormData(f);d.set("allocations",JSON.stringify(allocations.map(x=>{const child=children.find(c=>c.id===x.studentId),installment=child?.installments.find(i=>i.id===x.installmentId);return {...x,feeLabel:installment?.label??""}})));try{await api("/api/bank-transfer-requests",{method:"POST",body:d});f.reset();setAllocations([{studentId:"",installmentId:"",amount:0}]);setAmount(0);setMessage(L("Preuve soumise, en attente de verification Finance.","Proof submitted, awaiting Finance review."));await load()}catch(x){setMessage(String(x))}}
 async function act(id:string,path:string,reason?:string){try{await api(`/api/bank-transfer-requests/${id}/${path}`,{method:"POST",body:reason?JSON.stringify({reason}):undefined});await load()}catch(e){setMessage(String(e))}}
 async function viewProof(row:Row,proof:Proof){try{const blob=await apiBlob(`/api/bank-transfer-requests/${row.id}/proofs/${proof.id}`),url=URL.createObjectURL(blob);window.open(url,"_blank","noopener,noreferrer");setTimeout(()=>URL.revokeObjectURL(url),60000)}catch(e){setMessage(String(e))}}
 async function replaceProof(row:Row,file:File){const d=new FormData();d.set("proof",file);try{await api(`/api/bank-transfer-requests/${row.id}/proofs`,{method:"POST",body:d});await load()}catch(e){setMessage(String(e))}}
 return <div className="space-y-6"><header className="glass rounded-3xl p-6"><h1 className="text-3xl font-bold text-white">{L("Verification des virements bancaires","Bank Transfer Verification")}</h1><p className="mt-2 text-ink-dim">{parent?L("Le solde change uniquement apres approbation Finance.","Your balance changes only after Finance approval."):L("Verifier la preuve et les allocations avant validation.","Verify proof and allocations before posting a payment.")}</p></header>
 {message&&<p className="rounded-xl border border-brand-300/30 p-3 text-brand-100">{message}</p>}
 {parent&&<form onSubmit={submit} className="glass space-y-4 rounded-3xl p-6"><div className="grid gap-3 md:grid-cols-2">{[["bankName",L("Banque","Bank"),"text"],["referenceNumber",L("Reference bancaire","Bank reference"),"text"],["paymentDate",L("Date du paiement","Payment date"),"date"],["payerName",L("Nom du payeur","Payer name"),"text"]].map(([n,l,t])=><label key={n} className="text-sm text-ink-dim">{l}<input required name={n} type={t} className="mt-1 w-full rounded-xl bg-slate-950 p-3 text-white"/></label>)}<label className="text-sm text-ink-dim">{L("Montant du virement","Transfer amount")}<input required name="amount" type="number" min="0.01" step="0.01" value={amount||""} onChange={e=>setAmount(Number(e.target.value))} className="mt-1 w-full rounded-xl bg-slate-950 p-3 text-white"/></label></div>
 <div className="space-y-3"><h2 className="font-semibold text-white">{L("Allocations enfants et frais","Child and fee allocations")}</h2>{allocations.map((line,index)=>{const child=children.find(x=>x.id===line.studentId);return <div key={index} className="grid gap-2 rounded-xl border border-white/10 p-3 md:grid-cols-4"><select required value={line.studentId} onChange={e=>update(index,{studentId:e.target.value,installmentId:""})} className="rounded-xl bg-slate-950 p-3 text-white"><option value="">{L("Selectionner un enfant","Select child")}</option>{children.map(c=><option key={c.id} value={c.id}>{c.fullName} ? {c.class.name}</option>)}</select><select required value={line.installmentId} onChange={e=>update(index,{installmentId:e.target.value})} className="rounded-xl bg-slate-950 p-3 text-white"><option value="">{L("Selectionner frais/echeance","Select fee/installment")}</option>{child?.installments.map(i=><option key={i.id} value={i.id}>{i.label} ? {L("reste","outstanding")} USD {i.outstanding.toFixed(2)}</option>)}</select><input required type="number" min="0.01" step="0.01" value={line.amount||""} onChange={e=>update(index,{amount:Number(e.target.value)})} placeholder={L("Montant alloue","Allocated amount")} className="rounded-xl bg-slate-950 p-3 text-white"/><button type="button" className="btn-secondary" disabled={allocations.length===1} onClick={()=>setAllocations(x=>x.filter((_,i)=>i!==index))}>{L("Retirer","Remove")}</button></div>})}<button type="button" className="btn-secondary" onClick={()=>setAllocations(x=>[...x,{studentId:"",installmentId:"",amount:0}])}>{L("Ajouter une allocation","Add allocation")}</button><p className={balanced?"text-emerald-300":"text-amber-200"}>{L("Total alloue : USD ","Allocated total: USD ")}{allocated.toFixed(2)} / {amount.toFixed(2)}</p></div>
 <label className="block text-sm text-ink-dim">{L("Commentaire","Comment")}<input name="comment" className="mt-1 w-full rounded-xl bg-slate-950 p-3 text-white"/></label><label className="block text-sm text-ink-dim">{L("Preuve PDF/JPG/PNG (10 Mo max)","PDF/JPG/PNG proof (10 MB max)")}<input required name="proof" type="file" accept=".pdf,.jpg,.jpeg,.png" className="mt-2 block"/></label><button disabled={!balanced} className="btn-primary disabled:cursor-not-allowed disabled:opacity-50">{L("Verifier et soumettre","Review and submit")}</button></form>}
 <section className="space-y-3">{rows.map(r=><article key={r.id} className="glass rounded-2xl p-5"><div className="flex justify-between gap-3"><strong>{r.parent.fullName}{L(" ? USD "," ? USD ")}{r.amount.toFixed(2)}</strong><span>{r.status}</span></div><p className="text-sm text-ink-dim">{r.bankName} ? {r.referenceNumber} ? {new Date(r.paymentDate).toLocaleDateString()}</p><p className="text-sm text-ink-dim">{r.allocations.map(a=>`${a.student.fullName}: ${a.feeLabel} ($${a.amount})`).join(" ? ")}</p><div className="mt-3"><strong>{L("Historique des preuves","Proof version history")}</strong>{r.proofs.map((p,i)=><div key={p.id} className="mt-2 flex flex-wrap items-center gap-2 text-sm"><button className="text-brand-300 underline" onClick={()=>void viewProof(r,p)}>{L("Voir","View")} {p.originalFileName}</button><span>v{p.version}</span><span>{new Date(p.uploadedAt).toLocaleString()}</span><span>{i===0&&p.status==="PENDING"?L("Actuelle","Current"):p.status}</span></div>)}</div>{r.reviewReason&&<p className="mt-2 text-amber-200">{r.reviewReason}</p>}{parent&&["NEEDS_MORE_INFO","REJECTED"].includes(r.status)&&<label className="mt-3 block text-sm text-ink-dim">{L("Remplacer la preuve","Replace proof")}<input type="file" accept=".pdf,.jpg,.jpeg,.png" onChange={e=>{const file=e.target.files?.[0];if(file)void replaceProof(r,file)}} className="mt-1 block"/></label>}{!parent&&["SUBMITTED","UNDER_REVIEW"].includes(r.status)&&<div className="mt-3 flex flex-wrap gap-2"><button className="btn-secondary" onClick={()=>void act(r.id,"review")}>{L("Examiner","Review")}</button><button className="btn-primary" onClick={()=>confirm(L("Approuver et comptabiliser ce paiement ?","Approve and post this payment?"))&&void act(r.id,"approve")}>{L("Approuver","Approve")}</button><button className="btn-secondary" onClick={()=>{const x=prompt(L("Raison du rejet","Rejection reason"));if(x)void act(r.id,"reject",x)}}>{L("Rejeter","Reject")}</button><button className="btn-secondary" onClick={()=>{const x=prompt(L("Information requise","Information required"));if(x)void act(r.id,"request-more-info",x)}}>{L("Plus d information","More info")}</button></div>}{r.payment?.receipt&&<p className="mt-2 text-emerald-300">{L("Paiement approuve ? recu","Payment approved ? receipt")}: {r.payment.receipt.receiptNumber}</p>}</article>)}</section></div>
}
