import { FormEvent, useEffect, useMemo, useState } from "react";
import { api, apiBlob } from "../services/api";
import { useAuthStore } from "../store/auth";
import { useI18n } from "../i18n";

type Installment={id:string;label:string;dueDate:string;amountDue:number;amountPaid:number;outstanding:number;status:string};
type Child={id:string;fullName:string;class:{name:string};installments:Installment[]};
type Allocation={studentId:string;installmentId:string;amount:number};
type Proof={id:string;version:number;originalFileName:string;uploadedAt:string;status:string;mimeType:string;fileSize:number};
type Row={id:string;status:string;amount:number;bankName:string;referenceNumber:string;paymentDate:string;submittedAt?:string;reviewReason?:string;parent:{fullName:string};allocations:Array<{student:{fullName:string};installment:Installment;feeLabel:string;amount:number}>;proofs:Proof[];payment?:{receipt?:{receiptNumber:string}}};

export function BankTransferVerificationPage(){
 const {lang}=useI18n(),L=(fr:string,en:string)=>lang==="fr"?fr:en;
 const parent=useAuthStore(s=>s.role)==="PARENT";
 const [rows,setRows]=useState<Row[]>([]),[children,setChildren]=useState<Child[]>([]),[allocations,setAllocations]=useState<Allocation[]>([{studentId:"",installmentId:"",amount:0}]),[amount,setAmount]=useState(0),[message,setMessage]=useState("");
 const [filters,setFilters]=useState({search:"",status:"",dateFrom:"",dateTo:"",minAmount:"",maxAmount:""});
 const [selected,setSelected]=useState<Set<string>>(new Set());
 const [loading,setLoading]=useState(false);
 const allocated=useMemo(()=>allocations.reduce((sum,x)=>sum+(Number(x.amount)||0),0),[allocations]),balanced=amount>0&&Math.abs(allocated-amount)<0.005;
 const load=async(activeFilters=filters)=>{setLoading(true);try{const params=new URLSearchParams();if(!parent)Object.entries(activeFilters).forEach(([key,value])=>{if(value.trim())params.set(key,value.trim())});const query=params.size?`?${params.toString()}`:"";setRows(await api<Row[]>(`/api/bank-transfer-requests${query}`));setSelected(new Set());if(parent)setChildren(await api<Child[]>("/api/bank-transfer-requests/options"))}catch(e){setMessage(String(e))}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const update=(index:number,patch:Partial<Allocation>)=>setAllocations(current=>current.map((x,i)=>i===index?{...x,...patch}:x));
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!balanced)return;const f=e.currentTarget,d=new FormData(f);d.set("allocations",JSON.stringify(allocations.map(x=>{const child=children.find(c=>c.id===x.studentId),installment=child?.installments.find(i=>i.id===x.installmentId);return {...x,feeLabel:installment?.label??""}})));try{await api("/api/bank-transfer-requests",{method:"POST",body:d});f.reset();setAllocations([{studentId:"",installmentId:"",amount:0}]);setAmount(0);setMessage(L("Preuve soumise, en attente de vérification par le service Finance.","Proof submitted, awaiting Finance review."));await load()}catch(x){setMessage(String(x))}}
 async function act(id:string,path:string,reason?:string){try{await api(`/api/bank-transfer-requests/${id}/${path}`,{method:"POST",body:reason?JSON.stringify({reason}):undefined});await load()}catch(e){setMessage(String(e))}}
 async function viewProof(row:Row,proof:Proof){try{const blob=await apiBlob(`/api/bank-transfer-requests/${row.id}/proofs/${proof.id}`),url=URL.createObjectURL(blob);window.open(url,"_blank","noopener,noreferrer");setTimeout(()=>URL.revokeObjectURL(url),60000)}catch(e){setMessage(String(e))}}
 async function replaceProof(row:Row,file:File){const d=new FormData();d.set("proof",file);try{await api(`/api/bank-transfer-requests/${row.id}/proofs`,{method:"POST",body:d});await load()}catch(e){setMessage(String(e))}}
 function toggleSelected(id:string){setSelected(current=>{const next=new Set(current);next.has(id)?next.delete(id):next.add(id);return next})}
 async function deleteSelected(){if(!selected.size)return;const promptText=selected.size===1?L("Supprimer définitivement cette preuve et sa demande ? Cette action est journalisée.","Permanently delete this proof and its request? This action is audited."):L(`Supprimer définitivement ces ${selected.size} preuves et demandes ? Cette action est journalisée.`,`Permanently delete these ${selected.size} proofs and requests? This action is audited.`);if(!confirm(promptText))return;try{const result=await api<{message:string}>("/api/bank-transfer-requests",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({ids:[...selected]})});setMessage(result.message);await load()}catch(e){setMessage(String(e))}}
 return <div className="space-y-6"><header className="glass rounded-3xl p-6"><h1 className="text-3xl font-bold text-white">{L("Vérification des virements bancaires","Bank Transfer Verification")}</h1><p className="mt-2 text-ink-dim">{parent?L("Le solde change uniquement après l’approbation du service Finance.","Your balance changes only after Finance approval."):L("Vérifiez la preuve et les affectations avant de valider.","Verify proof and allocations before posting a payment.")}</p></header>
 {message&&<p className="rounded-xl border border-brand-300/30 p-3 text-brand-100">{message}</p>}
 {parent&&<form onSubmit={submit} className="glass space-y-4 rounded-3xl p-6"><div className="grid gap-3 md:grid-cols-2">{[["bankName",L("Banque","Bank"),"text"],["referenceNumber",L("Référence bancaire","Bank reference"),"text"],["paymentDate",L("Date du paiement","Payment date"),"date"],["payerName",L("Nom du payeur","Payer name"),"text"]].map(([n,l,t])=><label key={n} className="text-sm text-ink-dim">{l}<input required name={n} type={t} className="mt-1 w-full rounded-xl bg-slate-950 p-3 text-white"/></label>)}<label className="text-sm text-ink-dim">{L("Montant du virement","Transfer amount")}<input required name="amount" type="number" min="0.01" step="0.01" value={amount||""} onChange={e=>setAmount(Number(e.target.value))} className="mt-1 w-full rounded-xl bg-slate-950 p-3 text-white"/></label></div>
 <div className="space-y-3"><h2 className="font-semibold text-white">{L("Allocations enfants et frais","Child and fee allocations")}</h2>{allocations.map((line,index)=>{const child=children.find(x=>x.id===line.studentId);return <div key={index} className="grid gap-2 rounded-xl border border-white/10 p-3 md:grid-cols-4"><select required value={line.studentId} onChange={e=>update(index,{studentId:e.target.value,installmentId:""})} className="rounded-xl bg-slate-950 p-3 text-white"><option value="">{L("Selectionner un enfant","Select child")}</option>{children.map(c=><option key={c.id} value={c.id}>{c.fullName} ? {c.class.name}</option>)}</select><select required value={line.installmentId} onChange={e=>update(index,{installmentId:e.target.value})} className="rounded-xl bg-slate-950 p-3 text-white"><option value="">{L("Selectionner frais/echeance","Select fee/installment")}</option>{child?.installments.map(i=><option key={i.id} value={i.id}>{i.label} ? {L("reste","outstanding")} USD {i.outstanding.toFixed(2)}</option>)}</select><input required type="number" min="0.01" step="0.01" value={line.amount||""} onChange={e=>update(index,{amount:Number(e.target.value)})} placeholder={L("Montant alloue","Allocated amount")} className="rounded-xl bg-slate-950 p-3 text-white"/><button type="button" className="btn-secondary" disabled={allocations.length===1} onClick={()=>setAllocations(x=>x.filter((_,i)=>i!==index))}>{L("Retirer","Remove")}</button></div>})}<button type="button" className="btn-secondary" onClick={()=>setAllocations(x=>[...x,{studentId:"",installmentId:"",amount:0}])}>{L("Ajouter une allocation","Add allocation")}</button><p className={balanced?"text-emerald-300":"text-amber-200"}>{L("Total alloue : USD ","Allocated total: USD ")}{allocated.toFixed(2)} / {amount.toFixed(2)}</p></div>
 <label className="block text-sm text-ink-dim">{L("Commentaire","Comment")}<input name="comment" className="mt-1 w-full rounded-xl bg-slate-950 p-3 text-white"/></label><label className="block text-sm text-ink-dim">{L("Preuve PDF/JPG/PNG (10 Mo max)","PDF/JPG/PNG proof (10 MB max)")}<input required name="proof" type="file" accept=".pdf,.jpg,.jpeg,.png" className="mt-2 block"/></label><button disabled={!balanced} className="btn-primary disabled:cursor-not-allowed disabled:opacity-50">{L("Vérifier et soumettre","Review and submit")}</button></form>}
 {!parent&&<form onSubmit={e=>{e.preventDefault();void load(filters)}} className="glass space-y-4 rounded-3xl p-5">
  <div><h2 className="text-lg font-semibold text-white">{L("Recherche détaillée","Detailed search")}</h2><p className="text-sm text-ink-dim">{L("Recherchez par parent, élève, classe, téléphone, e-mail, payeur, banque, référence, frais, fichier ou reçu.","Search by parent, student, class, phone, email, payer, bank, reference, fee, file or receipt.")}</p></div>
  <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">
   <label className="text-sm text-ink-dim xl:col-span-2">{L("Recherche générale","Global search")}<input value={filters.search} onChange={e=>setFilters(x=>({...x,search:e.target.value}))} placeholder={L("Nom, téléphone, référence, classe…","Name, phone, reference, class…")} className="mt-1 w-full rounded-xl bg-slate-950 p-3 text-white"/></label>
   <label className="text-sm text-ink-dim">{L("Statut","Status")}<select value={filters.status} onChange={e=>setFilters(x=>({...x,status:e.target.value}))} className="mt-1 w-full rounded-xl bg-slate-950 p-3 text-white"><option value="">{L("Tous les statuts","All statuses")}</option>{["DRAFT","SUBMITTED","UNDER_REVIEW","NEEDS_MORE_INFO","REJECTED","APPROVED"].map(status=><option key={status} value={status}>{status}</option>)}</select></label>
   <label className="text-sm text-ink-dim">{L("Date du","Date from")}<input type="date" value={filters.dateFrom} onChange={e=>setFilters(x=>({...x,dateFrom:e.target.value}))} className="mt-1 w-full rounded-xl bg-slate-950 p-3 text-white"/></label>
   <label className="text-sm text-ink-dim">{L("Date au","Date to")}<input type="date" value={filters.dateTo} onChange={e=>setFilters(x=>({...x,dateTo:e.target.value}))} className="mt-1 w-full rounded-xl bg-slate-950 p-3 text-white"/></label>
   <label className="text-sm text-ink-dim">{L("Montant minimum","Minimum amount")}<input type="number" min="0" step="0.01" value={filters.minAmount} onChange={e=>setFilters(x=>({...x,minAmount:e.target.value}))} className="mt-1 w-full rounded-xl bg-slate-950 p-3 text-white"/></label>
   <label className="text-sm text-ink-dim">{L("Montant maximum","Maximum amount")}<input type="number" min="0" step="0.01" value={filters.maxAmount} onChange={e=>setFilters(x=>({...x,maxAmount:e.target.value}))} className="mt-1 w-full rounded-xl bg-slate-950 p-3 text-white"/></label>
  </div>
  <div className="flex flex-wrap items-center gap-3"><button className="btn-primary" disabled={loading}>{loading?L("Recherche…","Searching…"):L("Rechercher","Search")}</button><button type="button" className="btn-secondary" onClick={()=>{const cleared={search:"",status:"",dateFrom:"",dateTo:"",minAmount:"",maxAmount:""};setFilters(cleared);void load(cleared)}}>{L("Réinitialiser","Reset")}</button><span className="text-sm text-ink-dim">{rows.length} {L("résultat(s)","result(s)")}</span></div>
  <div className="flex flex-wrap items-center gap-3 border-t border-white/10 pt-4"><label className="flex items-center gap-2 text-sm text-white"><input type="checkbox" checked={rows.some(r=>r.status!=="APPROVED")&&rows.filter(r=>r.status!=="APPROVED").every(r=>selected.has(r.id))} onChange={e=>setSelected(e.target.checked?new Set(rows.filter(r=>r.status!=="APPROVED").map(r=>r.id)):new Set())}/>{L("Sélectionner toutes les demandes supprimables affichées","Select all displayed deletable requests")}</label><button type="button" className="rounded-xl bg-red-600 px-4 py-2 font-semibold text-white disabled:opacity-40" disabled={!selected.size} onClick={()=>void deleteSelected()}>{L(`Supprimer la sélection (${selected.size})`,`Delete selection (${selected.size})`)}</button><span className="text-xs text-amber-200">{L("Les virements approuvés sont protégés et ne peuvent pas être supprimés.","Approved transfers are protected and cannot be deleted.")}</span></div>
 </form>}
 <section className="space-y-3">{rows.map(r=><article key={r.id} className="glass rounded-2xl p-5">{!parent&&r.status!=="APPROVED"&&<label className="mb-3 flex items-center gap-2 text-sm text-ink-dim"><input type="checkbox" checked={selected.has(r.id)} onChange={()=>toggleSelected(r.id)}/>{L("Sélectionner cette preuve","Select this proof")}</label>}<div className="flex justify-between gap-3"><strong>{r.parent.fullName}{L(" ? USD "," ? USD ")}{r.amount.toFixed(2)}</strong><span>{r.status}</span></div><p className="text-sm text-ink-dim">{r.bankName} ? {r.referenceNumber} ? {new Date(r.paymentDate).toLocaleDateString()}</p><p className="text-sm text-ink-dim">{r.allocations.map(a=>`${a.student.fullName}: ${a.feeLabel} ($${a.amount})`).join(" ? ")}</p><div className="mt-3"><strong>{L("Historique des preuves","Proof version history")}</strong>{r.proofs.map((p,i)=><div key={p.id} className="mt-2 flex flex-wrap items-center gap-2 text-sm"><button className="text-brand-300 underline" onClick={()=>void viewProof(r,p)}>{L("Voir","View")} {p.originalFileName}</button><span>v{p.version}</span><span>{new Date(p.uploadedAt).toLocaleString()}</span><span>{i===0&&p.status==="PENDING"?L("Actuelle","Current"):p.status}</span></div>)}</div>{r.reviewReason&&<p className="mt-2 text-amber-200">{r.reviewReason}</p>}{parent&&["NEEDS_MORE_INFO","REJECTED"].includes(r.status)&&<label className="mt-3 block text-sm text-ink-dim">{L("Remplacer la preuve","Replace proof")}<input type="file" accept=".pdf,.jpg,.jpeg,.png" onChange={e=>{const file=e.target.files?.[0];if(file)void replaceProof(r,file)}} className="mt-1 block"/></label>}{!parent&&["SUBMITTED","UNDER_REVIEW"].includes(r.status)&&<div className="mt-3 flex flex-wrap gap-2"><button className="btn-secondary" onClick={()=>void act(r.id,"review")}>{L("Examiner","Review")}</button><button className="btn-primary" onClick={()=>confirm(L("Approuver et comptabiliser ce paiement ?","Approve and post this payment?"))&&void act(r.id,"approve")}>{L("Approuver","Approve")}</button><button className="btn-secondary" onClick={()=>{const x=prompt(L("Raison du rejet","Rejection reason"));if(x)void act(r.id,"reject",x)}}>{L("Rejeter","Reject")}</button><button className="btn-secondary" onClick={()=>{const x=prompt(L("Information requise","Information required"));if(x)void act(r.id,"request-more-info",x)}}>{L("Plus d’informations","More info")}</button></div>}{r.payment?.receipt&&<p className="mt-2 text-emerald-300">{L("Paiement approuvé — reçu","Payment approved ? receipt")}: {r.payment.receipt.receiptNumber}</p>}</article>)}</section></div>
}
