import { FormEvent, useEffect, useState } from "react";
import { api } from "../services/api";
import { useAuthStore } from "../store/auth";
import { useI18n } from "../i18n";
type Row={id:string;status:string;amount:number;bankName:string;referenceNumber:string;reviewReason?:string;parent:{fullName:string};allocations:Array<{student:{fullName:string};feeLabel:string;amount:number}>;proofs:Array<{id:string;version:number;originalFileName:string}>;payment?:{receipt?:{receiptNumber:string}}};
export function BankTransferVerificationPage(){
 const {lang}=useI18n(),L=(fr:string,en:string)=>lang==="fr"?fr:en;
 const parent=useAuthStore(s=>s.role)==="PARENT", [rows,setRows]=useState<Row[]>([]),[message,setMessage]=useState("");
 const load=()=>api<Row[]>("/api/bank-transfer-requests").then(setRows).catch(e=>setMessage(String(e)));useEffect(()=>{void load()},[]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,d=new FormData(f);d.set("allocations",JSON.stringify([{studentId:d.get("studentId"),installmentId:d.get("installmentId"),feeLabel:d.get("feeLabel"),amount:Number(d.get("amount"))}]));try{await api("/api/bank-transfer-requests",{method:"POST",body:d});f.reset();setMessage("Payment proof submitted and awaiting verification");await load()}catch(x){setMessage(String(x))}}
 async function act(id:string,path:string,reason?:string){await api(`/api/bank-transfer-requests/${id}/${path}`,{method:"POST",body:reason?JSON.stringify({reason}):undefined});await load()}
 return <div className="space-y-6"><header className="glass rounded-3xl p-6"><h1 className="text-3xl font-bold text-white">{L("Verification des virements bancaires","Bank Transfer Verification")}</h1><p className="mt-2 text-ink-dim">{parent?"Your balance changes only after Finance approval.":"Verify proof and allocations before posting a payment."}</p></header>
 {message&&<p className="rounded-xl border border-brand-300/30 p-3 text-brand-100">{message}</p>}
 {parent&&<form onSubmit={submit} className="glass grid gap-3 rounded-3xl p-6 md:grid-cols-2">{[["amount","Amount","number"],["bankName","Bank","text"],["referenceNumber","Bank reference","text"],["paymentDate","Payment date","date"],["payerName","Payer name","text"],["studentId","Child identifier","text"],["installmentId","Fee identifier","text"],["feeLabel","Fee","text"]].map(([n,l,t])=><label key={n} className="text-sm text-ink-dim">{l}<input required name={n} type={t} step={n==="amount"?"0.01":undefined} className="mt-1 w-full rounded-xl bg-slate-950 p-3 text-white"/></label>)}<label className="text-sm text-ink-dim">{L("Commentaire","Comment")}<input name="comment" className="mt-1 w-full rounded-xl bg-slate-950 p-3 text-white"/></label><label className="text-sm text-ink-dim">{L("Preuve","Proof")}<input required name="proof" type="file" accept=".pdf,.jpg,.jpeg,.png" className="mt-2 block"/></label><button className="btn-primary md:col-span-2">{L("Soumettre la preuve","Submit proof")}</button></form>}
 <section className="space-y-3">{rows.map(r=><article key={r.id} className="glass rounded-2xl p-5"><div className="flex justify-between"><strong>{r.parent.fullName} {L("- USD","- USD")} {r.amount.toFixed(2)}</strong><span>{r.status}</span></div><p className="text-sm text-ink-dim">{r.bankName} · {r.referenceNumber}</p><p className="text-sm text-ink-dim">{r.allocations.map(a=>`${a.student.fullName}: ${a.feeLabel} ($${a.amount})`).join(" · ")}</p>{r.proofs.map(p=><a key={p.id} target="_blank" rel="noreferrer" className="mr-2 text-brand-300" href={`/api/bank-transfer-requests/${r.id}/proofs/${p.id}`}>{L("Preuve v","Proof v")}{p.version}</a>)}{r.reviewReason&&<p className="text-amber-200">{r.reviewReason}</p>}{!parent&&["SUBMITTED","UNDER_REVIEW"].includes(r.status)&&<div className="mt-3 flex flex-wrap gap-2"><button className="btn-secondary" onClick={()=>void act(r.id,"review")}>{L("Examiner","Review")}</button><button className="btn-primary" onClick={()=>confirm("Approve and post this payment?")&&void act(r.id,"approve")}>{L("Approuver","Approve")}</button><button className="btn-secondary" onClick={()=>{const x=prompt("Reason");if(x)void act(r.id,"reject",x)}}>{L("Rejeter","Reject")}</button><button className="btn-secondary" onClick={()=>{const x=prompt("Information required");if(x)void act(r.id,"request-more-info",x)}}>{L("Plus d information","More info")}</button></div>}{r.payment?.receipt&&<p className="text-emerald-300">{L("Recu :","Receipt:")} {r.payment.receipt.receiptNumber}</p>}</article>)}</section></div>
}
