from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, verbose_name='Must Change Password'),
        ),
        migrations.AddField(
            model_name='user',
            name='password_generated_by_system',
            field=models.BooleanField(default=False, verbose_name='Password Generated by System'),
        ),
    ]
