import { useEffect, useState } from 'react'
import { FileCheck2, RefreshCw, Save, Send, Sparkles } from 'lucide-react'
import { teacherWorkspaceAPI } from '@/services/api'

type Report={id:string;title:string;content:string;periodStart:string;periodEnd:string;recipientRole:string;status:string;aiSource:string;submittedAt?:string|null;evidence:any}
const panel='rounded-2xl border border-sky-100 bg-sky-50/60 p-5 shadow-sm dark:border-kcs-blue-700 dark:bg-kcs-blue-900/70'
const field='w-full rounded-xl border border-gray-200 bg-white px-3 py-2.5 text-sm text-kcs-blue-950 outline-none focus:border-kcs-blue-500 dark:border-kcs-blue-700 dark:bg-kcs-blue-950 dark:text-white'
const button='inline-flex items-center justify-center gap-2 rounded-xl bg-kcs-blue-700 px-4 py-2.5 text-sm font-bold text-white hover:bg-kcs-blue-800 disabled:cursor-not-allowed disabled:opacity-50'
const iso=(date:Date)=>date.toISOString().slice(0,10)
const monthStart=()=>{const date=new Date();date.setDate(1);return iso(date)}

export default function TeacherActivityReports(){
 const [periodStart,setPeriodStart]=useState(monthStart()),[periodEnd,setPeriodEnd]=useState(iso(new Date())),[recipientRole,setRecipientRole]=useState('ADMINISTRATOR')
 const [reports,setReports]=useState<Report[]>([]),[selectedId,setSelectedId]=useState(''),[working,setWorking]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('')
 const selected=reports.find(item=>item.id===selectedId)||reports[0]
 const load=async()=>{try{const response=await teacherWorkspaceAPI.activityReports();const rows=response.data.data||[];setReports(rows);setSelectedId(current=>current||rows[0]?.id||'')}catch(reason:any){setError(reason?.response?.data?.message||'Activity reports could not be loaded.')}}
 useEffect(()=>{void load()},[])
 const generate=async()=>{setWorking(true);setError('');setMessage('');try{const response=await teacherWorkspaceAPI.generateActivityReport({periodStart,periodEnd,recipientRole});const row=response.data.data;setReports(items=>[row,...items]);setSelectedId(row.id);setMessage('Verified AI draft generated. Review and edit it before submitting.')}catch(reason:any){setError(reason?.response?.data?.message||'The report could not be generated.')}finally{setWorking(false)}}
 const update=(patch:Partial<Report>)=>setReports(items=>items.map(item=>item.id===selected?.id?{...item,...patch}:item))
 const save=async()=>{if(!selected)return;setWorking(true);setError('');try{const response=await teacherWorkspaceAPI.updateActivityReport(selected.id,{title:selected.title,content:selected.content,recipientRole:selected.recipientRole});update(response.data.data);setMessage('Editable report draft saved.')}catch(reason:any){setError(reason?.response?.data?.message||'The report could not be saved.')}finally{setWorking(false)}}
 const submit=async()=>{if(!selected||!window.confirm('Submit this reviewed report to the selected school authority?'))return;setWorking(true);setError('');try{await save();const response=await teacherWorkspaceAPI.submitActivityReport(selected.id);update(response.data.data);setMessage('Report submitted and the responsible school authority was notified.')}catch(reason:any){setError(reason?.response?.data?.message||'The report could not be submitted.')}finally{setWorking(false)}}
 return <section className={panel}><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex items-center gap-2"><Sparkles className="text-kcs-gold-600"/><h3 className="text-lg font-bold dark:text-white">AI-assisted teacher activity report</h3></div><p className="mt-2 max-w-3xl text-sm text-gray-600 dark:text-gray-300">Choose a period. Nexus uses only verified courses, published work, grading and attendance evidence. The result remains a draft until you review, edit and submit it.</p></div><button className={button} onClick={()=>void load()}><RefreshCw size={16}/>Refresh</button></div>
 <div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><label className="text-xs font-bold uppercase text-gray-500">From<input type="date" className={`${field} mt-1`} value={periodStart} onChange={event=>setPeriodStart(event.target.value)}/></label><label className="text-xs font-bold uppercase text-gray-500">To<input type="date" className={`${field} mt-1`} value={periodEnd} onChange={event=>setPeriodEnd(event.target.value)}/></label><label className="text-xs font-bold uppercase text-gray-500">Submit to<select className={`${field} mt-1`} value={recipientRole} onChange={event=>setRecipientRole(event.target.value)}><option value="ADMINISTRATOR">Administrator</option><option value="SUPER_ADMINISTRATOR">Super Administrator</option><option value="ADMINISTRATIVE_STAFF">Administrative Staff</option></select></label><button className={`${button} self-end`} disabled={working||!periodStart||!periodEnd} onClick={()=>void generate()}><Sparkles size={16}/>{working?'Generating...':'Generate verified draft'}</button></div>
 {(message||error)&&<p className={`mt-4 rounded-xl p-3 text-sm font-semibold ${error?'bg-red-50 text-red-700':'bg-emerald-50 text-emerald-700'}`}>{error||message}</p>}
 {reports.length>0&&<div className="mt-6 grid gap-4 xl:grid-cols-[280px_1fr]"><div className="space-y-2">{reports.map(report=><button key={report.id} onClick={()=>setSelectedId(report.id)} className={`w-full rounded-xl border p-3 text-left ${selected?.id===report.id?'border-kcs-blue-500 bg-white dark:bg-kcs-blue-950':'border-transparent bg-white/60 dark:bg-kcs-blue-800/40'}`}><strong className="block text-sm dark:text-white">{report.title}</strong><span className="mt-1 block text-xs text-gray-500">{report.status} · {new Date(report.periodStart).toLocaleDateString()} - {new Date(report.periodEnd).toLocaleDateString()}</span></button>)}</div>{selected&&<div className="rounded-2xl bg-white p-4 dark:bg-kcs-blue-950"><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><span className="rounded-full bg-kcs-blue-100 px-3 py-1 text-xs font-bold text-kcs-blue-700">{selected.status} · {selected.aiSource}</span><span className="text-xs text-gray-500">Evidence: {selected.evidence?.assignments?.total||0} work item(s), {selected.evidence?.attendance?.total||0} attendance record(s)</span></div><input className={field} value={selected.title} disabled={!['DRAFT','RETURNED'].includes(selected.status)} onChange={event=>update({title:event.target.value})}/><textarea className={`${field} mt-3 min-h-[420px] font-mono leading-6`} value={selected.content} disabled={!['DRAFT','RETURNED'].includes(selected.status)} onChange={event=>update({content:event.target.value})}/><select className={`${field} mt-3`} value={selected.recipientRole} disabled={!['DRAFT','RETURNED'].includes(selected.status)} onChange={event=>update({recipientRole:event.target.value})}><option value="ADMINISTRATOR">Administrator</option><option value="SUPER_ADMINISTRATOR">Super Administrator</option><option value="ADMINISTRATIVE_STAFF">Administrative Staff</option></select>{['DRAFT','RETURNED'].includes(selected.status)&&<div className="mt-4 flex flex-wrap gap-2"><button className={button} disabled={working} onClick={()=>void save()}><Save size={16}/>Save draft</button><button className={button} disabled={working||selected.content.trim().length<40} onClick={()=>void submit()}><Send size={16}/>Submit reviewed report</button></div>}{selected.status==='SUBMITTED'&&<p className="mt-4 flex items-center gap-2 text-sm font-semibold text-emerald-700"><FileCheck2 size={18}/>Submitted to the selected authority; editing is locked for audit integrity.</p>}</div>}</div>}
 </section>
}