import { useEffect, useMemo, useState } from 'react'
import { BookOpen, CheckCircle2, ClipboardCheck, Clock, RefreshCw, Save, Search, Trash2, Users } from 'lucide-react'
import { teacherWorkspaceAPI } from '@/services/api'

type Student={id:string;studentNumber:string;grade:string;section?:string;user:{firstName:string;lastName:string}}
type Submission={id:string;studentId:string;score?:number|null;feedback?:string|null;status:string;student:Student}
type Assignment={id:string;title:string;description:string;dueDate:string;maxScore:number;type:string;submissions:Submission[]}
type Course={id:string;name:string;code:string;grade:string;enrollments:Array<{studentId:string;student:Student}>;assignments:Assignment[]}
type Overview={profile:any;courses:Course[]}
type AttendanceStatus='PRESENT'|'ABSENT'|'LATE'|'EXCUSED'|'SICK'|'SUSPENDED'
const panel='rounded-2xl border border-gray-100 bg-white p-5 shadow-sm dark:border-kcs-blue-800 dark:bg-kcs-blue-900/50'
const field='w-full rounded-xl border border-gray-200 bg-white px-3 py-2.5 text-sm text-kcs-blue-950 outline-none focus:border-kcs-blue-500 dark:border-kcs-blue-700 dark:bg-kcs-blue-950 dark:text-white'
const button='inline-flex items-center justify-center gap-2 rounded-xl bg-kcs-blue-700 px-4 py-2.5 text-sm font-bold text-white hover:bg-kcs-blue-800 disabled:cursor-not-allowed disabled:opacity-50'
const tomorrow=()=>{const date=new Date();date.setDate(date.getDate()+1);return date.toISOString().slice(0,10)}
const nameOf=(student:Student)=>`${student.user.lastName} ${student.user.firstName}`.trim()||student.studentNumber

export default function TeacherAcademicOperations({segment}:{segment:'attendance'|'assignments'}){
 const [overview,setOverview]=useState<Overview>({profile:null,courses:[]}),[courseId,setCourseId]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('')
 const [query,setQuery]=useState(''),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[period,setPeriod]=useState('Daily'),[statuses,setStatuses]=useState<Record<string,AttendanceStatus>>({}),[notes,setNotes]=useState<Record<string,string>>({})
 const [draft,setDraft]=useState({title:'',description:'',dueDate:tomorrow(),maxScore:100,type:'HOMEWORK'}),[grading,setGrading]=useState<Record<string,{score:string;feedback:string}>>({})
 const course=overview.courses.find(item=>item.id===courseId)??overview.courses[0]
 const roster=useMemo(()=>course?.enrollments.map(item=>item.student).filter(student=>!query.trim()||`${nameOf(student)} ${student.studentNumber} ${student.grade} ${student.section??''}`.toLowerCase().includes(query.toLowerCase()))??[],[course,query])
 const assignments=course?.assignments??[]
 const load=async()=>{setLoading(true);setError('');try{const response=await teacherWorkspaceAPI.overview();const data=response.data.data as Overview;setOverview(data);setCourseId(current=>current||data.courses?.[0]?.id||'')}catch(reason:any){setError(reason?.response?.data?.message??'The official teacher workspace could not be loaded.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 useEffect(()=>{if(segment!=='attendance'||!course?.id)return;setStatuses(Object.fromEntries(course.enrollments.map(item=>[item.studentId,'PRESENT'])));setNotes({});teacherWorkspaceAPI.attendance(course.id,date).then(response=>{const records=response.data.data?.records??[];setStatuses(current=>({...current,...Object.fromEntries(records.map((record:any)=>[record.studentId,record.status]))}));setNotes(Object.fromEntries(records.map((record:any)=>[record.studentId,record.note??''])))}).catch(()=>undefined)},[segment,course?.id,date])
 const feedback=(text:string,isError=false)=>{setMessage(isError?'':text);setError(isError?text:'')}
 const saveAttendance=async()=>{if(!course)return;setSaving(true);feedback('');try{await teacherWorkspaceAPI.saveAttendance({courseId:course.id,date,period,entries:course.enrollments.map(item=>({studentId:item.studentId,status:statuses[item.studentId]??'PRESENT',note:notes[item.studentId]||undefined}))});feedback(`Official attendance saved for ${course.enrollments.length} student(s).`)}catch(reason:any){feedback(reason?.response?.data?.message??'Attendance could not be saved.',true)}finally{setSaving(false)}}
 const createAssignment=async()=>{if(!course||!draft.title.trim()||!draft.description.trim())return;setSaving(true);feedback('');try{await teacherWorkspaceAPI.createAssignment({courseId:course.id,...draft});setDraft({title:'',description:'',dueDate:tomorrow(),maxScore:100,type:'HOMEWORK'});await load();feedback(`Assignment published to ${course.enrollments.length} enrolled student(s).`)}catch(reason:any){feedback(reason?.response?.data?.message??'Assignment could not be published.',true)}finally{setSaving(false)}}
 const deleteAssignment=async(id:string)=>{if(!window.confirm('Delete this assignment and its linked submissions?'))return;setSaving(true);try{await teacherWorkspaceAPI.deleteAssignment(id);await load();feedback('Assignment deleted with an audit entry.')}catch(reason:any){feedback(reason?.response?.data?.message??'Assignment could not be deleted.',true)}finally{setSaving(false)}}
 const grade=async(assignment:Assignment,submission:Submission)=>{const value=grading[submission.id]??{score:String(submission.score??''),feedback:submission.feedback??''};if(value.score===''||Number(value.score)<0||Number(value.score)>assignment.maxScore)return feedback(`Enter a score between 0 and ${assignment.maxScore}.`,true);setSaving(true);try{await teacherWorkspaceAPI.gradeSubmission(assignment.id,submission.studentId,{score:Number(value.score),feedback:value.feedback});await load();feedback(`${nameOf(submission.student)} graded and synchronized with the official gradebook.`)}catch(reason:any){feedback(reason?.response?.data?.message??'The grade could not be saved.',true)}finally{setSaving(false)}}
 if(loading)return <div className={panel}><Clock className="mr-2 inline animate-spin"/>Loading the official teacher workspace...</div>
 if(!overview.profile)return <div className={panel}><h2 className="font-bold dark:text-white">Teacher profile synchronization pending</h2><p className="mt-2 text-sm text-gray-500">The institutional account is valid, but no teacher profile is linked yet.</p></div>
 return <div className="space-y-5">
  <div className={panel}><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-3">{segment==='attendance'?<ClipboardCheck className="text-kcs-blue-600"/>:<BookOpen className="text-kcs-blue-600"/>}<h2 className="text-xl font-bold dark:text-white">{segment==='attendance'?'Official attendance register':'Assignments and submission review'}</h2></div><p className="mt-2 text-sm text-gray-500">{segment==='attendance'?'Daily, period and subject attendance saved in the official student record.':'Publish to the whole enrolled class, review submissions, grade and provide feedback.'}</p></div><button className={button} onClick={()=>void load()} disabled={loading}><RefreshCw size={16}/>Refresh official data</button></div></div>
  {(message||error)&&<p className={`rounded-xl p-4 text-sm font-semibold ${error?'bg-red-50 text-red-700 dark:bg-red-950/30 dark:text-red-200':'bg-green-50 text-green-700 dark:bg-green-950/30 dark:text-green-200'}`}>{error||message}</p>}
  <div className={panel}><div className="grid gap-3 lg:grid-cols-[1fr_260px]"><label className="text-xs font-bold uppercase text-gray-400">Assigned course<select className={`${field} mt-1 normal-case`} value={course?.id??''} onChange={event=>setCourseId(event.target.value)}>{overview.courses.map(item=><option key={item.id} value={item.id}>{item.code} - {item.name} - {item.grade}</option>)}</select></label><div className="grid grid-cols-2 gap-2"><div className="rounded-xl bg-kcs-blue-50 p-3 text-center dark:bg-kcs-blue-800/30"><Users className="mx-auto text-kcs-blue-600" size={18}/><strong className="mt-1 block dark:text-white">{course?.enrollments.length??0}</strong><span className="text-xs text-gray-500">Enrolled</span></div><div className="rounded-xl bg-kcs-blue-50 p-3 text-center dark:bg-kcs-blue-800/30"><BookOpen className="mx-auto text-kcs-blue-600" size={18}/><strong className="mt-1 block dark:text-white">{assignments.length}</strong><span className="text-xs text-gray-500">Assignments</span></div></div></div></div>
  {!course?<div className={panel}><h3 className="font-bold dark:text-white">No official course assigned</h3><p className="mt-2 text-sm text-gray-500">An administrator must assign a course before attendance, assignments or grades can be recorded.</p></div>:segment==='attendance'?<>
   <div className={panel}><div className="grid gap-3 md:grid-cols-[180px_180px_1fr_auto]"><input type="date" className={field} value={date} onChange={event=>setDate(event.target.value)}/><input className={field} value={period} onChange={event=>setPeriod(event.target.value)} placeholder="Period"/><label className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={16}/><input className={`${field} pl-9`} value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search student or number..."/></label><button className={button} onClick={()=>setStatuses(Object.fromEntries(course.enrollments.map(item=>[item.studentId,'PRESENT'])))}><CheckCircle2 size={16}/>All present</button></div></div>
   <div className={panel}>{course.enrollments.length===0?<p className="text-sm text-gray-500">No student is enrolled in this course.</p>:<div className="overflow-x-auto"><table className="min-w-[760px] w-full text-sm"><thead><tr className="border-b text-left text-xs uppercase text-gray-400"><th className="pb-3">Student</th><th>Number</th><th>Status</th><th>Note</th></tr></thead><tbody>{roster.map(student=><tr key={student.id} className="border-b dark:border-kcs-blue-800"><td className="py-3 font-semibold dark:text-white">{nameOf(student)}</td><td>{student.studentNumber}</td><td><select className={field} value={statuses[student.id]??'PRESENT'} onChange={event=>setStatuses(current=>({...current,[student.id]:event.target.value as AttendanceStatus}))}>{['PRESENT','ABSENT','LATE','EXCUSED','SICK','SUSPENDED'].map(status=><option key={status}>{status}</option>)}</select></td><td><input className={field} value={notes[student.id]??''} onChange={event=>setNotes(current=>({...current,[student.id]:event.target.value}))} placeholder="Optional verified note"/></td></tr>)}</tbody></table></div>}<button className={`${button} mt-5 w-full sm:w-auto`} disabled={saving||course.enrollments.length===0} onClick={()=>void saveAttendance()}><Save size={16}/>{saving?'Saving...':'Save official attendance'}</button></div>
  </>:<>
   <div className={panel}><h3 className="font-bold dark:text-white">Publish a class assignment</h3><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-5"><input className={`${field} xl:col-span-2`} value={draft.title} onChange={event=>setDraft({...draft,title:event.target.value})} placeholder="Assignment title"/><select className={field} value={draft.type} onChange={event=>setDraft({...draft,type:event.target.value})}>{['HOMEWORK','QUIZ','EXAM','PROJECT','LAB'].map(type=><option key={type}>{type}</option>)}</select><input type="date" className={field} value={draft.dueDate} onChange={event=>setDraft({...draft,dueDate:event.target.value})}/><input type="number" min="1" className={field} value={draft.maxScore} onChange={event=>setDraft({...draft,maxScore:Number(event.target.value)})} placeholder="Max score"/><textarea className={`${field} min-h-24 md:col-span-2 xl:col-span-4`} value={draft.description} onChange={event=>setDraft({...draft,description:event.target.value})} placeholder="Clear instructions, expected work and assessment criteria..."/><button className={button} disabled={saving||!draft.title.trim()||!draft.description.trim()||course.enrollments.length===0} onClick={()=>void createAssignment()}><BookOpen size={16}/>Publish to class</button></div></div>
   <div className="space-y-4">{assignments.length===0?<div className={panel}><p className="text-sm text-gray-500">No official assignment has been published for this course.</p></div>:assignments.map(assignment=><details key={assignment.id} className={panel}><summary className="cursor-pointer list-none"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase text-kcs-gold-600">{assignment.type} - due {new Date(assignment.dueDate).toLocaleDateString()}</p><h3 className="mt-1 font-bold dark:text-white">{assignment.title}</h3><p className="mt-1 text-sm text-gray-500">{assignment.description}</p></div><div className="flex gap-2"><span className="rounded-full bg-kcs-blue-50 px-3 py-1 text-xs font-bold text-kcs-blue-700">{assignment.submissions.filter(item=>item.status==='GRADED').length}/{assignment.submissions.length} graded</span><button type="button" onClick={event=>{event.preventDefault();void deleteAssignment(assignment.id)}} className="rounded-lg p-2 text-red-600 hover:bg-red-50" aria-label="Delete assignment"><Trash2 size={17}/></button></div></div></summary><div className="mt-5 overflow-x-auto"><table className="min-w-[820px] w-full text-sm"><thead><tr className="border-b text-left text-xs uppercase text-gray-400"><th className="pb-3">Student</th><th>Status</th><th>Score / {assignment.maxScore}</th><th>Feedback</th><th></th></tr></thead><tbody>{assignment.submissions.map(submission=>{const value=grading[submission.id]??{score:String(submission.score??''),feedback:submission.feedback??''};return <tr key={submission.id} className="border-b dark:border-kcs-blue-800"><td className="py-3 font-semibold dark:text-white">{nameOf(submission.student)}</td><td>{submission.status}</td><td><input type="number" min="0" max={assignment.maxScore} className={field} value={value.score} onChange={event=>setGrading(current=>({...current,[submission.id]:{...value,score:event.target.value}}))}/></td><td><input className={field} value={value.feedback} onChange={event=>setGrading(current=>({...current,[submission.id]:{...value,feedback:event.target.value}}))} placeholder="Specific feedback"/></td><td><button className={button} disabled={saving||value.score===''} onClick={()=>void grade(assignment,submission)}><Save size={15}/>Grade</button></td></tr>})}</tbody></table></div></details>)}</div>
  </>}
 </div>
}
