import { createBlankLesson, createFlexibleWeeklyPlan, isAutoGeneratedWeeklyPlan, schoolDisplayName, schoolName } from "../data/defaults";
import { cloudAuthService } from "./cloudAuthService";
import { LessonActivityAction, LessonFilters, LessonPlan, LessonStatus, LessonWorkflowAction, WeeklyPlanDay } from "../types/lesson";
import { UserProfile } from "../types/user";

const key = "powerful-lesson-planner:lessons";
const tombstonesKey = "powerful-lesson-planner:lesson-tombstones";

const readTombstones = (): Record<string, string> => {
  try {
    return JSON.parse(localStorage.getItem(tombstonesKey) || "{}") as Record<string, string>;
  } catch {
    return {};
  }
};

const writeTombstones = (tombstones: Record<string, string>) => localStorage.setItem(tombstonesKey, JSON.stringify(tombstones));

const markDeleted = (id: string, timestamp: string) => {
  writeTombstones({ ...readTombstones(), [id]: timestamp });
};

const clearDeletedMark = (id: string) => {
  const tombstones = readTombstones();
  delete tombstones[id];
  writeTombstones(tombstones);
};

const read = (options: { includeDeleted?: boolean } = {}): LessonPlan[] => {
  try {
    const lessons = JSON.parse(localStorage.getItem(key) || "[]") as LessonPlan[];
    const normalized = lessons.map((lesson) => normalizeLesson(lesson));
    return options.includeDeleted ? normalized : normalized.filter((lesson) => !lesson.deletedAt);
  } catch {
    return [];
  }
};

const write = (lessons: LessonPlan[]) => {
  localStorage.setItem(key, JSON.stringify(lessons));
};

const readAll = () => read({ includeDeleted: true });

const normalizeLesson = (lesson: Partial<LessonPlan>): LessonPlan => {
  const base = createBlankLesson(lesson.lessonNumber || `LP-${new Date().getFullYear()}-0001`);
  const subject = lesson.subject || base.subject;
  const gradeClass = lesson.gradeClass || base.gradeClass;
  const chapter = isGeneratedLessonTitle(lesson.chapter) ? base.chapter : lesson.chapter || base.chapter;
  const weeklyPlan = normalizeWeeklyPlan(lesson.weeklyPlan, subject, gradeClass, chapter);
  const ownerId = lesson.ownerId || base.ownerId;
  const ownerName = lesson.ownerName || lesson.teachers || base.ownerName;
  const department = lesson.department || base.department;
  const weekStartDate = lesson.weekStartDate || getWeekStartDate(lesson.date || base.date);

  return {
    ...base,
    ...lesson,
    ownerId,
    ownerName,
    department,
    planType: lesson.planType || base.planType,
    status: normalizeStatus(lesson.status),
    schoolName: !lesson.schoolName || lesson.schoolName === schoolName || lesson.schoolName.includes("KINSHASA CHRISTIAN SCHOOL") ? schoolDisplayName : lesson.schoolName,
    schoolYear: lesson.schoolYear || base.schoolYear,
    semester: lesson.semester || base.semester,
    quarter: lesson.quarter || lesson.term || base.quarter,
    chapter,
    teachers: lesson.teachers || base.teachers,
    subject,
    gradeClass,
    duration: lesson.duration || base.duration,
    week: lesson.week || base.week,
    weekStartDate,
    weekEndDate: lesson.weekEndDate || getWeekEndDate(weekStartDate),
    tags: lesson.tags || base.tags,
    learningObjectives: lesson.learningObjectives?.length ? lesson.learningObjectives : base.learningObjectives,
    learningOutcomes: lesson.learningOutcomes?.length ? lesson.learningOutcomes : base.learningOutcomes,
    successCriteria: lesson.successCriteria?.length ? lesson.successCriteria : base.successCriteria,
    materialsResources: lesson.materialsResources?.length ? lesson.materialsResources : base.materialsResources,
    vocabulary: lesson.vocabulary?.length ? lesson.vocabulary : base.vocabulary,
    safetyConsiderations: lesson.safetyConsiderations?.length ? lesson.safetyConsiderations : base.safetyConsiderations,
    stages: lesson.stages?.length ? lesson.stages : base.stages,
    blooms: { ...base.blooms, ...(lesson.blooms || {}) },
    differentiation: { ...base.differentiation, ...(lesson.differentiation || {}) },
    assessment: { ...base.assessment, ...(lesson.assessment || {}) },
    reflection: { ...base.reflection, ...(lesson.reflection || {}) },
    weeklyPlan,
    activityLogs: lesson.activityLogs || [],
    revisionNotes: lesson.revisionNotes || [],
    reviewerComments: lesson.reviewerComments || [],
    revisionRequests: lesson.revisionRequests || [],
    approvalHistory: lesson.approvalHistory || [],
    workflowHistory: lesson.workflowHistory || [],
    versions: lesson.versions || []
  };
};

const getWeekStartDate = (dateValue?: string) => {
  const date = dateValue ? new Date(`${dateValue}T00:00:00`) : new Date();
  if (Number.isNaN(date.getTime())) return "";
  date.setDate(date.getDate() - ((date.getDay() + 6) % 7));
  return toIsoDate(date);
};

const getWeekEndDate = (startValue?: string) => {
  if (!startValue) return "";
  const date = new Date(`${startValue}T00:00:00`);
  if (Number.isNaN(date.getTime())) return "";
  date.setDate(date.getDate() + 4);
  return toIsoDate(date);
};

const toIsoDate = (date: Date) => {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
};

const normalizeStatus = (status?: string): LessonStatus => {
  if (status === "active") return "draft";
  if (["draft", "submitted", "under-review", "revision-requested", "approved", "final-approved", "rejected", "archived", "published"].includes(status || "")) {
    return status as LessonStatus;
  }
  return "draft";
};

const isGeneratedLessonTitle = (value?: string) => Boolean(value?.trim().toLowerCase().startsWith("weekly lesson plan"));

const cloudHeaders = (extra: Record<string, string> = {}) => ({
  ...cloudAuthService.baseHeaders(cloudAuthService.getAccessToken()),
  ...extra
});

const toCloudRow = (lesson: LessonPlan) => ({
  id: lesson.id,
  owner_id: lesson.ownerId,
  department: lesson.department || "",
  status: lesson.status,
  payload: lesson,
  deleted_at: lesson.deletedAt || null,
  created_at: lesson.createdAt,
  updated_at: lesson.updatedAt
});

const fromCloudRow = (row: Record<string, unknown>) => {
  const payload = row.payload && typeof row.payload === "object" ? row.payload as Partial<LessonPlan> : {};
  return normalizeLesson({
    ...payload,
    id: String(row.id || payload.id || ""),
    ownerId: String(row.owner_id || payload.ownerId || ""),
    department: String(row.department || payload.department || ""),
    status: String(row.status || payload.status || "draft") as LessonStatus,
    deletedAt: row.deleted_at ? String(row.deleted_at) : payload.deletedAt,
    createdAt: String(row.created_at || payload.createdAt || new Date().toISOString()),
    updatedAt: String(row.updated_at || payload.updatedAt || new Date().toISOString())
  });
};

const cloudRequest = async <T>(path: string, options: RequestInit = {}) => {
  const response = await fetch(cloudAuthService.restUrl(path), {
    ...options,
    headers: {
      ...cloudHeaders(),
      ...(options.headers || {})
    }
  });
  const text = await response.text();
  const data = text ? JSON.parse(text) : null;
  if (!response.ok) {
    const message = data?.message || data?.msg || data?.error_description || "Lesson cloud request failed";
    throw new Error(message);
  }
  return data as T;
};

const mergeLessons = (localLessons: LessonPlan[], cloudLessons: LessonPlan[]) => {
  const byId = new Map<string, LessonPlan>();
  const tombstones = readTombstones();
  [...localLessons, ...cloudLessons].forEach((lesson) => {
    const deletedAt = tombstones[lesson.id];
    if (deletedAt && !lesson.deletedAt) lesson = { ...lesson, deletedAt, updatedAt: deletedAt };
    const current = byId.get(lesson.id);
    if (!current || new Date(lesson.updatedAt || 0).getTime() >= new Date(current.updatedAt || 0).getTime()) {
      byId.set(lesson.id, lesson);
    }
  });
  return [...byId.values()].sort((a, b) => new Date(b.updatedAt || b.createdAt).getTime() - new Date(a.updatedAt || a.createdAt).getTime());
};

const syncLessonToCloud = (lesson: LessonPlan) => {
  if (!cloudAuthService.enabled || !lesson.ownerId) return;
  cloudRequest("lesson_plans?on_conflict=id", {
    method: "POST",
    headers: cloudHeaders({ Prefer: "resolution=merge-duplicates" }),
    body: JSON.stringify(toCloudRow(lesson))
  }).catch((error) => console.warn("Lesson cloud sync failed", error));
};

const syncLessonsToCloud = (lessons: LessonPlan[]) => {
  lessons.forEach(syncLessonToCloud);
};

const normalizeWeeklyPlan = (weeklyPlan: Partial<WeeklyPlanDay>[] | undefined, subject: string, gradeClass: string, chapter: string): WeeklyPlanDay[] => {
  const base = createFlexibleWeeklyPlan(subject, gradeClass, chapter);
  const hasManualWeeklyEdits = Boolean(weeklyPlan?.some((day) => day?.editedFields && Object.values(day.editedFields).some(Boolean)));
  const hasSavedWeeklyContent = Boolean(weeklyPlan?.some((day) =>
    ["lesson", "objectives", "introduction", "presentation", "guidedPractice", "exitTicket", "assessment", "homework"].some((key) => {
      const value = day?.[key as keyof WeeklyPlanDay];
      return typeof value === "string" && value.trim();
    })
  ));

  if (!hasManualWeeklyEdits && !hasSavedWeeklyContent && isAutoGeneratedWeeklyPlan(weeklyPlan, subject, gradeClass, chapter)) return base;

  return base.map((day, index) => ({
    ...day,
    ...(weeklyPlan?.[index] || {}),
    day: weeklyPlan?.[index]?.day || day.day,
    lesson: weeklyPlan?.[index]?.lesson ?? day.lesson,
    objectives: weeklyPlan?.[index]?.objectives ?? day.objectives,
    introduction: weeklyPlan?.[index]?.introduction ?? day.introduction ?? "",
    presentation: weeklyPlan?.[index]?.presentation ?? day.presentation,
    guidedPractice: weeklyPlan?.[index]?.guidedPractice ?? day.guidedPractice,
    exitTicket: weeklyPlan?.[index]?.exitTicket ?? day.exitTicket,
    assessment: weeklyPlan?.[index]?.assessment ?? day.assessment,
    homework: weeklyPlan?.[index]?.homework ?? day.homework
  }));
};

export const lessonRepository = {
  list: read,
  listAll: readAll,
  async syncFromCloud() {
    if (!cloudAuthService.enabled) return readAll();
    const rows = await cloudRequest<Record<string, unknown>[]>("lesson_plans?select=*&order=updated_at.desc");
    const cloudLessons = rows.map(fromCloudRow);
    const merged = mergeLessons(readAll(), cloudLessons);
    write(merged);
    syncLessonsToCloud(merged.filter((lesson) => lesson.ownerId));
    return merged;
  },
  get(id: string) {
    return readAll().find((lesson) => lesson.id === id && !lesson.deletedAt);
  },
  save(lesson: LessonPlan, actor?: UserProfile | null, description = "Lesson plan updated") {
    const lessons = readAll();
    const current = lessons.find((item) => item.id === lesson.id);
    const nextLesson = withActivity(
      { ...lesson, updatedAt: lesson.updatedAt || new Date().toISOString() },
      actor,
      current ? "updated" : "created",
      description,
      current?.status !== lesson.status ? { field: "status", oldValue: current?.status, newValue: lesson.status } : undefined
    );
    const next = lessons.some((item) => item.id === lesson.id)
      ? lessons.map((item) => (item.id === lesson.id ? nextLesson : item))
      : [nextLesson, ...lessons];
    write(next);
    syncLessonToCloud(nextLesson);
    return nextLesson;
  },
  duplicate(lesson: LessonPlan, actor: UserProfile, lessonNumber: string) {
    const now = new Date().toISOString();
    const copy = withActivity(
      {
        ...lesson,
        id: crypto.randomUUID(),
        ownerId: actor.id,
        ownerName: actor.name,
        department: actor.department,
        lessonNumber,
        topic: `${lesson.topic || "Untitled Lesson"} (Copy)`,
        status: "draft",
        deletedAt: undefined,
        deletedBy: undefined,
        deletedByName: undefined,
        createdAt: now,
        updatedAt: now,
        activityLogs: [],
        revisionNotes: [],
        reviewerComments: [],
        revisionRequests: [],
        approvalHistory: [],
        workflowHistory: [],
        versions: []
      },
      actor,
      "duplicated",
      `Duplicated from ${lesson.lessonNumber || lesson.id}`
    );
    write([copy, ...readAll()]);
    syncLessonToCloud(copy);
    return copy;
  },
  changeStatus(id: string, status: LessonStatus, actor: UserProfile | null | undefined, description?: string) {
    const lessons = readAll();
    const lesson = lessons.find((item) => item.id === id);
    if (!lesson) return undefined;
    const action = actionForStatus(status, lesson.status);
    const now = new Date().toISOString();
    const next = withActivity(
      { ...lesson, status, updatedAt: now },
      actor,
      action,
      description || `Status changed from ${lesson.status} to ${status}`,
      { field: "status", oldValue: lesson.status, newValue: status }
    );
    write(lessons.map((item) => (item.id === id ? next : item)));
    syncLessonToCloud(next);
    return next;
  },
  workflowAction(id: string, action: LessonWorkflowAction, status: LessonStatus, actor: UserProfile | null | undefined, comment = "") {
    const lessons = readAll();
    const lesson = lessons.find((item) => item.id === id);
    if (!lesson) return undefined;
    const timestamp = new Date().toISOString();
    const user = actorInfo(actor);
    const workflowEvent = {
      id: crypto.randomUUID(),
      ...user,
      userRole: actor?.role || "system",
      action,
      timestamp,
      fromStatus: lesson.status,
      toStatus: status,
      comment: comment.trim()
    };
    const note = { id: crypto.randomUUID(), ...user, timestamp, note: comment.trim() || workflowDescription(action, lesson.status, status) };
    const nextBase: LessonPlan = {
      ...lesson,
      status,
      updatedAt: timestamp,
      workflowHistory: [workflowEvent, ...(lesson.workflowHistory || [])],
      reviewerComments: shouldStoreReviewerComment(action) ? [note, ...(lesson.reviewerComments || [])] : lesson.reviewerComments || [],
      revisionRequests: action === "revision-requested" ? [note, ...(lesson.revisionRequests || [])] : lesson.revisionRequests || [],
      approvalHistory: ["hod-approved", "final-approved"].includes(action) ? [workflowEvent, ...(lesson.approvalHistory || [])] : lesson.approvalHistory || []
    };
    const next = withActivity(
      nextBase,
      actor,
      action === "hod-approved" ? "approved" : action === "final-approved" ? "final-approved" : action === "revision-requested" ? "revision-requested" : action,
      workflowDescription(action, lesson.status, status, comment),
      { field: "status", oldValue: lesson.status, newValue: status }
    );
    write(lessons.map((item) => (item.id === id ? next : item)));
    syncLessonToCloud(next);
    return next;
  },
  addRevisionNote(id: string, note: string, actor: UserProfile | null | undefined) {
    const lessons = readAll();
    const lesson = lessons.find((item) => item.id === id);
    if (!lesson || !note.trim()) return undefined;
    const timestamp = new Date().toISOString();
    const user = actorInfo(actor);
    const next = withActivity(
      {
        ...lesson,
        updatedAt: timestamp,
        revisionNotes: [{ id: crypto.randomUUID(), ...user, timestamp, note: note.trim() }, ...(lesson.revisionNotes || [])]
      },
      actor,
      "revision-note",
      note.trim()
    );
    write(lessons.map((item) => (item.id === id ? next : item)));
    syncLessonToCloud(next);
    return next;
  },
  softDelete(id: string, actor: UserProfile | null | undefined) {
    const lessons = readAll();
    const lesson = lessons.find((item) => item.id === id);
    if (!lesson) return;
    const timestamp = new Date().toISOString();
    const user = actorInfo(actor);
    const next = withActivity(
      { ...lesson, deletedAt: timestamp, deletedBy: user.userId, deletedByName: user.userName, updatedAt: timestamp },
      actor,
      "soft-deleted",
      "Lesson plan moved to deleted items"
    );
    markDeleted(id, timestamp);
    write(lessons.map((item) => (item.id === id ? next : item)));
    syncLessonToCloud(next);
  },
  restore(id: string, actor: UserProfile | null | undefined) {
    const lessons = readAll();
    const lesson = lessons.find((item) => item.id === id);
    if (!lesson) return undefined;
    const next = withActivity(
      { ...lesson, deletedAt: undefined, deletedBy: undefined, deletedByName: undefined, updatedAt: new Date().toISOString() },
      actor,
      "restored",
      "Lesson plan restored from deleted items"
    );
    clearDeletedMark(id);
    write(lessons.map((item) => (item.id === id ? next : item)));
    syncLessonToCloud(next);
    return next;
  },
  remove(id: string, actor?: UserProfile | null) {
    const lessons = readAll();
    const lesson = lessons.find((item) => item.id === id);
    if (!lesson) return;
    const timestamp = new Date().toISOString();
    const user = actorInfo(actor);
    const next = withActivity(
      { ...lesson, deletedAt: timestamp, deletedBy: user.userId, deletedByName: user.userName, updatedAt: timestamp },
      actor,
      "soft-deleted",
      "Lesson plan moved to deleted items"
    );
    markDeleted(id, timestamp);
    write(lessons.map((item) => (item.id === id ? next : item)));
    syncLessonToCloud(next);
  },
  import(lessons: LessonPlan[]) {
    write(lessons);
    syncLessonsToCloud(lessons);
  },
  exportJson() {
    return JSON.stringify(readAll(), null, 2);
  }
};

const actionForStatus = (status: LessonStatus, oldStatus: LessonStatus): LessonActivityAction => {
  if (status === "submitted") return "submitted";
  if (status === "under-review") return "review-started";
  if (status === "approved") return "approved";
  if (status === "revision-requested") return "revision-requested";
  if (status === "final-approved") return "final-approved";
  if (status === "rejected") return "rejected";
  if (status === "published") return "published";
  if (status === "archived") return "archived";
  if (oldStatus === "archived") return "unarchived";
  return "status-changed";
};

const shouldStoreReviewerComment = (action: LessonWorkflowAction) =>
  ["review-started", "hod-approved", "revision-requested", "rejected", "final-approved"].includes(action);

const workflowDescription = (action: LessonWorkflowAction, fromStatus: LessonStatus, toStatus: LessonStatus, comment = "") => {
  const labels: Record<LessonWorkflowAction, string> = {
    submitted: "Submitted for review",
    "review-started": "Review started",
    "hod-approved": "Approved by HOD",
    "revision-requested": "Returned for correction",
    rejected: "Rejected by reviewer",
    "final-approved": "Final approval granted"
  };
  return `${labels[action]} (${fromStatus} -> ${toStatus})${comment.trim() ? `: ${comment.trim()}` : ""}`;
};

const actorInfo = (actor?: UserProfile | null) => ({
  userId: actor?.id || "system",
  userName: actor?.name || "System"
});

const withActivity = (
  lesson: LessonPlan,
  actor: UserProfile | null | undefined,
  action: LessonActivityAction,
  description: string,
  change?: { field?: string; oldValue?: string; newValue?: string }
): LessonPlan => ({
  ...lesson,
  activityLogs: [
    {
      id: crypto.randomUUID(),
      ...actorInfo(actor),
      action,
      timestamp: new Date().toISOString(),
      field: change?.field,
      oldValue: change?.oldValue,
      newValue: change?.newValue,
      description
    },
    ...(lesson.activityLogs || [])
  ]
});

export const filterLessons = (lessons: LessonPlan[], filters: LessonFilters) => {
  const query = filters.query.trim().toLowerCase();
  const tags = filters.tags.toLowerCase().split(",").map((tag) => tag.trim()).filter(Boolean);

  return lessons.filter((lesson) => {
    const haystack = [
      lesson.schoolName,
      lesson.teachers,
      lesson.subject,
      lesson.gradeClass,
      lesson.topic,
      lesson.subtopic,
      lesson.chapter,
      lesson.schoolYear,
      lesson.semester,
      lesson.quarter,
      lesson.week,
      lesson.term,
      lesson.tags.join(" "),
      lesson.learningObjectives.map((item) => item.value).join(" "),
      lesson.weeklyPlan?.map((day) => Object.values(day).join(" ")).join(" ")
    ].join(" ").toLowerCase();
    const month = lesson.date ? String(new Date(lesson.date).getMonth() + 1).padStart(2, "0") : "";
    const year = lesson.date ? String(new Date(lesson.date).getFullYear()) : "";
    const lessonTime = lesson.date ? new Date(`${lesson.date}T00:00:00`).getTime() : Number.NaN;
    const fromTime = filters.dateFrom ? new Date(`${filters.dateFrom}T00:00:00`).getTime() : Number.NaN;
    const toTime = filters.dateTo ? new Date(`${filters.dateTo}T00:00:00`).getTime() : Number.NaN;

    return (
      (!query || haystack.includes(query)) &&
      (!filters.teacher || lesson.teachers.toLowerCase().includes(filters.teacher.toLowerCase())) &&
      (!filters.subject || lesson.subject.toLowerCase().includes(filters.subject.toLowerCase())) &&
      (!filters.grade || lesson.gradeClass.toLowerCase().includes(filters.grade.toLowerCase())) &&
      (!filters.date || lesson.date === filters.date) &&
      (!filters.dateFrom || (!Number.isNaN(lessonTime) && lessonTime >= fromTime)) &&
      (!filters.dateTo || (!Number.isNaN(lessonTime) && lessonTime <= toTime)) &&
      (!filters.topic || lesson.topic.toLowerCase().includes(filters.topic.toLowerCase())) &&
      (!filters.week || lesson.week === filters.week) &&
      (!filters.month || month === filters.month.padStart(2, "0")) &&
      (!filters.year || year === filters.year) &&
      (!filters.term || lesson.term.toLowerCase().includes(filters.term.toLowerCase())) &&
      (!tags.length || tags.every((tag) => lesson.tags.join(" ").toLowerCase().includes(tag))) &&
      (filters.status === "all" || lesson.status === filters.status)
    );
  });
};
