import React,{useEffect,useRef,useState}from'react'
import{Mic,Square,Trash2}from'lucide-react'
type Props={onRecorded:(file:File)=>void;disabled?:boolean;language?:'fr'|'en'}
const mime=()=>typeof MediaRecorder==='undefined'?'':['audio/mp4','audio/webm;codecs=opus','audio/webm'].find(x=>MediaRecorder.isTypeSupported(x))||''
export default function AudioRecorder({onRecorded,disabled=false,language='fr'}:Props){
 const[recording,setRecording]=useState(false),[elapsed,setElapsed]=useState(0),[error,setError]=useState('')
 const recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),chunks=useRef<Blob[]>([]),timer=useRef<number|null>(null)
 const tr=(fr:string,en:string)=>language==='fr'?fr:en
 const release=()=>{stream.current?.getTracks().forEach(x=>x.stop());stream.current=null;if(timer.current!==null)window.clearInterval(timer.current);timer.current=null}
 useEffect(()=>()=>release(),[])
 const start=async()=>{setError('');if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==='undefined'){setError(tr("L'enregistrement audio n'est pas pris en charge par ce navigateur.",'Audio recording is not supported by this browser.'));return}try{const source=await navigator.mediaDevices.getUserMedia({audio:true}),kind=mime(),active=new MediaRecorder(source,kind?{mimeType:kind}:undefined);stream.current=source;recorder.current=active;chunks.current=[];setElapsed(0);active.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data)};active.onstop=()=>{const type=active.mimeType||kind||'audio/webm',blob=new Blob(chunks.current,{type});if(blob.size){const ext=type.includes('mp4')?'m4a':'webm',stamp=new Date().toISOString().replace(/[:.]/g,'-');onRecorded(new File([blob],`message-audio-${stamp}.${ext}`,{type}))}release()};active.start();setRecording(true);timer.current=window.setInterval(()=>setElapsed(x=>x+1),1000)}catch{release();setError(tr("Autorisez l'accès au microphone puis réessayez.",'Allow microphone access, then try again.'))}}
 const stop=()=>{if(recorder.current?.state==='recording')recorder.current.stop();setRecording(false)}
 const cancel=()=>{chunks.current=[];if(recorder.current?.state==='recording')recorder.current.stop();setRecording(false);setElapsed(0)}
 const time=`${String(Math.floor(elapsed/60)).padStart(2,'0')}:${String(elapsed%60).padStart(2,'0')}`
 return <div className="rounded-xl border border-sky-200 bg-sky-50 p-3 dark:border-kcs-blue-700 dark:bg-kcs-blue-900/60"><div className="flex flex-wrap items-center gap-3">{!recording?<button type="button" disabled={disabled} onClick={()=>void start()} className="inline-flex min-h-11 items-center gap-2 rounded-full bg-emerald-600 px-4 py-2 text-sm font-bold text-white shadow-sm hover:bg-emerald-700 disabled:opacity-50"><Mic size={18}/>{tr('Enregistrer un message audio','Record an audio message')}</button>:<><span className="inline-flex items-center gap-2 font-mono text-sm font-bold text-red-600"><span className="h-3 w-3 animate-pulse rounded-full bg-red-600"/>{time}</span><button type="button" onClick={stop} className="inline-flex min-h-11 items-center gap-2 rounded-full bg-red-600 px-4 py-2 text-sm font-bold text-white"><Square size={16} fill="currentColor"/>{tr("Terminer l'enregistrement",'Stop recording')}</button><button type="button" onClick={cancel} aria-label={tr("Annuler l'enregistrement",'Cancel recording')} className="rounded-full border p-3 dark:text-white"><Trash2 size={17}/></button></>}<span className="text-xs text-gray-500 dark:text-gray-300">{tr('Comme sur WhatsApp : enregistrez, puis envoyez.','Like WhatsApp: record, then send.')}</span></div>{error?<p className="mt-2 text-xs font-semibold text-red-600">{error}</p>:null}</div>
}
