import { useEffect, useState } from 'react'
import { Download, FileCheck2, RefreshCw, ShieldCheck } from 'lucide-react'
import { academicRecordsAPI } from '@/services/api'

type Row={id:string;percentage:number;letterGrade:string;credits:number;cycle?:{academicYear?:string;term?:string};course?:{name?:string;code?:string}}
type Transcript={student:{studentNumber:string;name:string;grade:string};rows:Row[];summary:{credits:number;cumulativeGpa:number|null;officialRecords:number};generatedAt:string;dataPolicy:string}
const card='rounded-2xl border border-gray-100 bg-white p-5 shadow-sm dark:border-kcs-blue-800 dark:bg-kcs-blue-900/50'
const esc=(value:unknown)=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]??c))

export default function OfficialTranscriptPanel({studentId}:{studentId?:string|null}){
 const [data,setData]=useState<Transcript|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState('')
 const load=async()=>{if(!studentId)return;setLoading(true);setError('');try{const response=await academicRecordsAPI.transcript(studentId);setData(response.data.data)}catch(reason:any){setData(null);setError(reason?.response?.data?.message??'The official transcript is temporarily unavailable.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[studentId])
 const download=()=>{if(!data?.rows.length)return;const rows=data.rows.map(row=>`<tr><td>${esc(row.course?.code)}</td><td>${esc(row.course?.name)}</td><td>${esc(row.cycle?.academicYear)}</td><td>${esc(row.cycle?.term)}</td><td>${row.percentage.toFixed(1)}%</td><td>${esc(row.letterGrade)}</td><td>${row.credits}</td></tr>`).join('');const html=`<!doctype html><html><head><meta charset="utf-8"><title>KCS Official Transcript</title><style>@page{size:A4;margin:18mm}body{font-family:Arial;color:#102552}header{border-bottom:4px solid #c99a2e;padding-bottom:14px}table{width:100%;border-collapse:collapse;font-size:12px}th,td{padding:9px;border-bottom:1px solid #dbe3ef;text-align:left}.meta,.seal{margin:22px 0;padding:14px;background:#f4f7fb}</style></head><body><header><h1>Kinshasa Christian School</h1><p>Official Academic Transcript - KCS Nexus</p></header><div class="meta"><strong>${esc(data.student.name)}</strong><br>${esc(data.student.studentNumber)} - ${esc(data.student.grade)}</div><table><thead><tr><th>Code</th><th>Course</th><th>Year</th><th>Term</th><th>Result</th><th>Grade</th><th>Credits</th></tr></thead><tbody>${rows}</tbody></table><div class="seal"><strong>Approved records only</strong><p>Credits: ${data.summary.credits} - Cumulative GPA: ${data.summary.cumulativeGpa??'-'}</p><p>This document contains no projected or invented grade.</p></div></body></html>`;const url=URL.createObjectURL(new Blob([html],{type:'text/html;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`KCS-official-transcript-${data.student.studentNumber||'student'}.html`;a.click();URL.revokeObjectURL(url)}
 return <section className={card}><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex gap-3"><span className="rounded-xl bg-green-50 p-3 text-green-700 dark:bg-green-950/40"><FileCheck2 size={22}/></span><div><h2 className="font-bold dark:text-white">Official academic transcript</h2><p className="mt-1 text-sm text-gray-500">Only grades approved by authorized school staff appear here.</p></div></div><button onClick={()=>void load()} disabled={loading||!studentId} className="inline-flex items-center gap-2 rounded-xl border px-3 py-2 text-sm font-bold dark:border-kcs-blue-700 dark:text-white"><RefreshCw size={16} className={loading?'animate-spin':''}/>Refresh</button></div>{error?<p className="mt-4 rounded-xl bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</p>:loading?<p className="mt-4 text-sm text-gray-500">Verifying approved records...</p>:!data||data.dataPolicy==='NO_OFFICIAL_DATA'?<div className="mt-4 rounded-xl bg-amber-50 p-4 text-sm text-amber-900 dark:bg-amber-950/30 dark:text-amber-100"><strong>No official record published yet.</strong><p className="mt-1">Draft, projected and unapproved grades are excluded.</p></div>:<><div className="mt-5 grid gap-3 sm:grid-cols-3">{[['Official results',data.summary.officialRecords],['Credits',data.summary.credits],['Cumulative GPA',data.summary.cumulativeGpa??'-']].map(([label,value])=><div key={label} className="rounded-xl bg-gray-50 p-3 dark:bg-kcs-blue-800/30"><p className="text-xs font-bold uppercase text-gray-400">{label}</p><p className="mt-1 text-xl font-bold dark:text-white">{value}</p></div>)}</div><div className="mt-5 overflow-x-auto"><table className="min-w-[620px] w-full text-sm"><thead><tr className="border-b text-left text-xs uppercase text-gray-400"><th className="pb-3">Course</th><th>Year</th><th>Term</th><th className="text-right">Result</th><th className="text-right">Credits</th></tr></thead><tbody>{data.rows.map(row=><tr key={row.id} className="border-b dark:border-kcs-blue-800"><td className="py-3 font-semibold dark:text-white">{row.course?.name??row.course?.code??'Course'}</td><td>{row.cycle?.academicYear??'-'}</td><td>{row.cycle?.term??'-'}</td><td className="text-right font-bold">{row.percentage.toFixed(1)}% - {row.letterGrade}</td><td className="text-right">{row.credits}</td></tr>)}</tbody></table></div><button onClick={download} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-kcs-blue-700 px-4 py-2.5 text-sm font-semibold text-white"><Download size={17}/>Download official transcript</button><p className="mt-3 inline-flex items-center gap-2 text-xs font-semibold text-green-700"><ShieldCheck size={15}/>Approved-record policy enforced by the server.</p></>}</section>
}
