import React, { useEffect } from 'react';
import { createPortal } from 'react-dom';
import { BriefcaseBusiness, Building2, CreditCard, Edit3, HeartHandshake, House, UserRound, X } from 'lucide-react';
import { PrintableKcsCard } from './KcsIdentityTools';

const value = (v) => v === null || v === undefined || v === '' ? 'Non renseigné' : typeof v === 'boolean' ? (v ? 'Oui' : 'Non') : String(v);
const employeeSections = [
  { number:'01', title:'Informations administratives', icon:BriefcaseBusiness, fields:[['Code employé','employee_id'],['Date d’intégration','hire_date'],['Type de contrat','contract_type'],['Durée du contrat (mois)','contract_duration_months'],['Département / service','department'],['Intitulé du poste','job_title'],['Statut professionnel','employment_status'],['Rôle dans l’écosystème','employee_label']] },
  { number:'02', title:'État civil et identité', icon:UserRound, fields:[['Nom complet','full_name'],['Nom','last_name'],['Post-nom','middle_name'],['Prénom','first_name'],['Genre','gender'],['Date de naissance','birth_date'],['Lieu de naissance','birth_place'],['Nationalité','nationality'],['Pièce d’identité','identity_document_type'],['Numéro de la pièce','identity_document_number']] },
  { number:'03', title:'Coordonnées de contact', icon:House, fields:[['Adresse résidentielle','residential_address'],['Téléphone principal','phone'],['Téléphone secondaire','secondary_phone'],['Email personnel','personal_email'],['Email professionnel','work_email'],['Canal email privilégié','email_contact_preference']] },
  { number:'04', title:'Informations fiscales et bancaires', icon:CreditCard, fields:[['Numéro CNSS','cnss_number'],['Numéro ONEM','onem_number'],['Banque','bank_name'],['Numéro de compte','bank_account_number'],['Code SWIFT / IBAN','bank_swift_iban'],['Salaire de base','base_salary'],['Fréquence de paie','pay_frequency']] },
  { number:'05', title:'Contact d’urgence', icon:HeartHandshake, fields:[['Nom complet','emergency_contact_name'],['Lien de parenté','emergency_contact_relationship'],['Téléphone d’urgence 1','emergency_contact_phone'],['Téléphone d’urgence 2','emergency_contact_phone_secondary']] },
  { number:'06', title:'Situation familiale', icon:Building2, fields:[['État civil','marital_status'],['Nom du conjoint','spouse_full_name'],['Téléphone du conjoint','spouse_phone'],['Profession du conjoint','spouse_occupation']] },
];
const basic = {
 student:[['ID élève','student_id'],['Nom complet','full_name'],['Email','email'],['Classe','class_name'],['Parent responsable','parent_name'],['Date de naissance','date_of_birth'],['Genre','gender'],['Carte KCS','kcs_card_id'],['Statut','is_active']],
 parent:[['ID parent','parent_external_id'],['Famille / parent','family_name'],['Email','email'],['Téléphone','phone'],['Adresse','address'],['Élèves liés','students_label'],['Classes','classes_label'],['Effectif','student_count'],['Carte KCS','kcs_card_id']],
};
const DetailGrid=({fields,entity})=><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{fields.map(([label,key])=><div key={key} className="min-w-0 border-l-2 border-cyan-400/40 bg-slate-950/35 px-3 py-2.5"><p className="text-[11px] font-semibold uppercase tracking-[0.12em] text-slate-500">{label}</p><p className="mt-1 break-words text-sm font-medium text-slate-100">{value(entity[key])}</p></div>)}</div>;
const EntityDetailPanel=({entity,type,onClose,onEdit})=>{
 useEffect(()=>{if(!entity)return;const old=document.body.style.overflow;document.body.style.overflow='hidden';const key=e=>e.key==='Escape'&&onClose?.();window.addEventListener('keydown',key);return()=>{document.body.style.overflow=old;window.removeEventListener('keydown',key);};},[entity,onClose]);
 if(!entity)return null; const photo=entity.photo_data||entity.photoData||entity.parent_photo_data||entity.avatar||'';
 return createPortal(<div className="savanex-modal-backdrop fixed inset-0 z-[1000] flex items-center justify-center p-2 sm:p-4" role="dialog" aria-modal="true" onClick={onClose}>
  <section className="savanex-modal-panel h-[calc(100dvh-1rem)] w-[80vw] max-w-none overflow-y-auto border border-cyan-400/20 p-4 shadow-2xl sm:h-[calc(100dvh-2rem)] sm:p-6" onClick={e=>e.stopPropagation()}>
   <header className="sticky top-0 z-10 -mx-4 -mt-4 mb-6 border-b border-slate-700/70 bg-slate-950/95 px-4 py-4 backdrop-blur sm:-mx-6 sm:-mt-6 sm:px-6">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex min-w-0 items-center gap-4"><div className="h-20 w-20 shrink-0 overflow-hidden rounded-lg border border-cyan-300/40 bg-slate-900">{photo?<img src={photo} alt="Portrait" className="h-full w-full object-cover"/>:<div className="flex h-full items-center justify-center"><UserRound className="h-8 w-8 text-slate-500"/></div>}</div><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-cyan-300">Dossier institutionnel</p><h3 className="mt-1 text-xl font-bold text-white">{type==='employee'?'Fiche complète de l’employé':type==='student'?'Fiche de l’élève':'Fiche du parent'}</h3><p className="mt-1 text-sm text-slate-400">{entity.full_name||entity.family_name||'Entité SAVANEX'} · {entity.employee_id||entity.student_id||entity.parent_external_id||entity.id}</p></div></div><div className="flex gap-2">{onEdit&&<button type="button" onClick={()=>onEdit(entity)} className="inline-flex items-center gap-2 rounded-lg bg-amber-300 px-4 py-2 text-sm font-bold text-slate-950"><Edit3 className="h-4 w-4"/>Modifier</button>}<button type="button" onClick={onClose} className="inline-flex items-center gap-2 rounded-lg border border-slate-700 px-3 py-2 text-sm text-slate-200"><X className="h-4 w-4"/>Fermer</button></div></div>
   </header>
   <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_340px]"><main className="space-y-4">{type==='employee'?employeeSections.map(({number,title,icon:Icon,fields})=><section key={number} className="overflow-hidden rounded-lg border border-slate-700/70 bg-slate-900/45"><div className="flex items-center gap-3 border-b border-slate-700/60 bg-slate-900/80 px-4 py-3"><span className="flex h-9 w-9 items-center justify-center rounded-md bg-cyan-400/10 text-xs font-bold text-cyan-300">{number}</span><Icon className="h-5 w-5 text-cyan-300"/><h4 className="font-semibold text-white">{title}</h4></div><div className="p-4"><DetailGrid fields={fields} entity={entity}/>{number==='06'&&<div className="mt-4 border-t border-slate-700/60 pt-4"><p className="mb-3 text-xs font-semibold uppercase tracking-[0.14em] text-slate-400">Enfants ({Array.isArray(entity.children)?entity.children.length:0})</p>{Array.isArray(entity.children)&&entity.children.length?<div className="grid gap-2 sm:grid-cols-2">{entity.children.map((child,i)=><div key={`${child.full_name}-${i}`} className="rounded-md bg-slate-950/50 px-3 py-2 text-sm text-slate-200"><strong>{i+1}. {value(child.full_name)}</strong><span className="ml-2 text-slate-400">{value(child.birth_date)} · {value(child.gender)}</span></div>)}</div>:<p className="text-sm text-slate-500">Aucun enfant renseigné.</p>}</div>}</div></section>):<section className="rounded-lg border border-slate-700/70 bg-slate-900/45 p-4"><DetailGrid fields={basic[type]||[]} entity={entity}/></section>}</main><aside><div className="sticky top-28"><PrintableKcsCard entity={entity}/></div></aside></div>
  </section></div>,document.body);
};
export default EntityDetailPanel;
