import { jsPDF } from 'jspdf';
import QRCode from 'qrcode';
import { documentsService } from '../services/api';

const COLORS={navy:[9,23,45],cyan:[0,163,196],gold:[210,160,43],ink:[28,39,58],muted:[91,104,123],line:[214,223,232],soft:[244,248,250],white:[255,255,255]};
const shown=v=>v===null||v===undefined||v===''?'Non renseigné':typeof v==='boolean'?(v?'Oui':'Non'):String(v);
const employeeSections=[
 ['01','INFORMATIONS ADMINISTRATIVES',[['Code employé','employee_id'],['Date d’intégration','hire_date'],['Type de contrat','contract_type'],['Durée du contrat (mois)','contract_duration_months'],['Département / service','department'],['Intitulé du poste','job_title'],['Statut professionnel','employment_status'],['Rôle dans l’écosystème','employee_label']]],
 ['02','ÉTAT CIVIL ET IDENTITÉ',[['Nom complet','full_name'],['Nom','last_name'],['Post-nom','middle_name'],['Prénom','first_name'],['Genre','gender'],['Date de naissance','birth_date'],['Lieu de naissance','birth_place'],['Nationalité','nationality'],['Pièce d’identité','identity_document_type'],['Numéro de la pièce','identity_document_number']]],
 ['03','COORDONNÉES DE CONTACT',[['Adresse résidentielle','residential_address'],['Téléphone principal','phone'],['Téléphone secondaire','secondary_phone'],['Email personnel','personal_email'],['Email professionnel','work_email'],['Préférence de contact','email_contact_preference']]],
 ['04','INFORMATIONS FISCALES ET BANCAIRES',[['Numéro CNSS','cnss_number'],['Numéro ONEM','onem_number'],['Banque','bank_name'],['Numéro de compte','bank_account_number'],['Code SWIFT / IBAN','bank_swift_iban'],['Salaire de base','base_salary'],['Fréquence de paie','pay_frequency']]],
 ['05','CONTACT D’URGENCE',[['Nom complet','emergency_contact_name'],['Lien de parenté','emergency_contact_relationship'],['Téléphone d’urgence 1','emergency_contact_phone'],['Téléphone d’urgence 2','emergency_contact_phone_secondary']]],
 ['06','SITUATION FAMILIALE',[['État civil','marital_status'],['Nom du conjoint','spouse_full_name'],['Téléphone du conjoint','spouse_phone'],['Profession du conjoint','spouse_occupation']]],
];
const simple={student:[['01','IDENTITÉ DE L’ÉLÈVE',[['ID élève','student_id'],['Nom complet','full_name'],['Email','email'],['Date de naissance','date_of_birth'],['Genre','gender'],['Carte KCS','kcs_card_id']]],['02','SCOLARITÉ ET RESPONSABLE',[['Classe','class_name'],['Parent responsable','parent_name'],['Statut actif','is_active']]]],parent:[['01','IDENTITÉ DU RESPONSABLE',[['ID parent','parent_external_id'],['Nom / famille','family_name'],['Email','email'],['Téléphone','phone'],['Adresse','address'],['Carte KCS','kcs_card_id']]],['02','ÉLÈVES RATTACHÉS',[['Élèves liés','students_label'],['Classes','classes_label'],['Effectif','student_count'],['Élèves actifs','activeStudents']]]]};
const nameOf=(e,t)=>t==='parent'?(e.family_name||e.full_name):e.full_name||[e.last_name,e.middle_name,e.first_name].filter(Boolean).join(' ');
const refOf=e=>e.employee_id||e.student_id||e.parent_external_id||e.management_id||e.id;
const loadLogo=async()=>{const r=await fetch(`${import.meta.env.BASE_URL||'/'}kcs.jpg`);if(!r.ok)return null;const b=await r.blob();return new Promise(ok=>{const x=new FileReader();x.onload=()=>ok(x.result);x.readAsDataURL(b);});};
export const generateEntityPdf=async(entity,type)=>{
 const name=shown(nameOf(entity,type)),reference=shown(refOf(entity));
 const verification=await documentsService.createVerification({entity_type:type,reference,full_name:name});
 const [qr,logo]=await Promise.all([QRCode.toDataURL(verification.verification_url,{width:420,margin:1,color:{dark:'#09172D',light:'#FFFFFF'}}),loadLogo()]);
 const doc=new jsPDF({unit:'mm',format:'a4',compress:true}); const fieldValue=(key)=>String(key).startsWith('__literal:')?String(key).slice(10):entity[key]; let page=0,y=0;
 const header=()=>{page+=1;doc.setFillColor(...COLORS.navy);doc.rect(0,0,210,39,'F');doc.setFillColor(...COLORS.cyan);doc.rect(0,39,210,2,'F');if(logo){doc.setGState(new doc.GState({opacity:.055}));doc.addImage(logo,'JPEG',55,95,100,100);doc.setGState(new doc.GState({opacity:1}));doc.addImage(logo,'JPEG',13,8,24,24);}doc.setTextColor(...COLORS.white);doc.setFont('helvetica','bold');doc.setFontSize(15);doc.text('KINSHASA CHRISTIAN SCHOOL',43,16);doc.setFontSize(8.5);doc.setFont('helvetica','normal');doc.text('SAVANEX · SYSTÈME INSTITUTIONNEL DE GESTION SCOLAIRE',43,23);doc.setTextColor(176,221,231);doc.text('DOSSIER OFFICIEL ET VÉRIFIABLE',43,29);doc.setFillColor(...COLORS.soft);doc.roundedRect(12,47,186,24,2,2,'F');doc.setTextColor(...COLORS.navy);doc.setFont('helvetica','bold');doc.setFontSize(12);doc.text(name,18,57);doc.setFont('helvetica','normal');doc.setFontSize(8);doc.setTextColor(...COLORS.muted);doc.text(`Référence : ${reference}`,18,64);doc.text(`Émis le : ${new Date(verification.issued_at).toLocaleString('fr-CD')}`,128,64);y=79;};
 const need=h=>{if(y+h>268){doc.addPage();header();}};
 const section=(number,title,items)=>{const rows=[];for(let i=0;i<items.length;i+=2)rows.push(items.slice(i,i+2));const height=15+rows.reduce((sum,row)=>sum+Math.max(...row.map(([,key])=>Math.max(17,doc.splitTextToSize(shown(fieldValue(key)),78).length*4.3+12))),0)+5;need(height);doc.setFillColor(...COLORS.navy);doc.roundedRect(12,y,186,11,1.5,1.5,'F');doc.setFillColor(...COLORS.cyan);doc.roundedRect(12,y,13,11,1.5,1.5,'F');doc.setTextColor(...COLORS.white);doc.setFont('helvetica','bold');doc.setFontSize(8);doc.text(number,18.5,y+7.1,{align:'center'});doc.text(title,30,y+7.1);y+=15;for(const row of rows){const cellHeights=row.map(([,key])=>Math.max(17,doc.splitTextToSize(shown(fieldValue(key)),78).length*4.3+12));const h=Math.max(...cellHeights);row.forEach(([label,key],index)=>{const x=12+index*94;doc.setFillColor(...COLORS.white);doc.setDrawColor(...COLORS.line);doc.roundedRect(x,y,90,h-3,1.5,1.5,'FD');doc.setTextColor(...COLORS.cyan);doc.setFont('helvetica','bold');doc.setFontSize(6.8);doc.text(label.toUpperCase(),x+4,y+5.3);doc.setTextColor(...COLORS.ink);doc.setFont('helvetica','normal');doc.setFontSize(8.8);doc.text(doc.splitTextToSize(shown(fieldValue(key)),80),x+4,y+11);});y+=h;}y+=2;};
 header();const sections=type==='employee'?employeeSections:(simple[type]||[]);sections.forEach(([n,t,f])=>{section(n,t,f);if(type==='employee'&&n==='06'&&Array.isArray(entity.children)&&entity.children.length){const children=entity.children.map((c,i)=>[`Enfant ${i+1}`,`__literal:${shown(c.full_name)} · ${shown(c.birth_date)} · ${shown(c.gender)}`]);section('6A','ENFANTS',children);}});
 need(48);doc.setFillColor(...COLORS.soft);doc.setDrawColor(...COLORS.line);doc.roundedRect(12,y,186,43,2,2,'FD');doc.addImage(qr,'PNG',17,y+5,32,32);doc.setTextColor(...COLORS.navy);doc.setFont('helvetica','bold');doc.setFontSize(9);doc.text('VÉRIFICATION D’AUTHENTICITÉ',55,y+12);doc.setFont('helvetica','normal');doc.setTextColor(...COLORS.muted);doc.setFontSize(8);doc.text(doc.splitTextToSize('Scannez ce code QR pour confirmer en ligne l’origine, la référence et la date d’émission de ce dossier.',125),55,y+19);doc.setFont('helvetica','bold');doc.setTextColor(...COLORS.gold);doc.text(`Référence sécurisée : ${verification.document_reference}`,55,y+33);
 const total=doc.getNumberOfPages();for(let p=1;p<=total;p++){doc.setPage(p);doc.setDrawColor(...COLORS.line);doc.line(12,282,198,282);doc.setTextColor(...COLORS.muted);doc.setFont('helvetica','normal');doc.setFontSize(6.8);doc.text('Kinshasa Christian School · Document confidentiel · SAVANEX',12,287);doc.text(`Page ${p} / ${total}`,198,287,{align:'right'});}doc.save(`KCS-SAVANEX-${type}-${reference}.pdf`);return {filename:`KCS-SAVANEX-${type}-${reference}.pdf`};
};
