import { createHash } from "node:crypto";
import { Router } from "express";
import multer from "multer";
import { buildDryRun, errorReportCsv, suggestMappings, type ColumnMapping, type ImportEntityType } from "@ecosystem/shared-contracts";
import { prisma } from "../config/prisma.js";
import { authenticate, requireAdmin, type AuthenticatedRequest } from "../middleware/auth.js";
import { ApiError, asyncHandler, success } from "../utils/api.js";
import { MAX_IMPORT_BYTES, parseImportBuffer, templateWorkbook, validateImportFile } from "../modules/data-migration/file-parser.js";
import { commitImportJob, rollbackImportJob } from "../modules/data-migration/commit-service.js";

export const dataMigrationRouter=Router();
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:MAX_IMPORT_BYTES,files:1}});
const entities=new Set<ImportEntityType>(["STUDENT","PARENT","TEACHER","STAFF","CLASS","ACADEMIC_DIRECTORY"]);
const admin=[authenticate,requireAdmin()] as const;
const entity=(value:unknown)=>{const result=String(value||"").toUpperCase() as ImportEntityType;if(!entities.has(result))throw new ApiError(400,"Unsupported entity type");return result};

dataMigrationRouter.post("/preview",...admin,upload.single("file"),asyncHandler(async(req:AuthenticatedRequest,res)=>{if(!req.file)throw new ApiError(400,"Import file is required");try{validateImportFile(req.file.originalname,req.file.mimetype,req.file.size)}catch(error){throw new ApiError(400,(error as Error).message)}const entityType=entity(req.body.entityType);let rows;try{rows=parseImportBuffer(req.file.buffer,req.file.originalname)}catch(error){throw new ApiError(400,`Unable to parse import: ${(error as Error).message}`)}if(rows.length>10000)throw new ApiError(400,"Import is limited to 10,000 rows per job");const columns=Array.from(new Set(rows.flatMap(row=>Object.keys(row))));let mapping=suggestMappings(columns,entityType);if(req.body.mapping){try{mapping=JSON.parse(req.body.mapping) as ColumnMapping[]}catch{throw new ApiError(400,"Mapping must be valid JSON")}}const users=await prisma.user.findMany({select:{id:true,email:true,phone:true,firstName:true,lastName:true,orbitUserId:true,studentProfile:{select:{studentNumber:true,dateOfBirth:true}},teacherProfile:{select:{employeeNumber:true}},staffProfile:{select:{employeeNumber:true}}}});const existing=users.map(user=>({id:user.id,firstName:user.firstName,lastName:user.lastName,phone:user.phone||undefined,institutionalEmail:user.email,orbitId:user.orbitUserId||undefined,studentId:user.studentProfile?.studentNumber,employeeId:user.teacherProfile?.employeeNumber||user.staffProfile?.employeeNumber,dateOfBirth:user.studentProfile?.dateOfBirth?.toISOString().slice(0,10)}));const classes=await prisma.course.findMany({distinct:["grade"],select:{grade:true}});const report=buildDryRun({rows,mapping,entityType,existing,validClasses:classes.map(item=>item.grade)});const job=await prisma.importJob.create({data:{actorId:req.user!.sub,organizationId:String(req.body.organizationId||"")||null,sourceSystem:String(req.body.sourceSystem||"GENERIC").toUpperCase(),entityType,originalFileName:req.file.originalname,fileHash:createHash("sha256").update(req.file.buffer).digest("hex"),status:report.error?"VALIDATED":"READY",mapping: mapping as never,report: report as never,totalRows:report.total,failedRows:report.error}});return success(res,{jobId:job.id,columns,mapping,report,sendInvitations:false},"Dry run completed",201)}));
dataMigrationRouter.get("/jobs",...admin,asyncHandler(async(req:AuthenticatedRequest,res)=>success(res,await prisma.importJob.findMany({where:{actorId:req.user!.sub},orderBy:{createdAt:"desc"},take:100,select:{id:true,sourceSystem:true,entityType:true,originalFileName:true,status:true,totalRows:true,createdRows:true,updatedRows:true,skippedRows:true,failedRows:true,invitationsSent:true,createdAt:true}}))));
dataMigrationRouter.get("/jobs/:id",...admin,asyncHandler(async(req:AuthenticatedRequest,res)=>{const job=await prisma.importJob.findFirst({where:{id:String(req.params.id),actorId:req.user!.sub}});if(!job)throw new ApiError(404,"Import job not found");return success(res,job)}));
dataMigrationRouter.get("/jobs/:id/errors.csv",...admin,asyncHandler(async(req:AuthenticatedRequest,res)=>{const job=await prisma.importJob.findFirst({where:{id:String(req.params.id),actorId:req.user!.sub}});if(!job)throw new ApiError(404,"Import job not found");res.type("text/csv").attachment(`import-errors-${job.id}.csv`).send(errorReportCsv(job.report as never))}));
dataMigrationRouter.get("/jobs/:id/confirmation",...admin,asyncHandler(async(req:AuthenticatedRequest,res)=>{const job=await prisma.importJob.findFirst({where:{id:String(req.params.id),actorId:req.user!.sub}});if(!job)throw new ApiError(404,"Import job not found");const report=job.report as any;const rows=Array.isArray(report?.rows)?report.rows:[];return success(res,{jobId:job.id,status:job.status,newRecords:rows.filter((r:any)=>r.action==="IMPORT").length,recordsToUpdate:rows.filter((r:any)=>r.action==="UPDATE").length,recordsToMerge:rows.filter((r:any)=>r.action==="MERGE").length,recordsToSkip:rows.filter((r:any)=>r.action==="SKIP"||r.action==="REVIEW").length,warnings:report?.warning||0,errors:report?.error||0,canConfirm:job.status==="READY"&&(report?.error||0)===0,requiredConfirmation:"CONFIRM AND IMPORT"})}));
dataMigrationRouter.post("/jobs/:id/confirm",...admin,asyncHandler(async(req:AuthenticatedRequest,res)=>{try{return success(res,await commitImportJob({jobId:String(req.params.id),actorId:req.user!.sub,confirmation:String(req.body.confirmation||""),batchSize:Number(req.body.batchSize)||250}),"Import commit finished")}catch(error){throw new ApiError(409,(error as Error).message)}}));
dataMigrationRouter.post("/jobs/:id/rollback",...admin,asyncHandler(async(req:AuthenticatedRequest,res)=>{try{return success(res,await rollbackImportJob({jobId:String(req.params.id),actorId:req.user!.sub,confirmation:String(req.body.confirmation||"")}),"Import rollback finished")}catch(error){throw new ApiError(409,(error as Error).message)}}));
dataMigrationRouter.get("/jobs/:id/success.csv",...admin,asyncHandler(async(req:AuthenticatedRequest,res)=>{const job=await prisma.importJob.findFirst({where:{id:String(req.params.id),actorId:req.user!.sub}});if(!job)throw new ApiError(404,"Import job not found");const changes=await prisma.importChange.findMany({where:{importJobId:job.id,operation:{in:["CREATE","UPDATE","MERGE","CREATE_RELATION"]}},select:{entityType:true,entityId:true,operation:true,changedAt:true}});res.type("text/csv").attachment(`import-success-${job.id}.csv`).send(["entityType,entityId,operation,timestamp",...changes.map(c=>[c.entityType,c.entityId,c.operation,c.changedAt.toISOString()].join(","))].join("\r\n"))}));
dataMigrationRouter.get("/jobs/:id/rollback.csv",...admin,asyncHandler(async(req:AuthenticatedRequest,res)=>{const job=await prisma.importJob.findFirst({where:{id:String(req.params.id),actorId:req.user!.sub}});if(!job)throw new ApiError(404,"Import job not found");const changes=await prisma.importChange.findMany({where:{importJobId:job.id},select:{entityType:true,entityId:true,operation:true,rolledBackAt:true,rollbackError:true}});res.type("text/csv").attachment(`rollback-${job.id}.csv`).send(["entityType,entityId,operation,rolledBackAt,error",...changes.map(c=>[c.entityType,c.entityId,c.operation,c.rolledBackAt?.toISOString()||"",JSON.stringify(c.rollbackError||"")].join(","))].join("\r\n"))}));
dataMigrationRouter.get("/templates/:entity",...admin,asyncHandler(async(req,res)=>{const value=String(req.params.entity).toLowerCase();if(!["students","parents","teachers","staff"].includes(value))throw new ApiError(404,"Template not found");res.type("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet").attachment(`KCS-${value}-import-template.xlsx`).send(templateWorkbook(value as "students"|"parents"|"teachers"|"staff"))}));
dataMigrationRouter.get("/mapping-templates",...admin,asyncHandler(async(req:AuthenticatedRequest,res)=>success(res,await prisma.importMappingTemplate.findMany({where:{actorId:req.user!.sub},orderBy:{updatedAt:"desc"}}))));
dataMigrationRouter.post("/mapping-templates",...admin,asyncHandler(async(req:AuthenticatedRequest,res)=>{const name=String(req.body.name||"").trim();if(!name)throw new ApiError(400,"Template name is required");const entityType=entity(req.body.entityType);if(!Array.isArray(req.body.mapping)||!Array.isArray(req.body.sourceColumns))throw new ApiError(400,"Mapping and sourceColumns are required");const saved=await prisma.importMappingTemplate.upsert({where:{organizationId_name_entityType:{organizationId:req.body.organizationId||null,name,entityType}},update:{mapping:req.body.mapping,sourceColumns:req.body.sourceColumns,sourceSystem:String(req.body.sourceSystem||"GENERIC")},create:{name,actorId:req.user!.sub,organizationId:req.body.organizationId||null,sourceSystem:String(req.body.sourceSystem||"GENERIC"),entityType,sourceColumns:req.body.sourceColumns,mapping:req.body.mapping}});return success(res,saved,"Mapping template saved",201)}));
