import { createHash, randomUUID } from 'node:crypto'
import { Router } from 'express'
import multer from 'multer'
import { z } from 'zod'
import { prisma } from '../config/prisma.js'
import { authenticate, requireSuperAdmin, type AuthenticatedRequest } from '../middleware/auth.js'
import { ApiError, asyncHandler, success } from '../utils/api.js'
import { getRouteParam } from '../utils/request.js'
const allowed=new Set(['application/pdf','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document'])
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:10485760,files:1},fileFilter:(_r,f,cb)=>{if(allowed.has(f.mimetype))return cb(null,true);return cb(new ApiError(400,'PDF, DOC or DOCX required'))}})
const input=z.object({title:z.string().trim().min(5).max(180),category:z.string().trim().min(2).max(80),occurredAt:z.string().datetime(),location:z.string().trim().min(2).max(180),description:z.string().trim().min(20).max(12000),peopleInvolved:z.string().trim().max(2000).optional().default(''),immediateActions:z.string().trim().max(4000).optional().default(''),confidentiality:z.enum(['STANDARD','CONFIDENTIAL']).default('STANDARD')})
const status=z.object({status:z.enum(['SUBMITTED','UNDER_REVIEW','CLOSED']),adminNotes:z.string().trim().max(4000).optional()})
const clean=(x:any)=>({...x,attachmentData:undefined,hasAttachment:Boolean(x.attachmentName)})
export const incidentReportsRouter=Router()
incidentReportsRouter.use(authenticate)
incidentReportsRouter.get('/',asyncHandler(async(req:AuthenticatedRequest,res)=>success(res,(await prisma.incidentReport.findMany({where:req.user?.sub==='configured-superadmin'?undefined:{authorId:req.user!.sub},orderBy:{createdAt:'desc'},select:{id:true,reference:true,title:true,category:true,occurredAt:true,location:true,description:true,peopleInvolved:true,immediateActions:true,confidentiality:true,status:true,adminNotes:true,authorId:true,authorRole:true,authorName:true,attachmentName:true,attachmentMime:true,attachmentSize:true,verificationHash:true,createdAt:true,updatedAt:true}})).map(clean))))
incidentReportsRouter.post('/',upload.single('attachment'),asyncHandler(async(req:AuthenticatedRequest,res)=>{const data=input.parse(req.body),now=new Date(),reference=`KCS-IR-${now.getUTCFullYear()}-${randomUUID().slice(0,8).toUpperCase()}`;const u=req.user!.sub==='configured-superadmin'?null:await prisma.user.findUnique({where:{id:req.user!.sub},select:{firstName:true,middleName:true,lastName:true}});const authorName=u?[u.lastName,u.middleName,u.firstName].filter(Boolean).join(' '):'KCS Nexus SuperAdmin';const verificationHash=createHash('sha256').update([reference,req.user!.sub,data.title,data.occurredAt,now.toISOString()].join('|')).digest('hex');const report=await prisma.incidentReport.create({data:{...data,reference,occurredAt:new Date(data.occurredAt),authorId:req.user!.sub,authorRole:req.user!.role.toUpperCase() as any,authorName,verificationHash,attachmentName:req.file?.originalname,attachmentMime:req.file?.mimetype,attachmentSize:req.file?.size,attachmentData:req.file?.buffer}});return success(res,clean(report),'Report submitted',201)}))
incidentReportsRouter.get('/verify/:reference',asyncHandler(async(req,res)=>{const report=await prisma.incidentReport.findUnique({where:{reference:getRouteParam(req.params.reference)},select:{reference:true,title:true,status:true,authorRole:true,verificationHash:true,createdAt:true,updatedAt:true}});if(!report)throw new ApiError(404,'Authenticity record not found');return success(res,report)}))
incidentReportsRouter.get('/:id/attachment',asyncHandler(async(req:AuthenticatedRequest,res)=>{const report=await prisma.incidentReport.findUnique({where:{id:getRouteParam(req.params.id)}});if(!report)throw new ApiError(404,'Report not found');if(req.user?.sub!=='configured-superadmin'&&report.authorId!==req.user?.sub)throw new ApiError(403,'Access denied');if(!report.attachmentData||!report.attachmentName||!report.attachmentMime)throw new ApiError(404,'No attachment');res.type(report.attachmentMime).set('Content-Disposition',`attachment; filename*=UTF-8''${encodeURIComponent(report.attachmentName)}`).set('X-Content-Type-Options','nosniff');return res.send(Buffer.from(report.attachmentData))}))
incidentReportsRouter.patch('/:id/status',requireSuperAdmin(),asyncHandler(async(req,res)=>success(res,clean(await prisma.incidentReport.update({where:{id:getRouteParam(req.params.id)},data:status.parse(req.body)})),'Report updated')))
